### ISSUE TITLE
Ej 28

### ISSUE THREAD

**Issue by ThomasR62875** [marcelogarberoglio/PI#10]
Hola, estuve intentando este ejercicio y no se que esta  mal en mi codigo, el primer ejemplo del test lo pasa, pero el resto ya no. 

#include "getnum.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#define ABZ return 0;
#define CANT_VOCAL 5
#define VOCAL(c) c=='a' ? 1: (c=='e' ? 1: (c=='i' ? 1: (c=='o'? 1: (c=='u' ? 1:0))))
#define ERROR 0
#define EXITO 1

int elimVocales(char s[], int m[][CANT_VOCAL], int filas)
{
    //tengo q leer el string, verficar con una macro las letras q no sean vocales, y copiarlas en el propio string las vocales dejandolas de lado (esto a partir de un if)
    //con otros ifs, o un switch, cada vez que haya una vocal debo rellanr la matriz, siempre teneidno en cuenta el limite de filas
    // si es a-A, col=0, e-E col=1 y asi.

    int l, j=0, a=0, e=0, i=0, o=0, u=0;
    for(l=0; s[l]; l++){
        tolower(s[l]);
        if(!(VOCAL(s[l]))){
            s[j++]=s[l];
        }
        else if(VOCAL(s[l]) && a<filas && e<filas && i<filas && o<filas && u<filas){
            if(s[l]=='a'){
                m[a++][0]=l;
            }
            if(s[l]=='e'){
                m[e++][1]=l;
            }
            if(s[l]=='i'){
                m[i++][2]=l;
            }
            if(s[l]=='o'){
                m[o++][3]=l;
            }
            if(s[l]=='u'){
                m[u++][4]=l;
            }
        }
        else
            ABZ
    }
    s[j]=0;
    m[a][0] = -1;
    m[e][1] = -1;
    m[i][2] = -1;
    m[o][3] = -1;
    m[u][4] = -1;

    return 1;
}

**Comment by ThomasR62875** [comment]
Te dejo el test a mano. 

int main(void) {
    int m[6][CANT_VOCAL];
    char s[] = "las buenas ideas escasean, si";

    assert(elimVocales(s, m, 6) == EXITO);
    /*for (int k = 0; s[k]; k++) {
        printf("%c", s[k]);
    }*/
    printf("%c", m[0][2]);
    assert(strcmp(s, "ls bns ds scsn, s") == 0);
    assert(m[0][0] == 1);
    assert(m[1][0] == 8);
    assert(m[2][0] == 14);
    assert(m[3][0] == 20);
    assert(m[4][0] == 23);
    assert(m[5][0] == -1);

    assert(m[0][1] == 6);
    assert(m[1][1] == 13);
    assert(m[2][1] == 17);
    assert(m[3][1] == 22);
    assert(m[4][1] == -1);

    assert(m[0][2] == 11);
    assert(m[1][2] == 28);
    assert(m[2][2] == -1);

    assert(m[0][3] == -1);

    assert(m[0][4] == 5);
    assert(m[1][4] == -1);

    strcpy(s, "las buenas ideas escasean, si");
    assert(elimVocales(s, m, 1) == ERROR);
    assert(strcmp(s, "las buenas ideas escasean, si") == 0);
    assert(m[0][0] == -1);
    assert(m[0][1] == -1);
    assert(m[0][2] == -1);
    assert(m[0][3] == -1);
    assert(m[0][4] == -1);


    assert(elimVocales(s, m, 5) == ERROR);
    assert(strcmp(s, "ls bns ds scsan, s")==0);
    assert(m[0][0] == 1);
    assert(m[1][0] == 8);
    assert(m[2][0] == 14);
    assert(m[3][0] == 20);
    assert(m[4][0] == -1);

    assert(m[0][1] == 6);
    assert(m[1][1] == 13);
    assert(m[2][1] == 17);
    assert(m[3][1] == 22);
    assert(m[4][1] == -1);

    assert(m[0][2] == 11);
    assert(m[1][2] == 28);
    assert(m[2][2] == -1);

    assert(m[0][3] == -1);

    assert(m[0][4] == 5);
    assert(m[1][4] == -1);

    printf("OK!\n");
    return 0;
}

**Comment by marcelogarberoglio** [comment]
tolower es una función, no puede cambiar el parámetro.
Y si hicieras 
s[l] =   tolower(s[l]);
también estaría mal porque estarías modificando el string. Dejá el resultado en una variable.
