### ISSUE TITLE
Consulta sobre datos

### ISSUE THREAD

**Issue by Franco-A-Ghigliani** [marcelogarberoglio/PI#100]
Buenas tardes profe. 
Quería consultar sobre la consigna a nivel generalidad del TAD:
Los IDs de los sensores, en el ejemplo, comienzan en 1 y se mantienen consecutivos entre sí. Aunque sabemos que no nos debemos basar del todo en estos ejemplos, quería saber si deberíamos contemplar el caso en el cual los IDs arranquen en un número considerablemente mayor y/o no sean números cercanos entre sí.
Muchas gracias.

**Comment by marcelogarberoglio** [comment]
No necesariamente vienen ordenados, y viendo los datos, si bien puede haber un id que no se use, yo asumiría que, si por ejemplo hay en total 100 sensores, no habrá sensores con número mucho mayor a 100, por ejemplo 150, 200 y menos aún 3500 o 45000

**Comment by Franco-A-Ghigliani** [comment]
Muchisimas gracias <3
