### ISSUE TITLE
consulta TP

### ISSUE THREAD

**Issue by valentinamarti** [marcelogarberoglio/PI#101]
Buenas tardes, queríamos saber si los ID de los sensores los tenemos que tener en cuenta que arrancaran desde el ID 1, o si nos pueden pasar desde el ID 40 al ID 100 por ejemplo.
Porque saber eso nos podría ayudar a hacerlo más eficiente.

Muchas gracias :)

**Comment by marcelogarberoglio** [comment]
Eso ya se contestó: https://github.com/marcelogarberoglio/PI/issues/100

**Comment by valentinamarti** [comment]
muchas gracias
