### ISSUE TITLE
Consulta TPE - Estructura del CDT

### ISSUE THREAD

**Issue by LucasCampoli** [marcelogarberoglio/PI#102]
Buenas tardes!! Nosotros somos un grupo de 3, por lo que vamos a presentar las 3 primeras querys. Queriamos saber si la estructura del CDT tiene que estar pensada para realizar las 5 de forma eficiente(como era en el parcial que tenias que tener en cuenta tambien las funciones que no ibas a implementar), o solo las que vamos a hacer. 
Además, estamos pensando en si hacer un vector estatico o una lista de los años, podemos suponer que antes de un año (por ejemplo 1900) no hay mediciones? O podemos llegar a recibir mediciones de cualquier año(por ejemplo 1020). Muchas gracias

**Comment by marcelogarberoglio** [comment]
Por las 3 o 5 queries ya se contestó: https://github.com/marcelogarberoglio/PI/issues/97
No creo que tuvieran sensores en el 1020, al menos no electrónicos.

**Comment by LucasCampoli** [comment]
Perfecto, muchas gracias!!
