### ISSUE TITLE
Pregunta query 2 y 3

### ISSUE THREAD

**Issue by pi-na** [marcelogarberoglio/PI#103]
Hola profe, como estas?
Te hago una pregunta, estamos viendo como plantear el CDT para el query 2 y 3, con respecto a los datos divididos por AÑO.
Pensamos hacer un vector de años, y crear un define en el .h "AÑOMIN". Luego, haríamos realloc para agrandar el vector cada vez que se intenta cargar un dato de un año que no entraría en el vector existente.
Entonces, el usuario debería ver el .h y modificar el define de AÑOMIN si lo necesita para la base de datos que usara con nuestro programa. Es correcto aprovechar un define en el .h para esta situación? Y si es así, seria necesario validar que cada año que se lee es mayor al AÑOMIN, o podemos contar con que el usuario usara el programa de forma correcta? Es decir, si se encuentra que el año es menor al AÑOMIN, deja un error y para de correr las funciones (no aborta la ejecución). 
El problema seria que si no hacemos validación, y el usuario usa el programa de forma incorrecta, se daria a lugar a que nuestro programa haga una acceso a un espacio de memoria invalida. Adjunto screenshot relevante.
Muchas gracias!
<img width="434" alt="Screen Shot 2022-12-07 at 18 32 44" src="https://user-images.githubusercontent.com/112183921/206301581-09f09af8-0fb0-4406-8f29-f1cb44f651de.png">

**Comment by marcelogarberoglio** [comment]
Muy bonito el perrito, como los de la reina, no?
Lamentablemente sobre cómo deben implementarlo no podemos ayudarlo. Tienen que poder resolverlo entre uds, con las herramientas, conceptos y consejos que fuimos dando durante el cuatrimestre. Por ejemplo, que el backend debe aplicar programación defensiva, y tienen que diseñarlo pensando que alguien hará un front distinto al de uds.

**Comment by pi-na** [comment]
Entendido, muchas gracias!
