### ISSUE TITLE
consultas TPE: sensor roto

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#104]
buenas tardes, queriamos consultar lo siguiente:
-si un sensor esta registrado como roto(R), pero aun asi tiene datos registrados, esos datos los tomamos o simplemente los descartamos?

**Comment by marcelogarberoglio** [comment]
Cito el comienzo de la página 3 del enunciado:
"Si al procesar una medición, ésta proviene de un sensor que no está incluído en este archivo, o está incluido pero tiene el estado Removido, entonces se ignora esa medición. "
Creo que es claro.

**Comment by julianBogado1** [comment]
perfecto, gracias 👍
