### ISSUE TITLE
Consulta TPE - makefile

### ISSUE THREAD

**Issue by nnicokim** [marcelogarberoglio/PI#105]
Hola Marcelo, me gustaria consultarte acerca de una duda sobre el COMPILER del makefile. Se puede pasar por variable el compilador y no predefinirlo en el makefile ya que cada integrante del grupo tiene un compilador distinto? 
ej. del comando: CC=gcc-11 make all
Saludos.

**Comment by marcelogarberoglio** [comment]
Nosotros vamos a probarlo en pampero, generando el ejecutable usando únicamente make, sin parámetros, y debe usar gcc, la última versión instalada en pampero.
Si en alguna de las computadoras que usan para desarrollar no usan "gcc:", pueden hacer que "gcc" sea un alias para el compilador que usen
