### ISSUE TITLE
Consulta TPE

### ISSUE THREAD

**Issue by AgusAlonso1** [marcelogarberoglio/PI#106]
Buen día Marcelo
Tenia una duda acerca de la implementación de una función para validar los malloc usando como parámetro un void *.
Mi duda es si al llamar esta función con un puntero que no sea de tipo void me tira algún warning.

```
void validateAlloc(void * pointer) {
    if (pointer == NULL) {
        fprintf(stderr,"No se pudo reservar memoria.");
        exit(1);
    }
}
```
Muchas gracias!

**Comment by marcelogarberoglio** [comment]
> Mi duda es si al llamar esta función con un puntero que no sea de tipo void me tira algún warning.

Eso lo pueden verificar fácilmente uds. Por ejemplo

int * p = NULL;
validateAlloc(p);

Al compilar podrán ver si tira warnings o no. Aunque en realidad, si usaron realloc ya deberían saber la respuesta a esa pregunta. O tal vez no entendí bien cuál es la duda.
