### ISSUE TITLE
Consulta mediciones

### ISSUE THREAD

**Issue by AlekDG** [marcelogarberoglio/PI#107]
Es posible que hayan años en donde no se utilizó ningun sensor?
Por ejemplo, si se hizo este estudio en 2011 y 2013 pero no 2012.

**Comment by AlekDG** [comment]
Tambien pregunto: Es posible que todos los sensores esten inactivos en el csv?

**Comment by marcelogarberoglio** [comment]
Sería raro que un año entero no haya mediciones, pero por otro lado nada impediría que alguien decida armar un archivo con sólo dos años para comparar, por ejemplo el 2011 y 2013 pero no 2012
Con respecto a lo segundo, en el enunciado no dice que seguro hay datos, o que hay al menos un sensor activo.
