### ISSUE TITLE
Año mínimo de las lecturas

### ISSUE THREAD

**Issue by Secreto31126** [marcelogarberoglio/PI#108]
¿Podemos asumir que nunca habrá lecturas previas al 2000? Si no, ¿Hay algún año mínimo que podamos usar?

**Comment by marcelogarberoglio** [comment]
Ya se contestó si tienen que tomar como válido cualquier año. En principio sería razonable que haya un año mínimo, en el cual no fuera posible que hubiera sensores. En todo caso, un año menor al mínimo debería tratarse de la misma forma que sqrt trata a un negativo.
