### ISSUE TITLE
Error en el archivo htmltable.c funcion: newTable

### ISSUE THREAD

**Issue by nnicokim** [marcelogarberoglio/PI#109]
Hola Marcelo! Encontramos un error en el file, al final de la funcion newTable, falta ejecutar la funcion fclose(file);. Cuando ejecutamos el programa sin el cambio, nos advertia de un segmantation fault y agregando esta linea, funciona todo ok. Me gustaria saber si es correcta nuestra modificacion.
Saludos.

**Comment by marcelogarberoglio** [comment]
No, no es correcta la modificación. ¿A qué te referís con "agregando esta línea funciona todo ok"? Además de hacer newTable, ¿Agregaron algún dato?
Guíense por el programa de prueba -es muy simple- que figura en la misma carpeta.

**Comment by nnicokim** [comment]
Nos equivocamos nosotros. Al tener errores en el medio del programa, no se llegaba a las funciones htmlClose y por ende, pensamos que agregando la funcion fclose(file); en htmlTable.c se solucionaba. Mil disculpas Marcelo.
