### ISSUE TITLE
Pregunta sobre el almacenamiento de los datos en memoria

### ISSUE THREAD

**Issue by pi-na** [marcelogarberoglio/PI#112]
Hola profe,
Tenemos una duda con la consigna del trabajo. En la consigna se aclara que "Para el almacenamiento de los datos en memoria se deberá desarrollar al menos un TAD".
¿Esto significa que debemos desarrollar un TAD adicional que se encargue exclusivamente del almacenamiento de los datos en memoria, y que sea independiente del TAD que utilizamos en el back-end para manejar los archivos recibidos? O simplemente se refiere a que la estructura que se le da a los datos una vez que están en memoria debe ser manejada por el TAD de back-end? 
Muchas gracias.

**Comment by marcelogarberoglio** [comment]
En la cursada vimos varios TADs, principalmente para el almacenamiento de datos. Pues bien, en el TPE tienen que manejar muchos datos, lo que pide la consigna es que los almacenen en un TAD, l;a frase "al menos un TAD" quiere decir que tienen que tener por lo menos uno. Si uds consideran que es mejor tener más de uno, entonces pueden desarrollar otros TADs.
