### ISSUE TITLE
Consulta TPE final

### ISSUE THREAD

**Issue by ManuSanta12** [marcelogarberoglio/PI#113]
Hola! Queríamos consultar si tenemos información sobre a partir de que año se realizaron las mediciones y si podemos considerar que estas son hasta 2022?
Gracias!

**Comment by marcelogarberoglio** [comment]
Sobre "a partir de qué año" ya se contestó, más de una vez.
Con respecto a que sean sólo hasta 2022, deberían encararlo como un desarrollo, que si bien lo vamos a usar ahora por primera vez, no debería ser la última. Salvo que funcione mal, la idea sería poder seguir usándolo en el futuro.

**Comment by ManuSanta12** [comment]
Perfecto muchas gracias!
