### ISSUE TITLE
Duda con el .h del htmlTable

### ISSUE THREAD

**Issue by berni-245** [marcelogarberoglio/PI#114]
Buenas Marcelo! 
Puede que en el htmlTable.h falte el "#define __ctable_h_"? Es que estaba probando incluir el .h tanto en nuestro main como en un archivo aparte y me tira un warning de que redefinimos dos veces el tipo de dato htmlTable con el typedef. Pregunto porque en el .h está el ifndef __ctable_h_, pero no el define, y no sé si podría modificar el archivo para agregar el define.
La librería de html estaba en este link https://drive.google.com/drive/u/1/folders/1ANJGDZ1O17FmY7rAcn9tLouZwuYUY3MQ
Muchas gracias!

**Comment by marcelogarberoglio** [comment]
Sí, faltaba. Recién lo agregamos. Gracias.

**Comment by berni-245** [comment]
Entonces también lo agrego en el nuestro, muchas gracias por confirmar Marcelo!
