### ISSUE TITLE
Consulta TPE - Comentarios

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#117]
Buenas, en el enunciado dice:
`Tanto la biblioteca como el front-end deben estar correctamente comentados y en el caso de [...]`

Primero, a qué se refieren con `correctamente`? Es bastante subjetivo eso.
Segundo, hay que comentar **todas** las funciones? Hay algunas que no parecen necesarios los comentarios dado el nombre, tipo y parámetros de la función. Por ejemplo, el .h para uno de nuestros ADTs es el siguiente:

Está bien ese nivel de comentario? Como decía, algunas funciones como `SensorListLength()` me parece que ya son bastante autodescriptivas. Y las que sí están comentadas están bien o falta algo/hay que hacerlo de otra manera?

**Comment by marcelogarberoglio** [comment]
Sobre los comentarios se habló en la presentación 2 (slides 15 y 16) y cuando vimos funciones "Cada prototipo de función debe ser precedido por un prólogo (comentario) que indique qué hace y cómo usarla."
También pueden basarse en los .h del tp11 sobre cómo esperamos que estén comentados los prototipos de las funciones.
No deberías estar posteando diseño o código acá.

**Comment by fmorroni** [comment]
Hola Marcelo, ahí saqué el código. Eran solo los prototipos así que pensé que no habría problema.
Y okay lo de los comentarios, me fijo si tengo tiempo gracias.
