### ISSUE TITLE
Consulta TPE: abortar ejecucion

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#118]
Buenos dias, no termino de entender una aclaracion en la consigna:
![image](https://user-images.githubusercontent.com/113400047/206905583-6bb0a502-7222-477b-8b95-9fa50d44beb0.png)

Nosotros en esta ocasion no deberiamos usar exit() en ninguna ocasion? o si lo podemos usar, solo que unicamente en el front-end?

**Comment by marcelogarberoglio** [comment]
Sí, es lo que dice el párrafo: en caso de detectar que no tiene sentido seguir con la ejecución, esa decisión la debe tomar el front, no el back.

**Comment by julianBogado1** [comment]
gracias, saludos
