### ISSUE TITLE
Manipulacion de archivos

### ISSUE THREAD

**Issue by LucasCampoli** [marcelogarberoglio/PI#119]
Buenas tardes!! Viendo el power point queria consultar si fopen y fclose se considera del front. Porque al modularizar las queries en funciones, queria saber si query podia crear el file, o si eso estaba mal, y tenia que pasarle como arg el file ya abierto desde el front para que lo modifique.

**Comment by marcelogarberoglio** [comment]
Sobre la lectura y escritura de archivos ya se respondió. Sobre detalles de implementación dijimos que no íbamos a contestar.

**Comment by LucasCampoli** [comment]
Gracias!
