### ISSUE TITLE
duda enum, ej 33 tp6

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#12]
Buenas tardes, estaba tratando de resolver el ej 33 usando un enum pero la forma en la que lo estaba usando no funciona y queria saber si se puede hacer algo parecido o directamente lo estoy pensando mal.
lo que estaba tratando de hacer para codificar el mensaje era lo siguiente:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
void codificar(char * mensaje, char * alf, char cod[]){
	typedef enum{A=0,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z}Tletras;
	for(int i=0; *mensaje; mensaje++; i++){
		cod[i]=alf[*mensaje];
	}
}
`

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

la intencion era tomar cada letra del mensaje y pasarla como parametro, y que el enum se encargue de pasarla a indice numerico
por ejemplo: alf[A] deberia ser alf[0]
obviamente no funciona, de hecho se soluciona facil haciendo (*mensaje -'A'), pero queria saber si se puede hacer algo parecido

**Comment by julianBogado1** [comment]
aprovecho y pregunto otra cosa de este mismo ejercicio.
para armar el abecedario con el que me voy a manejar asumi que me pasaban uno con todas las letras, pero cuando vi el test me di cuenta que me pasan un vector vacio y que tiene tamaño 100.
queria saber si estaria bien primero llenarlo con las letras A-Z, y despues mezclarlo, o deberia encontrar una forma de crearlo ya mezclado? porque de la forma que lo estaba haciendo me quedaban letras repetidas

**Comment by marcelogarberoglio** [comment]
Por los enum: no, no sirve hacer eso, sino obtener la posición restando el ascii de la 'A'. La idea sería hacer algo parecido a lo que ya hicimos en la teórica. La parte de codificar no debe ser distinta a lo que ya vimos.

Por el otro tema, de cómo armar el diccionario, los pasos que vos mencionás son los mismos que hacemos nosotros: primero llenarlo de la A a la Z y luego mezclarlo, la única diferencia es que está modularizado distinto. La idea está bien, si te quedan duplicados es porque hay un error en la implementación, pero no en la idea.

**Comment by julianBogado1** [comment]
ahh ok, muchas gracias 😎👍
