### ISSUE TITLE
Consulta query 5

### ISSUE THREAD

**Issue by ManuSanta12** [marcelogarberoglio/PI#120]
Buen día, quería consultar si en la query 5 las mediciones con 0 peatones habría que tenerlas en cuenta o no?

**Comment by marcelogarberoglio** [comment]
En el enunciado dice "en la medición más antigua del sensor". Si no hay mediciones para ese sensor, no se debe informar (no hay fecha más antigua). Pero si la medición más antigua es con 0 personas, entonces sí, se debe informar esa fecha aunque no haya pasado nadie.

**Comment by ManuSanta12** [comment]
Muchas gracias!
