### ISSUE TITLE
Ej 3 Tp_03

### ISSUE THREAD

**Issue by za0sec** [marcelogarberoglio/PI#124]
Hola Marcelo, en este ejercicio, nos pide que el numero de lineas no exceda las 15. Nose si con esto se refiere a que tiene que quedar con buen estilo, porque hice un codigo con buen estilo que llevaba unas 17 lineas y despues hice uno que es MUY feo y tiene 11 lineas.
Queria saber si esta bien.
Este es el codigo con 11 lineas: 

```
#include <stdio.h>
#include "../../libreria/getnum.h"
int main(){
  double a;
  do
    a = getdouble("Cuanto vendiste esta semana?");
  while( a < 0 );
  a <= 1000 ? (a = 300) : (a > 1000 && a <= 2000) ? (a = ((a * 0.05) + 300.00)) : (a > 2000 && a<= 4000) ? (a = ((a*0.07) + 300.00)) : (a = ((a*0.09) + 300.00));
  printf("Tu ganancia es de $%.2f\n", a);
  return 0;
}
```
como veras, es un oneliner pero demasiado largo y confuso.
Nose cual es tu opinion.

Este es el codigo en 17 lineas:

```
#include <stdio.h>
#include "../../libreria/getnum.h"
int main(){
  double a;
  do
    a = getdouble("Cuanto vendiste esta semana?");
  while( a < 0 );
  if ( a <= 1000 ){
    a = 300;
  }else if ( a > 1000 && a <= 2000 ){
    a = ((a*0.05) + 300);
  }else{
    a > 2000 && a<= 4000 ? (a = ((a*0.07) + 300)) : (a = ((a*0.09) + 300));
  }
  printf("Tu ganancia es de %.2f", a);
  return 0;
}

```

**Comment by marcelogarberoglio** [comment]
Coincido que la versión más breve no tiene buen estilo.
Esmejorla versión 2. En cuanto a la cantidad de líneas, no se deben contar las líneas que tienen sólo una llave, ni los #include o la definición de la función. Te marco cuáles son las líneas a contar



#include <stdio.h>
#include "../../libreria/getnum.h"
int main(){
  **double a;
  do
    a = getdouble("Cuanto vendiste esta semana?");
  while( a < 0 );
  if ( a <= 1000 ){
    a = 300;
  }else if ( a > 1000 && a <= 2000 ){
    a = ((a*0.05) + 300);
  }else{
    a > 2000 && a<= 4000 ? (a = ((a*0.07) + 300)) : (a = ((a*0.09) + 300));**
  }
  **printf("Tu ganancia es de %.2f", a);
  return 0;**
}


por lo que queda en 12 líneas.
