### ISSUE TITLE
TP3 Ej 5

### ISSUE THREAD

**Issue by Nikkie-game-dev** [marcelogarberoglio/PI#126]
Hola!

Una consulta, se que esta es la respuesta correcta:
```
if ( (a >= 'B' && a <= 'Z') && (a != 'A' && a != 'E' && a != 'I' && a != 'O' && a != 'U'))  {
        printf("El caracter %c es una consonante mayúscula \n", a); 
```
Para el primer if, pero ¿hay alguna forma de hacer la condicion sin tener que repeter el `a !=`

Gracias!

**Comment by marcelogarberoglio** [comment]
Hola. En principio podrías usar una macro para que el código quede más claro. Por ejemplo una macro que devuelva 1 si es letra mayúscula y otra que devuelva 1 si es una vocal. Pero igualmente tendrías los a!= 5 veces en la macro.
Más adelante, cuando veamos cómo manipular strings veremos que sí hay una forma más simple y clara de hacerlo.

**Comment by Nikkie-game-dev** [comment]
Ah genial! Gracias
