### ISSUE TITLE
Duda sobre enunciado

### ISSUE THREAD

**Issue by za0sec** [marcelogarberoglio/PI#128]
Perdon, tenia una duda sobre algunos enunciados como este:
_Leer un número entero e indicar cuántos dígitos de ese número son iguales a 5.  Repetir para el caso de ser un número real, indicando cuántos 5 tiene en su parte entera y cuántos en su parte decimal. (En no más de 10 líneas el primer caso, y no más de 25 el segundo caso)._
Cuando me dice _Leer un numero entero_, me esta diciendo que use la funcion getint? Porque por ejemplo, en este mismo ejercicio la parte del numero real me salio en 6 lineas usando getchar pero el mismo enunciado dice en menos de 25 por eso me llamo la atencion.

**Comment by marcelogarberoglio** [comment]
No pidas perdón, justamente la idea de este "foro" es para contestar dudas.
Cuando dice "leer un número entero" efectivamente está diciendo que uses getint. También se podría leer con getchar e ir armando el número, pero es más simple usar getint
En cuanto a la parte del real, la idea es que se den cuenta que si usan getFloat o getDouble (o parten de una variable double) y aplican la misma idea que funciona para enteros (ir dividiendo por 10 hasta que se hace cero) funciona para la parte entera pero no funciona para la parte real.
