### ISSUE TITLE
Solución posible | TP3 - Ej14 

### ISSUE THREAD

**Issue by rluca6448** [marcelogarberoglio/PI#129]
Leer desde la entrada estándar una serie de caracteres, hasta que uno de ellos no sea una letra ni un espacio.  Luego imprimir por salida estándar  el menor alfabéticamente de ellos  respetando si fue mayúscula o minúscula, indicando además cuántas letras eran mayúsculas y cuántas minúsculas. No considerar el carácter ‘ñ’ como letra. (En no más de 15 líneas).

```
#include <stdio.h>

int main(void)
{
	int c, countmayus = 0, countminus = 0, lowestupper = '~', lowestlower = '~', lowest;
	while (((c=getchar()) >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || c == ' ')
	{
		if(c!=' ') {
			if (c>='A' && c<='Z')
			{
				lowestupper = (lowestupper < c ? lowestupper : c);
				countmayus++;
			}
			if (c>='a' && c<='z')
			{
				lowestlower = (lowestlower < c ? lowestlower : c);
				countminus++;
			}
		}
		
		putchar(c);
	}
	lowest = ((lowestlower - 52) < lowestupper ? lowestlower : lowestupper);
	printf("\nHay %i mayusculas y %i minusculas y la menor de todas es %c\n", countmayus, countminus, lowest);

	return 0;
}
```
Buenas, queria consultar que tal esta mi codigo para ese ejercicio

**Comment by marcelogarberoglio** [comment]
Está bien, sólo cambiaría dos cosas:
lowestupper, lowestlower las inicializaría con un valor numérico que me asegure que sea mayor, sin tener que conoecer la tabla ASCII, por ejemplo 255

Agregaría un else antes de 
if (c>='a' && c<='z')
Así como está ahora, primero hace las comparaciones para saber si es mayúscula. Y aún sabiendo que es mayúscula hace las comparaciones para saber si es minúscula, cosa que va a ser falso

**Comment by rluca6448** [comment]
Listo corregido, muchas gracias
