### ISSUE TITLE
Ej de parcial 

### ISSUE THREAD

**Issue by ThomasR62875** [marcelogarberoglio/PI#13]
Hola que tal, estab intentando un ej y no estoy seguro de que este bien porque al principio la verdad que me costo arrancar. 
El codigo termino siendo este: 

void playFair(const char clave[], char matriz[][DIM])
{
    int i, j, encontrada, k=0, p=0, l=0;
    char abcd[DIM*DIM]={'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
                        'r', 's','t', 'u', 'v', 'w', 'x', 'y', 'z'};

    //primero tomo las letras de la plabra por separado y las elimino del abcedario
    for(i=0; i<DIM*DIM ; i++){
        for(j=0, encontrada=0; clave[j] && !encontrada; j++){
            if(clave[j]==abcd[i]){
                encontrada=1;
            }
        }
        if(!encontrada){
            abcd[k++]=abcd[i];
        }
    }

    // segundo debo tomar cada letra de la palabra por separado, y meterla en la matriz
    for(i=0; i<DIM && clave[p]; i++){              //mientras q recorro la matriz voy colocando la palabra, si me quedo sin palabra corto
        for(j=0; j<DIM && clave[p]; j++){
            matriz[i][j]=clave[p++];
        }
    }

    // tercero relleno lo q queda de la matriz con el abcdeario recortado, sigo desde la posición donde termino el copiado del string
    for(i; i<DIM && l<k; i++){
        for(j; j<DIM && l<k; j++){             //no deberia llegar al vacio al final de el abcd recortado ya que la amtriz es de tamaño justo, igualmente uso el l<k por si acaso
            matriz[i][j]=abcd[l++];
            printf("%c ", matriz[i][j]);
        }
    }

}

**Comment by ThomasR62875** [comment]
Esta es la consigna, solo hice la primera parte. 

![image](https://user-images.githubusercontent.com/112571497/191795933-221a530d-fe31-4509-b762-5e567a497625.png)
![image](https://user-images.githubusercontent.com/112571497/191795968-2e8b411c-ba9a-4b2c-baed-33e73813fb5a.png)

**Comment by marcelogarberoglio** [comment]
No lo estás resolviendo en forma eficiente, sobre todo por el primer ciclo para sacar las letras que no van. Sería más eficiente si usás el vector auxiliar para marcar las letras que están en la clave, a medida que la vas copiando a la matriz (el segundo ciclo). Y luego completás con las letras que no salieron (excepto la j).
En el enunciado no aparece DIM, tendrías que definirla
