### ISSUE TITLE
Ej 21 Tp3

### ISSUE THREAD

**Issue by za0sec** [marcelogarberoglio/PI#130]
En este ejercicio nos piden identificar cuando un numero es capicua y cuando no.
Bueno, logre el objetivo el problema es que no lo pude reducir a 10 lineas o menos porque ya tendria que hacer algo con muy mal estilo.
Este es mi codigo:

```
#include <stdio.h> 
#include "../../libreria/getnum.h"

int main (){
  
  //Guardo en una variable el numero pedido para asi despues poder modificarlo y que no haya problemas.
  int comp = 0, i, numReves = 0, cant = 0, numPedido = getint("Dame un numero: "), numPedido2 = numPedido;
  
  //Doy vuelta el numero y me fijo cuantos digitos tiene.
  while ( numPedido != 0 ){
    numReves = (numReves+numPedido %10)*10;
    numPedido /= 10;
    cant++;
  }
  

  numReves /= 10;
  
  numPedido = numPedido2;

  //Me fijo digito por digito en el numero normal y en el que esta dado vuelta si son iguales y si lo son le agrego 1 al contador
  for ( i=1; i<=cant; i++ ){
    numPedido2%10 == numReves%10 ? comp++ : printf(" ");
  }

  //Comparo ambos contadores para ver si son iguales, si lo son, el numero es capicua.
  comp == cant ?  printf("%d es capicua\n", numPedido) : printf("%d no es capicua\n", numPedido);

  return 0;

}
```
Me queda siempre de 11 lineas. Podria, en vez de dividir por 10 a numReves, dividirlo en cada linea que lo llamo pero me pareceria muy de mak estilo. Alguna sugerencia a tener en cuenta?

**Comment by marcelogarberoglio** [comment]
Se puede no sólo eliminar algunas líneas sino también hacerlo más eficiente, por ejemplo al final del primer ciclo hacés
  numReves /= 10;
Eso es porque dentro del ciclo primero le sumás el dígito y luego multiplicás por 10, entonces tenés que "deshacer" el último paso. Teniendo en cuenta que numReves empieza en cero podrías primero multiplicar por 10 y luego sumar el dígito

Y luego está este ciclo
//Me fijo digito por digito en el numero normal y en el que esta dado vuelta si son iguales y si lo son le agrego 1 al contador
  for ( i=1; i<=cant; i++ ){
    numPedido2%10 == numReves%10 ? comp++ : printf(" ");
  }
Además de ser bastante feo lo del printf (que te va a retornar 1), el ciclo mucho sentido no tiene, ya que lo que estás haciendo es verificar que todos los dígitos de un número sean iguales a los dígitos de otro número, ¿no es lo mismo que preguntar si los números son iguales?

Y en cuanto a estilo, tampoco está muy bien el último condicional, ya que lo estás usando para ejecutar un printf o ejecutar otro printf, en estos casos es más claro usar un if, o sinó usar el condicional como vimos en algunos ejemplos de la clase, o sea

printf("%d%s es capicua\n", numPedido,   comp == cant ?  "" :  " no");

Haciendo los cambios mencionados te ahorrás además la variable cant (y la línea en la cual se incrementa)

**Comment by za0sec** [comment]
si es verdad estaba todo muy feo pero el problema fue que en el momento no se me ocurria algo mejor, ahora, con los arreglos que me mencionaste y pensando un poco logre dejarlo bastamte mas pulido y de 8 lineas.
Me habia dado cuenta, ademas de que en el ciclo for era mas eficiente chequear el numero entero, que en realidad el ciclo que mande solo chequeaba el ultimo numero de cada numero, osea recontra ineficiente y si ponias un numero determinado no funcionaba ajajja.
Te lo dejo para una ultima correccion, me pude ahorrar tanto la variable cant como la cont y la i:

```
#include <stdio.h> 
#include "../../libreria/getnum.h"

int main (){
  
  //Guardo en una variable el numero pedido para asi despues poder modificarlo y que no haya problemas.
  int numReves = 0, numPedido = getint("Dame un numero: "), numPedido2 = numPedido;
  
  //Doy vuelta el numero
  while ( numPedido != 0 ){
    numReves *= 10;
    numReves += (numPedido % 10);
    numPedido /= 10;
  }
  
  numPedido = numPedido2;

  //Me fijo si el numero normal y el que esta dado vuelta si son iguales y si lo son, el numero es capicua.
  printf("%d%s es capicua\n", numPedido, numPedido == numReves ? "" : " no");


  return 0;

}

```
Otra ultima pregunta, si no retorno 0 al final de la funcion main, entiendo que no pasaria nada. Porque es que no pasaria nada y porque debemos poner el return 0? Tal vez no preste atencion si se dijo en clase pero no recuerdo.

**Comment by marcelogarberoglio** [comment]
Ahora está bien. Lo importante es haberlo hecho y luego darse cuenta que se puede hacer mejor, por eso insistimos en que hagan los ejercicios solos y si no les sale lo dejan para más adelante o piden alguna pista o cómo empezar a encararlo. SI en vez de eso van y miran la solución, no sirve, ya que cuando tengan que resolver algún problema similar no van a poder. Nadie nace sabiendo, es cuestión de intentar, equivocarse y aprender.

En cuanto a la pregunta final, el return del main sirve sólo para los casos en los cuales se ejecute desde algún script y querramos saber si termnó bien o mal, como hacían con los scripts en Introducción. O sea que si en este caso y en casi toda la guía retornás cero u otro valor no cambia nada. Pero la convención es que retorne algo distinto de cero sólo si hubo un error, por lo tanto si en este caso ponés return 1 u otro valor, a cualquiera que lea el código le llamará la atención.
