### ISSUE TITLE
Ej 5 y 6 de Tp4

### ISSUE THREAD

**Issue by za0sec** [marcelogarberoglio/PI#132]
Tengo una duda en cuanto a enunciados. El ej5 me pide esto:

_Escribir una macro MAXIMO2 que recibiendo tres parámetros, asigne al tercer parámetro el mayor de los dos primeros. Utilizarla en un programa para verificar su correcto funcionamiento. (En no más de 5 líneas)_

y lo hice asi:

```
#include <stdio.h>
#define MAXIMO2(a, b, c) { c = (a > b) ? a : b; }

int main(){
  
  int a = 10, b = 25, c;

  MAXIMO2(a, b, c);

  printf("%d", c);

  return 0;
}
```

pero luego el ej 6 me pide esto: 

_Escribir la macro MAXIMO3 para determinar el mayor de 3 valores, usando la macro definida en el ejercicio anterior. (En no más de 10 líneas). Verificar su funcionamiento invocándola desde un programa._

Lo que comprendi yo es que debo usar la macro MAXIMO2 y crear otra llamada MAXIMO3 cosa que me parecio rara pero lo hice. Tengo algun error de concepto? y de no ser asi quisiera saber si el codigo esta bien.

```
#include <stdio.h>
#include "../../libreria/getnum.h"

#define MAXIMO2(a, b, c) { c = (a > b) ? a : b; }
#define MAXIMO3(d, c, max){ max = (d > c) ? d : c; }

int main (){

  int a = getint("Dame un numero: "), b = getint("\nDame otro numero: "), d = getint("\nDame el ultimo numero: "), c, max;

  MAXIMO2(a, b, c);
  MAXIMO2(d, c, max);

  printf("El mas mas grande = %d\n", max);

}
```

**Comment by marcelogarberoglio** [comment]
Lo que se pide para MAXIMO3 es que le pase 3 expresiones y en un cuarto parámetro que debe ser una variable deje el mayor de los 3 primeros elementos, por ejemplo

int n;
MAXIMO3(3, 5, 4, n)
y debe dejar en n el valor 5
El código de la macro MAXIMO3 debe usar la macro MAXIMO2
