### ISSUE TITLE
Consulta de estilo.

### ISSUE THREAD

**Issue by za0sec** [marcelogarberoglio/PI#138]
Hola Marcelo! Queria preguntarte si el siguiente codigo tiene buen estilo y se entiende. Para ver en que lo puedo mejorar.

```
/*Escribir una función que reciba un vector desordenado de números enteros 
 *y su dimensión, y construya otro vector eliminando los valores repetidos.
 *La función deberá retornar en su nombre la dimensión del nuevo vector (La función solicitada  no debe superar las 10 líneas). */

#include <stdio.h>

int dup(const int vec[], unsigned int dim);

int main(){

  int vec[] = {5,2,7,9,2,4,12,87,45,23,7,7,4,7,23,23,41,1,5,7,3,2,5,9,12,123,1,1,1,1,45,45,5,65,67,45,23,12}; 
  
  int dim = sizeof(vec)/sizeof(vec[0]); //dim = 24


 printf("%d\n", dup(vec, dim)); // 13

}


int dup(const int vec[], unsigned int dim){
  
  int vec2[dim], cont = 0, j = 0;
  
  for ( int i=0; i<dim; i++ ){

    for ( int k = 0; k < j; k++ ){

      if ( vec[i] != vec2[k] ){

        cont++;

      }
    }

    if (cont == j){

      vec2[j++] = vec[i];

    } 

    cont = 0;
  }

  return j;

}

```

**Comment by marcelogarberoglio** [comment]
Hola,
  primero: recordá poner como título el número de ejercicio, en este caso TP06_Ej4, por ejemplo
No está bien el prototipo de la función, fijate cómo se usa en el test

#include <assert.h>
#include <stdio.h>

int
eliminaRepetidos( const int original[], int dimOrig, int resultado[]);

int main(void) {
  int v[] = { 3, 5, 1, 3, -3, 3, 5, 1};
  int res[20];
  int dimRes;

  dimRes = eliminaRepetidos(v, 0, res);
  assert(dimRes==0);

  dimRes = eliminaRepetidos(v, 1, res);
  assert(dimRes==1);
  assert(res[0]==3);

O sea, la función recibe tanto el vector original como el vector donde dejar el resulktado
Y me parece que no lo estás haciendo eficiente, ya que estás contando cuántas veces aparece. Para determinar si lo copiás o no, tenés que fijarte si ya estaba antes.

**Comment by za0sec** [comment]
Ok genial, ya me fijo los cambios. En este caso, porque le tengo que enviar el vector donde dejar el resultado si solo voy a devolver la dimension de el? (correccion) Creo q ya lo entendi. Se hace asi para que funcione correctamente el assert?

**Comment by marcelogarberoglio** [comment]
La idea es que yo en main quiero en otro vector los mismos elementos que el original pero sin repetir. Más adelante vamos a ver cómo puede hacer una funnción para crear un vector nuevo y poder devolverlo.
La dimensión la tiene que devolver para que el que llama a la función sepa cuántoos elementos quedaron, por ejemplo en el main de test para saber cuántos elementoos tiene res. Al igual que hacíamos con eliminaCeros, que la función debía retornar la nueva diemnsión, o el que hicimos en clase que leía floats hasta leer un negativo.

**Comment by za0sec** [comment]
Ok ya comprendi. Que tal ahora el codigo? sigue siendo ineficiente? Lo que hice fue, en vez de recorrer el vector nuevo todo el tiempo, comparo con los numeros anteriores del primer vector y cuando detecta que hay un repetido agrega al contador para asi tenerlo en cuenta.

```
/*Escribir una función que reciba un vector desordenado de números enteros 
 *y su dimensión, y construya otro vector eliminando los valores repetidos.
 *La función deberá retornar en su nombre la dimensión del nuevo vector (La función solicitada  no debe superar las 10 líneas). */

#include <stdio.h>
#include <assert.h>

int eliminaRepetidos(const int vec[], unsigned int dim, int vec2[]);

int main(void) {
  int v[] = { 3, 5, 1, 3, -3, 3, 5, 1};
  int res[20];
  int dimRes;

  dimRes = eliminaRepetidos(v, 0, res);
  assert(dimRes==0);

  dimRes = eliminaRepetidos(v, 1, res);
  assert(dimRes==1);
  assert(res[0]==3);

  dimRes = eliminaRepetidos(v, 2, res);
  assert(dimRes==2);
  assert(res[0]==3);
  assert(res[1]==5);

  dimRes = eliminaRepetidos(v, 4, res);
  assert(dimRes==3);
  assert(res[0]==3);
  assert(res[1]==5);
  assert(res[2]==1);


  dimRes = eliminaRepetidos(v, 8, res);
  assert(dimRes==4);
  assert(res[0]==3);
  assert(res[1]==5);
  assert(res[2]==1);
  assert(res[3]==-3);

  for (int i=0; i < 8; i++)
     v[i] =10;
  dimRes = eliminaRepetidos(v, 8, res);
  assert(dimRes==1);
  assert(res[0]==10);

  for (int i=0; i < 8; i++)
     v[i] =i;
  dimRes = eliminaRepetidos(v, 8, res);
  assert(dimRes==8);
  for (int i=0; i < 8; i++)
    assert(res[i]==i);

  puts("\nOK!");
  return 0;
}


int eliminaRepetidos(const int vec[], unsigned int dim, int vec2[]){
  
  int j = 0;

  for ( int i=0; i<dim; i++ ){

    int cont = 0;

    for ( int k = 0; k<i && cont == 0; k++ ){

      if ( vec[i] == vec[k] ){

        cont++;

      }

    }
  
    if (cont == 0){

      vec2[j++] = vec[i];
    }

  }

  return j;

}

```

**Comment by marcelogarberoglio** [comment]
Ahora cumple con lo pedido y es eficiente.
Pero fijate que se puede modularizar, por ejemplo usando la función belongs que hicimos ayer en clase.
