### ISSUE TITLE
ej 3 recu1 primer cuatri 2022

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#14]
buenas tardes, queria saber si esta bien el codigo, en particular si se puede hacer recorriendo la matriz menos de 2 veces, que es lo que hace este codigo, porque no se me ocurrio otra manera

Se que la funcion sumaCol hay que llamarla de otra manera porque esta sumando cada columna 3 veces (una por cada vez que entra al for i) 
mas alla de eso quisiera saber si hay algo mas para mejorar:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
int sumarCol(const unsigned int m[N][N], int col){
    int suma=0;
    for(int i=0; i<N; i++){
        suma+=m[i][col];
    }
    return suma;
}


int esMagica(const unsigned int m[N][N]){
    int nums[N*N]={0};
    int sumFila1=0, sumfil=0, sumcol=0;

    for(int k=0; k<N; k++){     //sumo primer fila y guardo resultado para comparar
        if(m[0][k]<=(N*N) && m[0][k]>0 && !nums[m[0][k]-1]){
            sumFila1+=m[0][k];
            nums[m[0][k]-1]=1;
        }
        else{
            return 0;        //algun numero se fue de rango o hubo un repetido
        }
    }

    for(int i=1; i<N; i++){     //empiezo desde la segunda fila y seteo las sumas en 0
        sumfil=0;
        sumcol=0;
        for(int j=0; j<N; j++){
            if(m[i][j]<=(N*N) && m[i][j]>0 && !nums[m[i][j]-1]){  //el numero donde estoy parado es 0 en el vector
                sumfil+=m[i][j];
                nums[m[i][j]-1]=1;           //ahora que ya pase lo seteo en 1 y agrego a la suma de la fila


                sumcol = sumarCol(m, j);      //hago la suma de la columna al final para no recorrer sin necesidad

            }
            else{
                return 0;   //algun numero se fue de rango o se repitio
            }
        }
        if(sumfil != sumFila1 || sumcol != sumFila1)   //alguna suma dio distinta
            return 0;
    }
    return 1;
}

**Comment by julianBogado1** [comment]
![image](https://user-images.githubusercontent.com/113400047/191860047-4d412fb4-9561-4a26-987a-a9abad6bccee.png)

**Comment by marcelogarberoglio** [comment]
Cuando ponés
  sumcol = sumarCol(m, j);      //hago la suma de la columna al final para no recorrer sin necesidad
el comentario está bien, pero estás calculando varias veces la misma suma, ya que está dentro del for, podrías cambiarlo por

  sumcol += m[j][i];

ya que la matriz es cuadrada.

Por otro lado hay código repetido, tanto al calcular cuánto deben sumar (sumando la primer fila) como dentro del for. Podrías tener una condición especial para la primer fila dentro del ciclo.

**Comment by julianBogado1** [comment]
ahh buenisimo, muchas gracias
