### ISSUE TITLE
TP.6 EJ.7

### ISSUE THREAD

**Issue by jrambau** [marcelogarberoglio/PI#144]
Buenas tardes Marcelo, te queria consultar por este ejercicio ya que no estaria sabiendo porque no pasa el test.

```c
void unirArreglos(const int ar1[],const int ar2[],int resultado[]){
int dimUnion=0,i=0,j=0;
while(((ar1[i]!=ULTVALOR)||(ar2[j]!=ULTVALOR))){
if((ar1[i] < ar2[j]) && (ar1[i] != ULTVALOR)){
    resultado[dimUnion++]=ar1[i++];
}
else if((ar1[i] > ar2[j]) && (ar2[j] != ULTVALOR)){
    resultado[dimUnion++]=ar2[j++];
}
else if((ar1[i] == ar2[j])){
    resultado[dimUnion++]=ar2[j++];
    i++;
}}
resultado[dimUnion]= ULTVALOR;
}

**Comment by marcelogarberoglio** [comment]
Podría pasar que 
ar1[i] es  10
ar2[j] es -1

deberíacopiar ar1[i], pero no "entra" al primer if
No están bien planteadas las condiciones, tendría que ser "si terminó ar2 o ar1 no terminó y es  menor que ar2, entonces copiar de ar1"

**Comment by jrambau** [comment]
ahi lo corregi pero por alguna razon al ejecutar el test entra en un ciclo infinito y eso ya me estaba pasando antes
```c
void unirArreglos(const int ar1[],const int ar2[],int resultado[]){
int dimUnion=0,i=0,j=0;
while(((ar1[i]!=ULTVALOR) || (ar2[j]!=ULTVALOR))){
if((ar1[i] < ar2[j]) && ((ar1[i] != ULTVALOR) || (ar2[j] == ULTVALOR))){
    resultado[dimUnion]=ar1[i++];
}
else if((ar1[i] > ar2[j]) && ((ar2[j] != ULTVALOR) || (ar1[i] == ULTVALOR))){
    resultado[dimUnion]=ar2[j++];
}
else if((ar1[i] == ar2[j])){
    resultado[dimUnion]=ar2[j++];
    i++;
}
dimUnion++;
}
resultado[dimUnion]= ULTVALOR;
}
`

**Comment by marcelogarberoglio** [comment]
Está mal la condición, en vez de
if((ar1[i] < ar2[j]) && ((ar1[i] != ULTVALOR) || (ar2[j] == ULTVALOR))){
tiene que ser

if( ar1[i] < ar2[j] && ar1[i] != ULTVALOR || ar2[j] == ULTVALOR){

tratá de no poner tantos paréntesis porque me parece que eso puede confundir. Lo mismo pero más claro podría ser así (sólo invertí el orden de los términos)

if( ar2[j] == ULTVALOR  ||  ar1[i] != ULTVALOR && ar1[i] < ar2[j]  ){

En base a esto, hay que revisar las otras condiciones

**Comment by jrambau** [comment]
ahi funciono gracias
