### ISSUE TITLE
Autoevaluación 3, pregunta 2

### ISSUE THREAD

**Issue by Nikkie-game-dev** [marcelogarberoglio/PI#147]
Buenas tardes,

Quería preguntarle sobre la pregunta 2, de la autoevaluación número 3, el resultado correcto es `???` mi pregunta seria porque ese es el resultado. Segun tengo entendido, lo convierte de `int` a `double` y que por tanto deberia resultar en 5.0.

Esta es la pregunta en cuestión.
![Pregunta 2](https://user-images.githubusercontent.com/54285513/230736217-ac24535b-52db-4ebc-bd4c-0829e64e6da2.png)

**Comment by marcelogarberoglio** [comment]
No, no convierte de int a double. Es lo que se menciona en el comentario.

**Comment by Nikkie-game-dev** [comment]
Osea, printf lo analiza como 00000000...0101 en IEEE754?

**Comment by marcelogarberoglio** [comment]
Algo así. Como el double ocupa 8 bytes tomará esos 4 bytes que pusiste más los 4 que sigan en memoria.

**Comment by Nikkie-game-dev** [comment]
Entiendo, ósea que tomaría 05??h

**Comment by marcelogarberoglio** [comment]
La idea es esa, en realidad no serían dos bytes sino ocho: 00 00 00 05 00 00 00 00

**Comment by Nikkie-game-dev** [comment]
Entiendo! gracias!!
