### ISSUE TITLE
ej 2 recu1 1C2022

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#15]
buenas tardes, queria saber si el codigo estaria bien, me parece que quedo medio feo y queria saber que se puede mejorar:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
int isVoc(unsigned char c){
    return (tolower(c)=='a' || tolower(c)=='e' || tolower(c)=='i' || tolower(c)=='o' || tolower(c)=='u');
}


void eliminaVoc(char s[]){
    int dimaux=0, i=0;
    char anterior=0, siguiente=0;

    for(i=0; s[i]; i++){  //se que no estoy en el primer caso ni en el ultimo
        if(s[i+1]!= '\0')
            siguiente=s[i+1];
        else if(s[i+1]=='\0')
            siguiente=0;

        if(!isVoc(s[i]))            //copio si no es vocal
            s[dimaux++]=s[i];
        else if((!isalpha(anterior) && !isalpha(siguiente)) || isVoc(anterior) || isVoc(siguiente))   //si es vocal pero la anterior y la siguiente no son letras
            s[dimaux++]=s[i];
        anterior = s[i];
    }
    s[dimaux++]='\0';
}

**Comment by julianBogado1** [comment]
![image](https://user-images.githubusercontent.com/113400047/191860324-ff888983-31fa-4197-a564-54b4d81badec.png)

**Comment by marcelogarberoglio** [comment]
Este fragmento de código

 if(s[i+1]!= '\0')
            siguiente=s[i+1];    // Si no es cero, le asigno el valor de s[i+1]
        else if(s[i+1]=='\0')    // esto es verdadero. Si es cero le asigno cero, que es el valor de s[i+1]
            siguiente=0;

se puede reemplazar por
            siguiente=s[i+1];
ya que hace lo mismo, pero en forma más simple

**Comment by julianBogado1** [comment]
claro, en ese caso no habria problemas  al operar con el 0 del string? en ningun momento se cambia pero no sabia si podia generar algun conflicto
