### ISSUE TITLE
TP6ej7

### ISSUE THREAD

**Issue by valenNovillo** [marcelogarberoglio/PI#156]
Hola Marcelo, cómo estas? Quería consultar si el estilo de este código para el ejercicio 7 del TP6  es aceptable, ya que si bien pasa el test, es muy distinto al subido en las soluciones.
Gracias!

```
#define VALOR_FINAL -1

void unirArreglos(const int v1[], const int v2[], int resultado[])
{
    int i, j, dimRes;
    for(i=0, j=0, dimRes=0; v1[i]!=VALOR_FINAL && v2[j]!=VALOR_FINAL; ) //ciclo funciona mientras ninguno de los dos arreglos haya llegado al final
    {
        if(v1[i]< v2[j])
        {
            resultado[dimRes++]=v1[i++];
        } else if(v1[i]==v2[j])
        {
            resultado[dimRes++]=v1[i++];
            j++;
        } else
            resultado[dimRes++]=v2[j++];
    }

    if(v1[i]==VALOR_FINAL) //si terminó el v1 primero, continuo completando el vector resultado con los elementos del v2
        for(;v2[j]!=VALOR_FINAL;j++)
            resultado[dimRes++]=v2[j];

    if(v2[j]==VALOR_FINAL) //si terminó el v2 primero, continuo completando el vector resultado con los elementos del v1
        for(;v1[i]!=VALOR_FINAL;i++)
            resultado[dimRes++]=v1[i];

    resultado[dimRes]=VALOR_FINAL; //termino el vector resultado con -1

}
```

**Comment by marcelogarberoglio** [comment]
Sí, está bien, ya que estás recorriendo una sola vez cada vector. Si bien está el código al final del for para copiar el resto, las condiciones dentro del for inicial quedan más simples que la solución que publicamos.
Lo que podrías sacar son los dos if, y quedaría así

 for(;v2[j]!=VALOR_FINAL;j++)
       resultado[dimRes++]=v2[j];

for(;v1[i]!=VALOR_FINAL;i++)
       resultado[dimRes++]=v1[i];

ya que si v2 terminó, no entra al primer for, y lo mismo con v1 y el segundo for

**Comment by valenNovillo** [comment]
Buenísimo! Muchísimas Graciasss

**Comment by valenNovillo** [comment]
Buenísimo! Muchísimas Gracias!!
