### ISSUE TITLE
Ejercicio 1 Recuperatorio 21/06/2018

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#18]
Buenas, quería pedir la corrección de un ejercicio. Pedía:
```
Escribir una función que, dada una matriz de N filas y N columnas determine si es un “cuadrado mágico”.
Una matriz es cuadrado mágico cuando:
● es cuadrada (NxN) (donde N es una constante simbólica)
● tiene todos los números del 1 al N2
● la suma de los elementos de cualquier fila es igual a la suma de los elementos de cualquier columna
```
## Mi código
 ```C
#define N 4 // O lo que sea.

int isMagicSquare(int M[N][N]) {
	int isMagic = 1;
	int controlSum = sumRow(M, 0);
	// validValues[i-1] will be set to 1 if 1 <= i <= N*N is in M.
	int validValues[N*N] = {0};
	for (int i = 0, rowSum = 0, colSum = 0; i < N && isMagic; ++i, rowSum = 0, colSum = 0) {
		for (int j = 0; j < N && isMagic; ++j) {
			isMagic = validateValue(validValues, M[i][j]);
			rowSum += M[i][j];
			colSum += M[j][i];
		}
		// "isMagic &&" is added in case it's already 0 from validateValue()
		isMagic = (isMagic && rowSum == controlSum && colSum == controlSum);
	}

	return isMagic;
}

int validateValue(int validValues[], int val) {
	int isValid = 1;
	if (1 <= val && val <= N*N) {
		if (validValues[val-1] == 0) {
			validValues[val-1] = 1;
		} else {
			isValid = 0;
		}
	} else {
		isValid = 0;
	}

	return isValid;
}

int sumRow(int M[N][N], int row) {
	int sum = 0;
	for (int i = 0; i < N; ++i) {
		sum += M[row][i];
	}

	return sum;
}

```

Mi duda viene más que nada en la parte `controlSum` donde estaría recorriendo "de más" una fila. Me pareció que así el código era mucho más legible que tratar por ejemplo de ir guardando siempre el valor previo o algo así, y recorrer una fila extra no me parece muy ineficiente. 
Pero bueno, justamente quería consultar cómo lo considerarían en la cátedra.

Otro tema es que cuando lo terminé de hacer y lo probé, no andaba... Lo había chequeado antes obviamente pero me había parecido que estaba bien. El error fue que me había olvidado de resetear `rowSum` y `Colsum` a 0 en cada iteración del for exterior.
Que tanto puede llegar a restar eso en el parcial?

**Comment by marcelogarberoglio** [comment]
Está muy bien así, aunque se le podrían hacer algunos pequeños retoques, por ejemplo en vez de
for (int i = 0, rowSum = 0, colSum = 0; i < N && isMagic; ++i, rowSum = 0, colSum = 0) {
   	for (int j = 0; j < N && isMagic; ++j) {

hacer

for (int i = 0;  i < N && isMagic; ++i) {
        rowSum = 0, colSum = 0;
   	for (int j = 0; j < N && isMagic; ++j) {


y dejar la función así

int validateValue(int validValues[], int val) {
  return  1 <= val && val <= N*N  &&  validValues[val-1]++ == 0;
}

con lo cual se puede ver que no es necesaria la función e incluir esa condición directamente en la función isMagicSquare

Con respecto a no resetear las variables, podría bajar hasta 0,5 puntos, considerando que el ejercicio valdría 3 ó 3,5 puntos
