### ISSUE TITLE
Ej1 Parcial 17/04/2019

### ISSUE THREAD

**Issue by za0sec** [marcelogarberoglio/PI#188]
Hola marcelo! El ejercicio pide hacer la resta entre dos vectores y pueden estar desordenados (terminan en -1). Solo vengo a chequear si en la funcion, puedo recorrer menos veces al vector v2. Porque veo que si es muy largo lo recorro muchas veces, pense en tal vex ordenar ambos vectores primero y despues hacer lo demas pero siento que no tenia mucho sentido. Alguna sugerencia?

```
#include <stdio.h>
#define FINAL -1

void resta(const int v1[], const int v2[], int resta12[]);


int main(){


  int v1[] = {1,9,2,6,3,6,-1};
  int v2[] = {3,2,8,2,-1};
  int resta12[sizeof(v1)/sizeof(v1[0])];

  resta(v1,v2,resta12);

  for (int i=0; resta12[i]!=FINAL; i++)
    printf("%d ", resta12[i]);
  
  puts("");

  int resta21[sizeof(v2)/sizeof(v2[0])];

  resta(v2,v1,resta21);

  for (int i=0; resta21[i]!=FINAL; i++)
    printf("%d ", resta21[i]);


}




void resta(const int v1[], const int v2[], int resta12[]){

  int i, j, t, band;

  for (i=0, t=0; v1[i] != FINAL; i++){

    band=0;

    for (j=0; v2[j] != FINAL; j++){

      if(v1[i] == v2[j]){

        band = 1;

    }

  }

  if(!band)
    resta12[t++] = v1[i];

  }

  resta12[t] = FINAL;
}

```

**Comment by marcelogarberoglio** [comment]
Hay que recorrer varias veces v2.
En vez del for para buscar en v2 podrías usar la vieja y confiable belongs.
Lo que no tenés que hacer es recorrer sí o sí v2 hasta el final, tenés que cortar si encontrás el elemento (de usar belongs, esto no pasaba)

**Comment by za0sec** [comment]
claro si, entiendo. Mil gracias!
