### ISSUE TITLE
2022 1C 1er parcial - Ej 2

### ISSUE THREAD

**Issue by lulostupnik** [marcelogarberoglio/PI#190]
Hola Marcelo, como estas? Con respecto a este ejercicio, te quiero hacer unas preguntas de estilo:
1) Cuando uso el operador ternario poniendo _**j = (vocal(s[0]) && consonante(s[1])) ? 0:1;**_:
- Es claro?
- Podria haber hecho que algo como _**j = !(vocal(s[0]) && consonante(s[1])**_   ? Porque no solo me interesa que me ponga en j si es verdadero o falso, sino que me interesa que en el caso donde es falso me ponga si o si el valor 1, y no se en estos operadores si hace eso, o pone cualquier valor !0
2) Cuando pongo "if(!(consonante(last_c) || consonante(next_c)))", es "correcto", o seria mejor poner **!condicion1 && !condicion2** 

Ya de antemano te agradezco y te mando un saludo,
Luciano. 
```
#include <stdio.h>
#include <ctype.h>

int vocal(char c){
	if( c == 'a' || c=='e' || c=='i' || c=='o' || c=='u'){
		return 1;
	}
	return 0;
}


int consonante(char c){
	if(!vocal(c) && isalpha(c)){
		return 1;
	}
	return 0;
}


void eliminaVoc(char s[]){

	int i,j;
	char last_c = s[0], next_c;
	
	if(!last_c){
		return;}


	j = (vocal(s[0]) && consonante(s[1])) ? 0:1; // si no es vocal dejo la pos s[0] como esta (haciendo que j=1), si es vocal y la proximo es consonante tengo que eliminarla. 
	

	for(i=1; s[i] != '\0'; i++){
		next_c = s[i+1];

		if(!vocal(s[i])){
			s[j++] =s[i];
		}else{ 
			if(!(consonante(last_c) || consonante(next_c))){ // NO elimino 
				s[j++]=s[i];
				}
		}
        last_c = s[i];
    }	
	s[j] = 0;
}
```

Pd: te pego el link del examen por si no lo tenes a mano:

https://docs.google.com/document/d/1uR5Nytlf7KNQYknIxP2mEyU3RIv38Ehytioke2_N0Lc/edit

**Comment by marcelogarberoglio** [comment]
1. A diferencia de funciones como isupper o isalpha, todos los operadores "booleanos" valen 0 ó 1, por ejemplo 
   a < b
   b == 5 && c < 3
   etc
  
   pore lo tanto no debería tener un condicional que retorne 1 ó 0 ya que es redundante
2. Es indistinto, ambas formas están bien.


Por el punto 1 es que habría que cambiar la función vocal, para que directamente sea

      return  c == 'a' || c=='e' || c=='i' || c=='o' || c=='u';

lo mismo con la función consonante

**Comment by lulostupnik** [comment]
Perfecto, muchas gracias.
