### ISSUE TITLE
Rec 2022 2C ej3

### ISSUE THREAD

**Issue by valensangui8** [marcelogarberoglio/PI#196]
Queria saber si estaba bien, es el ej 3 del recu del cuatri pasado.
El enunciado dice asi: Se desea eliminar de un string los caracteres que estén contenidos enotra cadena, y también registrar en qué posiciones estaban los caractereseliminados.Para ello se pide escribir la función int elimChars que reciba los siguientesparámetros:● text: cadena de caracteres null terminated● chars: cadena de caracteres null terminated● pos: vector de enteros, donde se irán guardando en qué posiciónestaba cada carácter eliminado (en la posición 0 el que se eliminóprimero, en la 1 el que se eliminó segundo, etc.)y retorne la cantidad de caracteres eliminados.A continuación un ejemplo de testeo, en el cual el parámetro text es breve,pero se espera -en su uso habitual- que text sea una cadena extensa, no así elstring chars.

int check(char s[], char c){
    if(strchr(s,c)!=NULL){
        return 1;
    }
    return 0;
}

int elimChars(char text[], char chars[],int pos[]){
    int i,j,contador=0;
    for(i=0,j=0;text[i];i++){
        if(!check(chars,text[i])){
            text[j++]=text[i];
        }
        else{
            pos[contador++]=i;
        }
    }
    text[j]='\0';
    return contador;
}

**Comment by marcelogarberoglio** [comment]
La función elimChar está bien.
La función check deberís ser
int check(char s[], char c){
return strchr(s,c)!=NULL;
}
o directamente poner la condición en el if de elimChar
