### ISSUE TITLE
rec 2022 2C ej2

### ISSUE THREAD

**Issue by valensangui8** [marcelogarberoglio/PI#197]
Es el pal en mat del recuperatorio. Queria saber si estaba bien y si era eficiente. y a su vez si podia usar el continue, ya que no lo vimos en profundidad y no sabia si se podia usar o no, en el caso de no poder usarlo que podria hacer para que saltee el caso q no estaria dentro de la matriz.
Escribir una función palEnMat que reciba:● una matriz cuadrada de chars de dimensión N (con N constantesimbólica previamente definida)● un puntero a entero que indica una fila● un puntero a entero que indica una columna● un stringy retorne 1 si el string se encuentra dentro de la matriz, ya sea en sentidohorizontal, vertical o diagonal y en cualquier dirección. En caso de haberlaencontrado, debe dejar en el parámetro fila la fila en que comenzó la palabraencontrada y en el parámetro columna la columna en la que comenzó la palabraindicada.

int word(char m[][N], char *s, int fila, int columna, int dx, int dy) {
    int k = 2;
    while (s[k]) {
        fila += dx;
        columna += dy;
        if (fila >= N || fila < 0 || columna >= N || columna < 0) {
            return 0;
        }
        if (m[fila][columna] != s[k]) {
            return 0;
        }
        k++;
    }
    return 1;
}

int check(char m[][N], char *s, int fila, int columna) {
    for (int i = -1; i <= 1; i++) {
        for (int j = -1; j <= 1; j++) {
            if (i == 0 && j == 0) {
                continue;
            }
            int dx = i;
            int dy = j;
            if (fila + dx >= N || fila + dx < 0 || columna + dy >= N || columna + dy < 0) {
                continue;
            }
            if (m[fila + dx][columna + dy] == s[1]) {
                if (word(m, s, fila + dx, columna + dy, dx, dy)) {
                    return 1;
                }
            }
        }
    }
    return 0;
}

int palEnMat(char m[][N], int *fila, int *col, char *s) {
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < N; j++) {
            if (m[i][j] == s[0]) {
                if (check(m, s, i, j) || s[1]==0) {
                    *fila = i;
                    *col = j;
                    return 1;
                }
            }
        }
    }
    return 0;
}

**Comment by marcelogarberoglio** [comment]
En check verificás que la segunda letra esté en una dirección y sólo en ese caso llamás a word para que se mueva en esa dirección, eso se podría simplicar, llamando directamente a word para que compare de la segunda letra en adelante.
El continue se podría eivta si en vez de los dos for usás el vector de desplazamientos como vieron en la clase del taller pasado
