### ISSUE TITLE
P6 Ej10 

### ISSUE THREAD

**Issue by ThomasR62875** [marcelogarberoglio/PI#2]
Hola, estuve intentando este ejericio. Hice un codigo y lo corrí en el test, no cumple del todo con test, y la verdad no puedo encontrar el error. (Ahora ya se que la función "cuenta" podria estar mucho mejor, pero en el momento fue lo que se me ocurrió.) 

_Consgina:_
Los laboratorios de Propulsión por Reacción tienen la representación del cielo y sus estrellas, digitalizada en una matriz bidimensional de hasta 80 columnas por 20 filas. Cada elemento de la misma representa la cantidad de luz que hay en una zona del cielo con un rango de intensidad entre 0 y 20. En el lugar de coordenadas (i,j) del cielo se considera que hay una estrella si el elemento Aij correspondiente  cumple con la siguiente relación:
		( A[i,j] + suma de las ocho intensidades circundantes ) / 9 > 10

	Escribir una función (en no más de 15 líneas) que reciba tres parámetros de entrada representando a una matriz de dichas características y sus dimensiones. Dicha función debe localizar gráficamente las estrellas en la pantalla representando las mismas con el carácter ‘*’. La función debe ignorar las aristas de la matriz. 

_Mi codigo:_

int cuenta(int m[][COLUMNAS], int i, int j)
{
    if ((m[i-1][j-1]+m[i-1][j]+m[i-1][j+1]+m[i][j-1]+m[i][j]+m[i][j+1]+m[i+1][j-1]+m[i+1][j]+m[i+1][j+1])/9>10)
        return 1;
    else
        return 0;
}

void graficar(int m[][COLUMNAS], int COL, int FIL) {
    int i, j, estrella;

    for (i=1; i<FIL-1; i++){
        printf("\n ");
        for (j=1; j<COL-1; j++) {
            estrella=cuenta(m, i, j);
            if (estrella)
                putchar('*');
            else
                putchar(' ');
        }
    }
}

**Comment by marcelogarberoglio** [comment]
Es cierto que la función cuenta se puede simplificar. No había visto el \n antes de cada fila (yo lo pondría después de cada fila). Más allá del estilo de cuenta no veo error.

**Comment by marcelogarberoglio** [comment]
Al poner el "\n " antes de cada fila, hace que la primer fila quede desplazada un lugar, tal vez sea eso lo que ves de distinto con el programa de testeo. Tendrías que hacer solamente putchar('\n'); luego de cada fila, sin el espacio

**Comment by ThomasR62875** [comment]
Ahí borre el espacio al lado del \n, pero no cambio nada en el resultado, te muestro lo que imprime: 

Edit: No creo poder mostrarlo porque los '*' no los muestra el github -.-

**Comment by marcelogarberoglio** [comment]
¿Podés adjuntar el programa completo?

**Comment by ThomasR62875** [comment]
Esto es todo lo que tengo.


int cuenta(int m[][COLUMNAS], int i, int j)
{
    if ((m[i-1][j-1]+m[i-1][j]+m[i-1][j+1]+m[i][j-1]+m[i][j]+m[i][j+1]+m[i+1][j-1]+m[i+1][j]+m[i+1][j+1])/9>10)
        return 1;
    else
        return 0;
}

void graficar(int m[][COLUMNAS], int COL, int FIL) {
    int i, j, estrella;

    for (i=1; i<FIL-1; i++){
        printf("\n");
        for (j=1; j<COL-1; j++) {
            estrella=cuenta(m, i, j);
            if (estrella)
                putchar('*');
            else
                putchar(' ');
        }
    }
}

int
main (void) {
    int cielo1[FILAS][COLUMNAS] = {{0}};

    puts("A continuación debe mostrar 8 filas en blanco");

    graficar(cielo1, FILAS, COLUMNAS);
    puts("-----------------------------");


    int cielo2[FILAS][COLUMNAS] = {
            {10, 17, 6, 15, 6, 7, 8, 9, 11, 12, 13, 15, 8, 10, 11, 13, 14, 15, 18, 20, 11, 8, 2, 3, 12, 13, 11, 3, 9, 20},
            {18, 17, 6, 5, 6, 7, 8, 9, 11, 12, 13, 5, 8, 10, 1, 13, 14, 15, 18, 20, 11, 8, 2, 3, 12, 13, 11, 3, 9, 20},
            {10, 15, 16, 15, 6, 17, 8, 19, 11, 12, 13, 1, 8, 10, 11, 1, 14, 15, 18, 20, 11, 8, 2, 3, 12, 23, 11, 3, 9, 20},
            {12, 2, 6, 5, 16, 7, 8, 9, 1, 12, 13, 15, 8, 10, 1, 13, 14, 15, 18, 20, 11, 8, 2, 3, 12, 23, 11, 3, 9, 20},
            {8, 5, 4, 15, 6, 7, 8, 9, 12, 12, 13, 5, 8, 10, 11, 13, 14, 15, 18, 20, 11, 8, 12, 3, 12, 23, 11, 3, 9, 20},
            {20, 19, 18, 15, 16, 7, 8, 9, 11, 12, 13, 15, 18, 10, 11, 13, 14, 15, 18, 20, 11, 8, 12, 3, 12, 23, 11, 3, 9, 20},
            {10, 9, 9, 15, 16, 7, 8, 9, 12, 12, 13, 11, 8, 10, 1, 13, 14, 15, 18, 20, 11, 8, 2, 13, 12, 23, 11, 3, 9, 20},
            {10, 12, 9, 6, 16, 7, 8, 9, 15, 12, 13, 15, 18, 10, 11, 13, 14, 15, 18, 20, 11, 8, 2, 3, 12, 23, 11, 3, 9, 20},
            {10, 7, 9, 15, 6, 7, 8, 9, 11, 12, 13, 15, 8, 10, 1, 10, 14, 15, 18, 20, 11, 8, 2, 3, 12, 23, 11, 3, 9, 20},
            {10, 17, 16, 15, 6, 7, 8, 9, 11, 12, 13, 15, 8, 10, 11, 3, 14, 15, 18, 20, 11, 8, 2, 3, 12, 23, 11, 3, 9, 20},
    };

    puts("A continuación su función debe mostrar esto:");
    puts(" **     **      *****    *");
    puts(" *              *****   ***");
    puts("         *      *****   ***");
    puts("   *     ****  ******   ***");
    puts(" ****    ***   ******   ***");
    puts(" ****   *****  ******   ***");
    puts("   *    *****   *****   ***");
    puts(" **     *****   *****   ***");

    puts("-----------------------------");
    puts("Y muestra esto:");
    graficar(cielo2, FILAS, COLUMNAS);
    puts("-----------------------------");

    return 0;
}

**Comment by marcelogarberoglio** [comment]
Creo que tenés al revés los parámetros en graficar, vos ponés

void graficar(int m[][COLUMNAS], int COL, int FIL) {

y en el ejemplo pasamos primero filas y luego columnas

**Comment by fmorroni** [comment]
Tengo una pregunta de enunciado y sobre cómo se evalúan los ejercicios. 
Si me dicen "Escribir una función `foo()` en no más de 15 líneas", tienen en cuenta también la cantidad de líneas de funciones auxiliares que cree, o sólo las de `foo()`?
Y qué tan estrictos son con eso? Si me queda de 16 líneas por ejemplo estaría mal/restaría puntos?

**Comment by marcelogarberoglio** [comment]
Si se crean funciones auxiliares también se deben sumar esas líneas.
En cuanto a estrictos, no solemos tomar en el parcial ejercicios con límite de líneas; están puestos en las guías para que se vean forzados a pensar distintas formas de resolverlo, hasta encontrar con el de menor cantidad de líneas. Se supone que para el parcial, como hicieron las guías, ya están capacitados para escribir código correcto, modularizado, claro y eficiente.

**Comment by marcelogarberoglio** [comment]
Agrego: si no se contaran las líneas de funciones auxiliares, entonces siempre podrían resolverlo en una línea, que sería la llamada a otra función.
