### ISSUE TITLE
ej 6 mastermind

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#20]
buenas tardes,  el sanitizer me tira un error de memory leaks, creo q es cuando falta hacer free, pero no entiendo por que, ya que el codigo tiene el free en el main:

```C
#define X 5

//genera nro aleatorio de X digitos y lo deja en un vector
void generaAleatorio(int * incognita){

    srand(time(NULL));

    int digitos[9]={0};

    int * paux = malloc(X*sizeof(int));
    int elem, i=0;

    while(i<X){
        elem=randInt(1,9);

        if(!digitos[elem-1]){     //si el digito no estaba repe, lo marco repe, lo guardo y avanzo
            digitos[elem-1]=1;
            paux[i++] = elem;
        }
    }
    incognita = paux;

}

int main(void){
    int * p;
    generaAleatorio(p);
    free(p);
    return 0;
}

```

este es el prompt del sanitizer
![image](https://user-images.githubusercontent.com/113400047/193344156-3ef1552e-7dd4-4d36-9d85-e394c6be67b8.png)

**Comment by julianBogado1** [comment]
puede ser porque estoy asignando incognita que en realidad es una copia del puntero en main? 
igualmente, el malloc se espera que nosotros lo hagamos en la funcion o que se haga desde el main?

**Comment by marcelogarberoglio** [comment]
El problema es que una función no puede modificar una variable, sea del tipo que sea, entonces cuando hacés
    generaAleatorio(p);
p vale lo mismo que antes de invocar a la función, y entonces fala al hacer el free, porque no está recibiendo la función free la dirección de comienzo de un bloque, lo correcto sería


#define X 5

//genera nro aleatorio de X digitos y lo deja en un vector
int * generaAleatorio(){

    int digitos[9]={0};

    int * paux = malloc(X*sizeof(int));
    int elem, i=0;

    while(i<X){
        elem=randInt(1,9);

        if(!digitos[elem-1]){     //si el digito no estaba repe, lo marco repe, lo guardo y avanzo
            digitos[elem-1]=1;
            paux[i++] = elem;
        }
    }
    return  paux;
}

int main(void){

    srand(time(NULL));   // esto va en el main
    int * p = generaAleatorio();
    free(p);
    return 0;
}

por otro lado, la forma en que se generan los aleatorios puede llegar a tardar mucho, por ejemplo con X igual a 7 u 8, ya que cuando falten pocos dígitos por elegir la probabilidad de que ya hayan salido es bastante alta, y el ciclo que ejecuta randInt se puede llegar a repetir demasiadas veces.

**Comment by julianBogado1** [comment]
claro, a mi me parecio que la funcion deberia retornar el vector, pero creo que se pide como parametro.
Muchas gracias
