### ISSUE TITLE
TP7 EJ8

### ISSUE THREAD

**Issue by TomasBalboa** [marcelogarberoglio/PI#216]
Hola Marcelo, como estas ? estoy haciendo la funcion de ControlarLineas en el ejercicio del bingo y me surgio una duda. Yo la plantie de la siguiente manera: 

int controlarLineas(TipoLinea linea){
    int completa = 1; 
    for(int i = 0; i < LONG_LINEA && completa; i++){
        if(linea[i] != 0){
            completa = 0; 
        }
    }
    return completa; 
sin embargo en la resolucion de la catedra, utiliza la variable aciertos y lo hace de la siguiente manera: 
int controlarLineas(TipoLinea linea)
{
    int i;
    int aciertos;
    for (i = 0, aciertos = 0; i < LONG_LINEA; i++)
        aciertos += (linea[i] == 0);
    return (aciertos == LONG_LINEA);
}

Hay alguna razon en particular para resolverlo de esta forma ? o hay algo que no estoy teniendo en cuenta planteandolo como lo plantie ? 
Saludos

**Comment by marcelogarberoglio** [comment]
Está bien tu código, ya que completa queda en 1 sólo si todos están en cero.

**Comment by TomasBalboa** [comment]
Perfecto, muchas gracias !
