### ISSUE TITLE
Ej6 - TP8

### ISSUE THREAD

**Issue by TomasBalboa** [marcelogarberoglio/PI#233]
Hola Marcelo, como estas ? estuve haciendo el ej de las raices y hay algo en mi codigo que funciona mal, ya que cuando corro el programa es como que se me duplica la cantidad de raices encontradas (por ej si en el intervalo (-15 - 40) hay 17 raices, el programa me halla 34, siendo las duplicadas siempre con el "componente x" en 0, me fije y comentando uno de los incrementos de la dimension del vector, me da bien (osea 17 enves de 34), sin embargo no entiendo porque, ni donde esta el error. Probablemente por como soles decir, veo la idea mas q otra cosa. 

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include "random.h"
#include <math.h>
#include <stdlib.h>
#include "getnum.h"

#define PASOS 100000
#define EPSILON 00000.1
#define FUNCION(x) sin(x)
#define BLOQUE 10 

typedef struct intervalo{
    double a; 
    double b; 
}intervalo; 

typedef intervalo particiones; 

typedef struct roots{
    int cant; //Dimension --> Cantidad real de conjuntos almacenados. 
    particiones * lista; //Esta es la estructura para el almacenamiento de la respuesta es un puntero q apunta a la estructura q contiene cada particion (aqui iran todas las particiones halladas). 
}roots; 

void leerExtremos(intervalo *extremos); 
roots buscarRaices(intervalo *extremos); 

int main(void){

    intervalo extremos; 

    leerExtremos(&extremos); 

    roots respuesta;
    respuesta = buscarRaices(&extremos); 
if(respuesta.cant == -1){
    printf("Error en el almacenamiento de las raices");
}
else if(respuesta.cant> 0){
    for(int i = 0; i < respuesta.cant; i++){
        printf("Raices son %d en: [%f, %f]\n", i+1, respuesta.lista[i].a, respuesta.lista[i].b); 
    }
}
else
    printf("\n No hay raices en el intervalo "); 

free(respuesta.lista); 

    return 0;
}

void leerExtremos(intervalo *extremos){

    double a = getdouble("Ingrese Extremo 1: "); 
    double b = getdouble("Ingrese Extremo 2: "); 

    if( b > a ){
        extremos-> a = a; 
        extremos-> b = b;
    }
    else{
        extremos-> a = b;
        extremos-> b = a; 
    }

}

roots buscarRaices(intervalo *extremos){

    roots rsta; //La estructura de rsta. 
    rsta.lista = NULL; //Inicializo lista en NULL
    rsta.cant = 0; //La dimension del arreglo.

    signed char signoAnterior;
    signed char signo; 

    char esRaiz = 0; 
    char TerminaRaiz= 0; 

    double incremento = (extremos->b - extremos->a)/ PASOS; //Determino de a cuanto va a ir "saltando" (sumo 1 para tener en cuenta los extremos)
    double imagen = FUNCION(extremos->a); 
    signoAnterior = (imagen>0 ? 1 : (imagen == 0 ? 0 : -1)); //Guardo en signo anterior el primero posible para lograr entrar a la iteracion

    for(double i = extremos->a ; i <= extremos->b ; i+=incremento)
    {
    
    imagen = FUNCION(i); 
    signo = (imagen>0 ? 1 : (imagen == 0 ? 0 : -1)); //Guardo en signo el signo de la funcion. 

//SI SON DE DISTINTO SIGNO
        if(rsta.cant % BLOQUE == 0){
            rsta.lista = realloc(rsta.lista, (BLOQUE + rsta.cant) * sizeof(particiones)); //Aumento el espacio del vector. 
            }
        if(signo != signoAnterior)
        {
            rsta.lista[rsta.cant].a = i - incremento; //Asigno la cota inferior de la particion
            rsta.lista[rsta.cant].b = i; //Asigno la cota superior de la particion 

            (rsta.cant)++; //Incremento la dimension, primero accede y dsp incrementa (el () tiene mas precedencia que todo)
        }

//SI ES QUE ES 0 

        if(fabs(imagen) < EPSILON && !esRaiz && !TerminaRaiz)//Si pasa esto significa que esta por arrancar la raiz. 
        { 
            rsta.lista[rsta.cant].a = i - incremento; //Yo se que la cota inferior es el (incremento) anterior al que entro. 
            esRaiz = 1; 
            TerminaRaiz = 1; 
        }
        else if(fabs(imagen) > EPSILON && esRaiz && TerminaRaiz)
        {
            rsta.lista[rsta.cant].b = i; 
             esRaiz = 0; 
            TerminaRaiz = 0; 
            //(rsta.cant)++;  //PORQUE SE DUPLICA ? 
        } //ACA TERMINA LA RAIZ 

    signoAnterior = signo; 
    }

    rsta.lista = realloc(rsta.lista, rsta.cant * sizeof(particiones)); 

     return rsta; 
    }

**Comment by marcelogarberoglio** [comment]
Por un lado el EPSILON es un poco grande, no sé si en vez de 00000.1 quisiste poner 0.00001
Lo que estás haciendo es primero ver si cambia de signo y en ese caso guardás la raíz
Y después te fijás si es cero entonces guardás la raíz.
Podría darse el caso en que el valor anterior fue -0.01 y el actual es 0.0001, entonces la contás dos veces.

Lo más simple es usar un OR (¿cambió de signo o es cero?) y entonces guardás la raíz.

**Comment by TomasBalboa** [comment]
aaa jajajaj era literalmente lo del epsilon, muchas gracias !

**Comment by TomasBalboa** [comment]
y con el caso q planteas, perfecto ahora lo voy a corregir tambien
