### ISSUE TITLE
Ej 11 TP9

### ISSUE THREAD

**Issue by TomasBalboa** [marcelogarberoglio/PI#237]
Hola Marcelo, como estas ? En el ej 11 del TP9 hay una duda conceptual que no estoy entendiendo y es cuando se plantea el caso del segundo if en relación a la fila que dice: 

if(fil - n < dim);

Lo que no entiendo es porque en este caso queremos ver que sea menor a dim y no en cambio que fil - n >= 0. Ya que sino no entiendo de que manera validas que la matriz no se te este "escapando" hacia arriba digamos. 

Saludos

**Comment by marcelogarberoglio** [comment]
Porque está mal planteado. Tenés que moverte de a un paso en una dirección, sin irte de la matriz, sin importar cuántos pasos te moviste o te falta mover.
