### ISSUE TITLE
Autoevaluación 6 - Pregunta 4

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#24]
Buenas, una duda y una corrección de la autoevaluación. La función de la pregunta 4 era esta:
```C
#include <stdio.h>
 
// Le pide al usuario un valor entero mayor a cero
unsigned int readValidAge(void) }
   int age, count;
   printf("Ingrese su edad:");
   do {
      count = scanf("%d", &age);
   } while ( count !=1 && age <= 0); // Acá debería ser || en vez de &&
   return age;
} 
```
Y el comentario que hicieron fue:
`Si el usuario la primera vez ingresa un número entero mayor a cero, sale del ciclo y lo retorna. Pero si ingresa un negativo, en el buffer queda el \n, que será tomado por el siguiente scanf, entrando en un ciclo infinito. Lo mismo sucede si ingresa algún carácter inválido.`

Pero por cómo está el condicional del while, el loop terminaría si `age` es positivo pero si es negativo también porque `count == 1` aunque `age` sea negativo. Además dependiendo el valor inicial de `age` (que sería un valor basura), si se ingresa algo que no sea un número el programa podría quedar en un loop infinito (si `age <= 0`) o no (si `age > 0`).

Mi duda viene en caso de que se reemplace el condicional por `(count !=1 || age <= 0)` que creo es a lo que apuntaba el ejercicio. Ahí entiendo que quede en un loop infinito si se ingresa algo que no sea un número. 
Pero en el caso de que sea negativo no pasa lo que mencionan en el comentario. Es verdad que queda el `'\n'` en el buffer, pero lo probé y parece que el scanf lo ignora en la siguiente iteración e igual le pide al usuario que ingrese nuevamente caracteres. Por lo que probé, scanf ignora cualquier whitespace al comienzo de la entrada estándar.
Es correcto eso o hay algo que estoy entendiendo mal?

Gracias!

**Comment by marcelogarberoglio** [comment]
Sí, tus observaciones son acertadas, el comentario no se condice con el código propuesto. Recién cambiamos el código para que use || en vez de &&, para que sea coherente con el comentario.
