### ISSUE TITLE
ej 20, 21 tp7

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#25]
buenas tardes, tengo un problema con el programa, el sanitizer me dice q estoy teniendo un overflow y no entiendo por que, ya que en teoria no estoy accediendo a nada que no haya reservado previamente. 
el error del sanitizer es el siguiente:
![image](https://user-images.githubusercontent.com/113400047/194440561-b7bc410d-56fe-4d1c-8f9b-784e8f33380c.png)

![image](https://user-images.githubusercontent.com/113400047/194440590-d1214165-578e-4042-8a61-15b5ccc252e1.png)

```C

#define BLOCK 15
#define NOTA_MINIMA 4

typedef char * TAlumnos[];


char ** aprobados(TAlumnos nombres, size_t promedio[]){
    int i;
    char ** rta=NULL;

    //los i van a representar el espacio del puntero big
    //luego para cada alumno se debe hacer otro malloc

    for(i=0; nombres[i][0]!='\0'; i++){
        if(i%BLOCK==0)
            rta = realloc(rta, i+BLOCK);    //agrando vector de punteros

        if(promedio[i]>=NOTA_MINIMA){
            rta[i] = malloc(strlen(nombres[i])+1);   //reservo espacio (palabra) y guardo el nombre del alumno aprobado
            rta[i]=nombres[i];
        }
    }
    if(i%BLOCK==0)
        rta = realloc(rta, i+BLOCK); //agrego espacio

    rta[i] = malloc(1);   //reservo espacio para el '\0'
    rta[i]="";         //dejo la marca de final

    rta = realloc(rta, i++);
    return rta;
}

void liberaEspacio(char ** p){
    int cant=0;
    for(int i=0; p[i][0]!='\0'; i++){
        free(p[i]);
    }
    free(p);
}

int main(void){

    TAlumnos alumnos = {"Juan", "Pedro", "Martin", ""};
    int notas[] = {1, 4, 10, 2, 10, 11};

    char ** apr = aprobados(alumnos, notas);
    if(apr == NULL){
        printf("No hay suficiente memoria!\n");
        return 1;
    }
    assert(!strcmp(alumnos[1], apr[0]) && !strcmp(alumnos[2], apr[1]) && !strcmp(alumnos[3], apr[2]));

    puts("OK!");
    // En este programa no liberamos la memoria que utilizamos. Que ocurre si compilamos con "-fsanitize=address"?

    /*
     * test del free
     *
      TAlumnos alumnos = {"Juan", "Pedro", "Martin", ""};
    int notas[] = {1, 4, 10, 2, 10, 11};

    char ** apr = aprobados(alumnos, notas);
    if(apr == NULL){
        puts("No hay suficiente memoria!");
        return 1;
    }
    assert(!strcmp(alumnos[1], apr[0]) && !strcmp(alumnos[2], apr[1]) && !strcmp(alumnos[3], apr[2]));

    liberaAprobados(apr);

    puts("OK");
     */

    return 0;
}

```

**Comment by marcelogarberoglio** [comment]
El error es porque estás reservando menos bytes de los necesarios, en vez de 
   rta = realloc(rta, i+BLOCK); 
tendría que ser
      rta = realloc(rta, (i+BLOCK) * sizeof(char*);  
o.   
    rta = realloc(rta, (i+BLOCK) * sizeof(*rta);

**Comment by marcelogarberoglio** [comment]
Después habría que corregir estas líneas

     if(i%BLOCK==0).    //.  Ya sabés que vas a necesitar i+1 elementos, ¿por qué agregar un bloque si después 
                                      // vas a liberar lo que te sobra de ese bloque ?
        rta = realloc(rta, i+BLOCK); 

y las que siguen

    rta[i] = malloc(1);   //reservo espacio para el '\0'
    rta[i]="";         //dejo la marca de final
    rta = realloc(rta, i++);

en la segunda asignación pisás la dirección que te devolvió malloc (que si quisieras guardar un puntero no te alcanza con un. byte). Por lo que ese byte reservado nunca se va a poder liberar
Y si tenés un elemento en la posición i, el realloc tendría que ser para i+1 elementos

**Comment by julianBogado1** [comment]
cambie los tipos de datos para el realloc, pero igualmente me sigue tirando error el sanitizer.


```C

#define BLOCK 15
#define NOTA_MINIMA 4

typedef char * TAlumnos[];


char ** aprobados(TAlumnos nombres, size_t promedio[]){
    int i;
    char ** rta=NULL;

    //los i van a representar el espacio del puntero big
    //luego para cada alumno se debe hacer otro malloc

    for(i=0; nombres[i][0]!='\0'; i++){
        if(i%BLOCK==0)
            rta = realloc(rta, (i+BLOCK)*sizeof(*rta));    //agrando vector de punteros

        if(promedio[i]>=NOTA_MINIMA){
            rta[i] = malloc(strlen(nombres[i])+1);   //reservo espacio (palabra) y guardo el nombre del alumno aprobado
            rta[i]=nombres[i];
        }
    }
    if(i%BLOCK==0)
        rta = realloc(rta, i+BLOCK); //agrego espacio

    rta[i] = malloc(sizeof(*rta));   //reservo espacio para el '\0'
    rta[i++]="";         //dejo la marca de final

    rta = realloc(rta, i);
    return rta;
}

void liberaEspacio(char ** p){
    int cant=0;
    for(int i=0; p[i][0]!='\0'; i++){
        free(p[i]);
    }
    free(p);
}

int main(void){

    TAlumnos alumnos = {"Juan", "Pedro", "Martin", ""};
    int notas[] = {1, 4, 10, 2, 10, 11};

    char ** apr = aprobados(alumnos, notas);
    if(apr == NULL){
        printf("No hay suficiente memoria!\n");
        return 1;
    }
    assert(!strcmp(alumnos[1], apr[0]) && !strcmp(alumnos[2], apr[1]) && !strcmp(alumnos[3], apr[2]));

    puts("OK!");
    // En este programa no liberamos la memoria que utilizamos. Que ocurre si compilamos con "-fsanitize=address"?

    /*
     * test del free
     *
      TAlumnos alumnos = {"Juan", "Pedro", "Martin", ""};
    int notas[] = {1, 4, 10, 2, 10, 11};

    char ** apr = aprobados(alumnos, notas);
    if(apr == NULL){
        puts("No hay suficiente memoria!");
        return 1;
    }
    assert(!strcmp(alumnos[1], apr[0]) && !strcmp(alumnos[2], apr[1]) && !strcmp(alumnos[3], apr[2]));

    liberaAprobados(apr);

    puts("OK");
     */
    liberaEspacio(apr);
    return 0;
}

```

**Comment by marcelogarberoglio** [comment]
¿Cuál es el mensaje que te tira el sanitizer? Acordate de compilarlo con la opción -g.

¿Este realloc lo viste?
    
    rta = realloc(rta, i);

**Comment by julianBogado1** [comment]
el ultimo realloc deberia liberar la memoria q se reservo y no se uso, esta mal puesto ahi?

el error del sanitizer es el siguiente:
![image](https://user-images.githubusercontent.com/113400047/196006869-8c1ad14d-5b0d-4ba8-b405-3a1385b99f2d.png)
![image](https://user-images.githubusercontent.com/113400047/196006889-6dd3acc8-a622-4fe4-9ab8-2a6edf8a38c0.png)
![image](https://user-images.githubusercontent.com/113400047/196006893-6883b2e6-7400-4007-a359-52d7616f41fe.png)

**Comment by marcelogarberoglio** [comment]
No es el lugar lo que está mal. Pero le estás diciendo que querés que quede con i bytes. O sea, corregiste el otro realloc para multiplicar por el sizeof pero este no.
