### ISSUE TITLE
Guía 7, Ej 10: Ahorcado

### ISSUE THREAD

**Issue by berni-245** [marcelogarberoglio/PI#26]
Buenas! Me gustaría saber si mi resolución en este ejercicio está bien. También me gustaría consultar si hay alguna forma de calcular  la cantidad de palabras que tengo en la matriz candidatos para saber si puedo evitar el uso de un define para esa cantidad. 
Muchas gracias de antemano!

PD: No tengo mi nombre completo de usuario pero soy Bernardo Zapico (Por las dudas aviso, no sé si hace falta)

```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "../random.h"
#define LONG_LETRAS 10
#define CANT_PALABRAS 9
#define INTENTOS_INI 6

void selecPalabra(char candidatos[][LONG_LETRAS+1], char palabra[]);
char ingresarLetra();
int controlarLetra(char palabra[], char letra, short marcas[]);
void imprimirPalabra(char palabra[], short marcas[]);
int palabraCompleta(char palabra[], short marcas[]);

int
main(){
    char candidatos[][LONG_LETRAS+1] = {"test","despreciar","explotador","futbolista","interrogar","justiciero","relevancia","septiembre","voluntario"};
    char palabra[LONG_LETRAS+1];
    short marcas[LONG_LETRAS] = {0};
    int i, gano, intentos = INTENTOS_INI;
    char letra;

    randomize();
    selecPalabra(candidatos, palabra);

    do{
        imprimirPalabra(palabra, marcas);

        printf("Le quedan %d intentos restantes\n",intentos);
        letra = ingresarLetra();
        intentos -= (controlarLetra(palabra, letra, marcas) != 1);

        gano = palabraCompleta(palabra, marcas);
    
    }while(intentos != 0 && !gano);

    if(gano){
            printf("Felicidades, acertaste! La palabra era:\n");
            imprimirPalabra(palabra, marcas);
    }
    else{
        for(i=0; palabra[i] != '\0'; i++){
            marcas[i] = 1;
        }

        printf("Lo siento! La palabra era:\n");
        imprimirPalabra(palabra, marcas);
    }
        

    return 0;
}

void
selecPalabra(char candidatos[][LONG_LETRAS+1], char palabra[]){;
    int i = randInt(0, CANT_PALABRAS-1);
    int j;

    for(j=0; candidatos[i][j]; j++){
        palabra[j] = candidatos[i][j];
    }
    palabra[j] = '\0';

}

char
ingresarLetra(){
    char letra;

    printf("Ingrese una letra: ");
    while(!isalpha(letra = getchar()));

    return tolower(letra);
}

int 
controlarLetra(char palabra[], char letra, short marcas[]){
    int i, found=0;

    for(i=0; palabra[i] != '\0'; i++){
        if(palabra[i] == letra){
            marcas[i] = 1;
            found = 1;
        }
    }

    return found;
}
void 
imprimirPalabra(char palabra[], short marcas[]){
    int i;

    for(i=0; palabra[i]; i++){
        if(marcas[i])
            putchar(palabra[i]);
        else
            putchar('_');
        putchar(' ');
    }
    putchar('\n');
    putchar('\n');
}

int 
palabraCompleta(char palabra[], short marcas[]){
    int i, gano = 1;

    for(i=0; palabra[i] && gano; i++){
        if(marcas[i] != 1){
            gano = 0;
        }
    }

    return gano;
    
}

```
PD2: Cómo hago para que el código se suba con color? Me dice que no se pueden subir archivos del formato .c en este lugar

**Comment by marcelogarberoglio** [comment]
Para la cantidad de palabras, para no tener que cambiar la constante cada vez que agregás a mano palabras en el vector, podrías tener una variable y pasarla a las funciones, o sea

```C
char candidatos[][LONG_LETRAS+1] = {"test","despreciar","explotador","futbolista","interrogar","justiciero","relevancia","septiembre","voluntario"};

int cant = sizeof(candidatos) / sizeof(candidatos[0]);

int cual = selecPalabra(candidatos, palabra, cant);
```



En el código cambiaría la forma en que se imprime la palabra original cuando pierde. Tal vez sería mejor que selectPalabra te devuelva el índice de la palabra elegida, y lo usás para imprimir la palabra original, ya sea que haya perdido o ganado.  Ya que en ambos casos la imprimís, entonces lo hacés afuera del if, o sea


```C
 if(gano){
            printf("Felicidades, acertaste! La palabra era:\n");
    }
    else{
        for(i=0; palabra[i] != '\0'; i++){
            marcas[i] = 1;
        }

        printf("Lo siento! La palabra era:\n");
    }
   printf("%s\n", candidatos[cual]);
```

En selectPalabra podrías usar strcpy


Para que el código se vea con formato tenés que anteponer ```C  antes y después del c;ódigo, como explican en https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by berni-245** [comment]
Ahhh, yo había probado lo del sizeof pero lo había hecho dentro de la función selecPalabra, pero me dio 0 y me había tirado este warning:
```C
E10.c: In function ‘selecPalabra’:
E10.c:61:22: warning: ‘sizeof’ on array function parameter ‘candidatos’ will return size of ‘char (*)[11]’ [-Wsizeof-array-argument]
   61 |     int cant = sizeof(candidatos)/sizeof(candidatos[0]);
      |                      ^
E10.c:58:19: note: declared here
   58 | selecPalabra(char candidatos[][LONG_LETRAS+1], char palabra[]){;
      |              ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Y no había entendido muy bien que pasaba. Asumo que dentro de la función se tomaba cómo puntero el parámetro 'candidatos' y que al hacer la división del puntero por el tamaño del primer elemento del array (4 o 8 / LONG_LETRAS+1) se trunca a 0?

Respecto a cómo se imprime la palabra original, podría también quitar el for que recorre el vector marcas en el else, no? Y que tanto el if como el else sean sólo para imprimirle al usuario el resultado, seguido por printear la palabra fuera de los condicionales.

PD: Gracias por el truco para que el código se vea con formato! Ahí actualicé el código original

**Comment by marcelogarberoglio** [comment]
> 
> Y no había entendido muy bien que pasaba. Asumo que dentro de la función se tomaba cómo puntero el parámetro 'candidatos' y que al hacer la división del puntero por el tamaño del primer elemento del array (4 o 8 / LONG_LETRAS+1) se trunca a 0?

Sí, es por eso. Como se explicó cuando vimos pasaje de vectores a funciones. La función recibe la dirección del primer elemento y la almacena en una variable, por el sizeof del "vector" dentro de la función te da la cantidad. de bytes que ocupa un puntero.

> 
> Respecto a cómo se imprime la palabra original, podría también quitar el for que recorre el vector marcas en el else, no? Y que tanto el if como el else sean sólo para imprimirle al usuario el resultado, seguido por printear la palabra fuera de los condicionales.
> 
Sí, eso es lo que proponía, no usar la función que imprime sino simplemente imprimir si ganó o no. Y al final la palabra directamente.

**Comment by berni-245** [comment]
Perfecto, muchas gracias Marcelo!
