### ISSUE TITLE
EJ 14 - TP11

### ISSUE THREAD

**Issue by TomasBalboa** [marcelogarberoglio/PI#269]
Hola marcelo, como va ? estaba haciendo el ejercicio 14 y me surgio una duda al momento de modularizar para la lista de orden de insercion ya que cuando hago lo que seria agregar el elemento a la lista en la funcion add directamente (como hace la rsta) me corre bien. Pero cuando lo modularize de la siguiente manera, me falla en el next(de insercion) a que se debe ? 

![image](https://github.com/marcelogarberoglio/PI/assets/133538474/04f7b466-ef28-421b-b5dc-929801b562f3)

![image](https://github.com/marcelogarberoglio/PI/assets/133538474/56221a70-b6d4-414b-8789-243adb45a78e)

**Comment by marcelogarberoglio** [comment]
addInser recibe una copia del puntero al primero, entonces la primera vez es NULL, al hacer
  listFirst  = aux
estás modificando la copia local

**Comment by TomasBalboa** [comment]
Aaa perfecto, me imagine que podia ser por el tema de la copia, pero no entendia porq si funcionaba en el addrec, pero ahi me di cuenta q en addinser modifico la copia, no creo una lista como en addrec. Listo impecable, gracias !

**Comment by TomasBalboa** [comment]
Aa perfecto muchas gracias, claro solo modifica la copia local de listFirst pero no cambia el de "afuera"
