### ISSUE TITLE
ej17 Guia7

### ISSUE THREAD

**Issue by romamati** [marcelogarberoglio/PI#27]
Buenas! Cuando ejecuto mi código me tira error y me gustaría saber que es lo que esta mal. 
Desde ya muchas gracias.

/* 
Escribir una version de strcat usando punteros. Osea que tengo que hacer una funcion strcat(s,t) que copie al 
string t al final del string s
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Funcion que retorna la suma de los caracteres de dos string */
int suma_caracteres(char t[],const char s[])
{
    int suma_t = 0, suma_s = 0, suma_total = 0;
    suma_t = strlen(t);
    suma_s = strlen(s);
    suma_total = suma_t + suma_s;
    
    return suma_total;
}

char * strcat_punteros( char *pt, const char *ps)
{
    int i = 0, dimension = suma_caracteres(pt,ps), j = 0;
    char *aux = malloc((dimension+1) *sizeof(char));
    while(*pt)
    {
        *(aux + i) = *(pt +i);
        i++;
    }
    while(*(aux+i) = *(ps+j))
    {
        i++;
        j++;
    }

    *(aux + dimension +1) = 0;

    return aux;

}

/* Funcion que imprime en pantalla un string*/
void imprimir(char t[])
{
    printf("\n");
    for(int i = 0; t[i] != 0; i++)
    {
        printf("%c",t[i]);
    }
    printf("\n");
}

int main(void)
{
    char t[] = {"el auto es "};
    char s[] = {"rojo"};
    char *pt = t; 
    char *ps = s;

    pt = strcat_punteros(pt, ps);
    imprimir(pt);
    free(pt); /* libero pt pues tendria la direccion del aux que retorna mi funcion strcat_punteros*/

    return 0;
}

**Comment by marcelogarberoglio** [comment]
¿Por dónde empezar?
1) Sería útil que envíes cuál es el error, para facilitar mi respuesta
2) Si es la versión de strcat, no habría que crear un nuevo string, sino copiar el segundo al final del primero, algo que te va a dar error porque en t no tenés "lugar de sobra", tendrías que haberlo definido por ejemplo así
   char t[50] = {"el auto es "};
3) Los punteros pt y ps en main no son necesarios, podrías pasar t y s a la función
4) Si vas a copiar primero un string seguido de otro, no es eficiente averiguar la longitud y luego copiar, ya que hacés dos recorridos, eso sería válido sólo en el caso de que te aseguren que los strings son cortos.
5) Cuando hacés
      *(aux + i) = (pt +i);
  deberías hacer
   *(aux + i) = *(pt +i);
6) tendría que ser
   *(aux + dimension) = 0;
7) Te aconsejo que hagas la función con índices y no punteros, y trates de hacer las guías que siguen. Salvo que estés al día con las guías y hayas querido practicar punteros.
8) ¿Esto  compila?
     while((aux+i) = *(ps+j))

**Comment by romamati** [comment]
Ahi lo rehice y funciona: 

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/* Funcion que retorna la suma de los caracteres de dos string */
int suma_caracteres(char t[],const char s[])
{
    int suma_t = 0, suma_s = 0, suma_total = 0;
    suma_t = strlen(t);
    suma_s = strlen(s);
    suma_total = suma_t + suma_s;
    
    return suma_total;
}

char * strcat_punteros( char *pt, const char *ps)
{
    int i = 0, j = 0;
    long int dimension = suma_caracteres(pt,ps);
    char *aux = malloc((dimension+1) *sizeof(char));
    while(pt[i] != 0)
    {
        aux[i] = pt[i];
        i++;
    }
    while(aux[i] = ps[j])
    {
        i++;
        j++;
    }

    aux[i] = 0;

    return aux;

}

void imprimir(char t[])
{
    printf("\n");
    for(int i = 0; t[i] != 0; i++)
    {
        printf("%c",t[i]);
    }
    printf("\n");
}


int main(void)
{
    char *t = {"el auto es "};
    char *s = {"rojo"};

    t = strcat_punteros(t, s);
    imprimir(t);
    free(t); /* libero pt pues tendria la direccion del aux que retorna mi funcion strcat_punteros*/

    return 0;
}

**Comment by marcelogarberoglio** [comment]
Tendría que ser

char *t = "el auto es ";
char *s = "rojo";

Si bien decís que funciona, las observaciones de los puntos 2 y 4 siguen valiendo para esta nueva versión.
