### ISSUE TITLE
Guía 8, Ej 1.b: Corregir el siguiente fragmento de código

### ISSUE THREAD

**Issue by berni-245** [marcelogarberoglio/PI#28]
Buenas! Estaba haciendo el ejercicio 1 de la guía 8 y no pude hallar cuál era el error en el siguiente código:
```C 
struct art {
   int code;
   double price;
}

struct art * newArt(int code, double price) {
   struct art * p = calloc(1, sizeof(struct art));
   p->code = code;
   p->price = price;
   return p;
}
```
No creo que sea el punto y coma que faltaba en la struct, por lo que me gustaría preguntar cuál es error importante del código para sacarme la duda.
Muchas gracias de antemano!

**Comment by marcelogarberoglio** [comment]
Errores de funcionamiento no vas a encontrar. Lo que no está bien es haber usado calloc cuando inmediatamente después se completan todos los valores del struct. Se tendría que haber usado malloc.

**Comment by berni-245** [comment]
Ahhh, claro. Estaba tan mentalizado en buscar algún error de sintaxis que no pensé que fuera relevante el uso de calloc en este caso jaja
Muchas gracias Marcelo!
