### ISSUE TITLE
TP6 ejercicio 20

### ISSUE THREAD

**Issue by DeZ7ro** [marcelogarberoglio/PI#285]
Si bien pasa el testeo, tengo una duda de si esta bien escrita la funcion checkSubMat:
int checkSubMat(char m[][DIM], int fil, int col){
    char flags[DIMAUX] = {0};
    // no voy a usar flags[0], como tengo numeros del 1 al 9 cada uno accede a su flag
    int i,j;
    for(i = 0;fil+i < DIM && i < 3;i++){
        for(j = 0; col+j < DIM && j < 3; j++){
            if(m[fil+i][col+j] < 1 || m[fil+i][col+j] > 9)  //chequeo fueras de rango, tener en cuenta en el orden de llamada de funcion
                return 0;
            if(flags[(int)m[i][j]] == 1) // accedo al flag del numero en cuestion, chequeo repetidos y si falto alguno no lo chequeo ya que si o si debe ser repetido
                return 0;
            flags[(int)m[i][j]] = 1;    // el casteo esta bien? xq funciona? no deberia ser fil+i y col+j?
        }
    }
    return 1;
}

**Comment by marcelogarberoglio** [comment]
Sí, está bien.,
