### ISSUE TITLE
Guía 7 - Ej 8/9 Bingo

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#29]
Buenas, quería pedir la corrección de mi programa de bingo. El tema es que no seguí al pie de la letra el enunciado. 
Hice la mayoría de las funciones que pedía (y algunas extra), pero con parámetros un poco distintos porque usé structs en vez de los typedef del enunciado.
Además, en vez de eliminar lo valores que van saliendo de los cartones decidí dejarlos y tener otro vector que me marca si cada número salió o no. Eso me permite imprimir los cartones de forma bonita.

En principio el programa funciona bien, me interesaría más que nada el tema de estilo y eficiencia.

```C
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define LINE_LEN 5
#define N_LINES 3
#define B_MIN 0
#define B_MAX 90
#define BALL_COUNT (B_MAX - B_MIN + 1)

typedef struct Card {
  int numbers[N_LINES][LINE_LEN];
  char matchedNumbers[N_LINES][LINE_LEN];
} Card;

typedef struct Baller {
  int baller[BALL_COUNT];
  int remainingBalls;
} Baller;

int randInt(int min, int max);
int getNumberOfPlayers();

int playBingo();
int playRound(int numberOfPlayers, Card cards[], Baller* b);
void congratulatePlayers(int count, char winners[], char type);
Card generateCard();

int getBingoBall(Baller* b);
int controlCard(Card* card, int ballNumber);
void printCard(const Card* card);

int cardMarkMatch(Card* card, int ballNumber);
int controlLine(char matchedNumbersLine[]);

int main() {
  srand(time(NULL));

  playBingo();

  return 0;
}

int playBingo() {
  int numberOfPlayers = getNumberOfPlayers();
  Card cards[numberOfPlayers];
  for (int i = 0; i < numberOfPlayers; i++) {
    cards[i] = generateCard();
    printf("Player %i: \n", i + 1);
    printCard(&cards[i]);
    printf("\n");
  }
  printf("Press <Enter> to start game: ");
  getchar();

  Baller b = {{0}, BALL_COUNT};
  int bingoCount = 0;
  while (!bingoCount) {
    bingoCount = playRound(numberOfPlayers, cards, &b);
  }

  return bingoCount;
}

int playRound(int numberOfPlayers, Card cards[], Baller* b) {
  int bingoCount = 0, lines = 0;
  static int firstLine = 0;
  int firstLineCount = 0;
  static char* firstLiners = NULL;
  static char* bingoWinners = NULL;
  int ball = getBingoBall(b);

  printf("----------------------\n");
  printf("| Ball Number: %02d!!! |\n", ball);
  printf("----------------------\n\n");

  for (int i = 0; i < numberOfPlayers; i++, lines = 0) {
    lines = controlCard(&cards[i], ball);
    printf("Player %i: \n", i + 1);
    printCard(&cards[i]);
    printf("\n");
    if (lines != 0) {
      if (firstLine == 0) {
        ++firstLineCount; 
        firstLiners = realloc(firstLiners, firstLineCount);
        firstLiners[firstLineCount - 1] = i + 1;
      }
      if (lines == N_LINES) {
        ++bingoCount;
        bingoWinners = realloc(bingoWinners, bingoCount);
        bingoWinners[bingoCount - 1] = i + 1;
      }
    }
  }

  if (firstLineCount) {
    firstLine = 1;
    congratulatePlayers(firstLineCount, firstLiners, 'L');
    free(firstLiners);
  }
  if (bingoCount) {
    congratulatePlayers(bingoCount, bingoWinners, 'B');
    free(bingoWinners);
  }

  printf("Press <Enter> for next round or <C-d> to play full game: ");
  getchar();

  return bingoCount;
}

void congratulatePlayers(int count, char winners[], char type) {
  char* msg;
  char* borderSup;
  char* borderInf;
  switch (type) {
    case 'B':
      borderSup = "\n\\ | | | | | | | | | | | | | | | | | | | | | | | | | | | /\n";
      msg =       "- Congratulations to Player %02i on getting a BINGO!!!!! -";
      borderInf = "\n/ | | | | | | | | | | | | | | | | | | | | | | | | | | | \\\n\n";
      break;
    case 'L':
      borderSup = "\n\\ | | | | | | | | | | | | | | | | | | | | | /\n";
      msg =       "- Player %02i has completed the first line!!! -";
      borderInf = "\n/ | | | | | | | | | | | | | | | | | | | | | \\\n\n";
      break;
  }
  for (int i = 0; i < count; i++) {
    printf("%s", borderSup);
    printf(msg, winners[i]);
    printf("%s", borderInf);
  }
}

Card generateCard() {
  Card card;
  int usedValues[BALL_COUNT] = {0};
  for (int i = 0; i < N_LINES; i++) {
    for (int j = 0; j < LINE_LEN; j++) {
      int val = 0;
      do {
        val = randInt(B_MIN, B_MAX);
        if (usedValues[val - B_MIN] == 0) {
          card.numbers[i][j] = val;
        }
      } while (usedValues[val - B_MIN]++ != 0);
      card.matchedNumbers[i][j] = 0;
    }
  }

  return card;
}

int getBingoBall(Baller* b) {
  int ballNumber, repeatedNumber = 1;
  
  while (repeatedNumber && b->remainingBalls > 0) {
    ballNumber = randInt(B_MIN, B_MAX);
    repeatedNumber = (b->baller[ballNumber - B_MIN] != 0);
    if (!repeatedNumber) {
      b->baller[ballNumber - B_MIN] = 1;
      b->remainingBalls--;
    }
  }

  return ballNumber;
}

int controlCard(Card* card, int ballNumber) {
  int completeLines = 0;
  cardMarkMatch(card, ballNumber);
  for (int i = 0; i < N_LINES; i++) {
    completeLines += controlLine(card->matchedNumbers[i]);
  }

  return completeLines;
}

void printCard(const Card* card) {
  for (int i = 0; i < N_LINES; i++) {
    for (int j = 0; j < LINE_LEN; j++) {
      if (card->matchedNumbers[i][j] == 0) {
        printf("| %02d ", card->numbers[i][j]);
      } else {
        printf("|-%02d-", card->numbers[i][j]);
      }
    }
    printf("|\n");
  }
  // printArray(N_LINES*LINE_LEN, (void*)card->matchedNumbers, sizeof(char));
}

int cardMarkMatch(Card* card, int ballNumber) {
  int match = 0;
  for (int i = 0; i < N_LINES; i++) {
    for (int j = 0; !match && j < LINE_LEN; j++) {
      if (ballNumber == card->numbers[i][j]) {
        card->matchedNumbers[i][j] = 1;
        match = 1;
      }
    }
  }

  return match;
}

int controlLine(char matchedNumbersLine[]) {
  for (int i = 0; i < LINE_LEN; i++) {
    if (matchedNumbersLine[i] == 0) return 0;
  }
  return 1;
}

int getNumberOfPlayers() {
  int numberOfPlayers = 0;
  int correctArgs = 0;
  while (correctArgs != 1 || numberOfPlayers <= 0) {
    printf("Number of players: ");
    correctArgs = scanf("%d", &numberOfPlayers);
  while (getchar() != '\n');
  }
  printf("NoP = %i, cA = %i\n", numberOfPlayers, correctArgs);

  return numberOfPlayers;
}

int randInt(int min, int max) {
  return rand()%(max - min + 1) + min;
}
```
Por ejemplo el uso de los static en la función playRound() no me parece que esté mal pero no se si es lo mejor. Tampoco se si es buena idea separar la parte de playRound() de la función playBingo(), lo hice para modularizar pero no se si es necesario.

**Comment by marcelogarberoglio** [comment]
Está bien el uso de structs, nosotros no lo pedimos para este ejercicio porque aún no habíamos visto el tema.
Algunas observaciones

getNumberOfPlayers: deberías usar un "do while" en vez de un while. También podrías usar getint

Está bien tener el vector matchedNumbers con 0 ó 1 para saber si ya salió o no. Un truco que se puede hacer en estos casos también es poner en negativo el valor de numbers[i][j] si salió la bolilla de la fila i, columna j. De esa forma podés tener marcado que salió (es negativo) y también imprimir el valor original, con abs

La función generateCard está devolviendo un struct que tiene un cartón, lo cual hace que sea lento mover toda esa info, desde la variable card a la zona de la respuesta, y luego al elemento del vector. Se podría hacer que reciba el puntero al cartón y lo complete, o sea invocarla así:
     generateCard(cards + i );

getBingoBall no es eficiente. A medida que se sacan bolillas, la probabilidad de que salga repetida es muy grande, y se puede poner lento el juego, tendrías tener en cuenta la observación que agregamos en la guía para el juego de mastermind:
     
 _en esta función es bastante común que el algoritmo para generar X dígitos aleatorios sin repetir sea el siguiente:
   Crear un vector auxiliar de 9 chars en cero
     Para i desde 0 hasta X-1 hacer
     Elegir un dígito al azar entre 1 y 9
     Si ya estaba marcado en el vector auxiliar volver al punto 2.a
     Marcarlo en el vector auxiliar
     Guardar el dígito en la posición i del vector incognita_

Usaría un #define o enum en vez de las "magic letters" 'L' y 'B'

**Comment by fmorroni** [comment]
> getNumberOfPlayers: deberías usar un "do while" en vez de un while. También podrías usar getint

Esto decís para evitar tener que inicializar las variables?

> Está bien tener el vector matchedNumbers con 0 ó 1 para saber si ya salió o no. Un truco que se puede hacer en estos casos también es poner en negativo el valor de numbers[i][j] si salió la bolilla de la fila i, columna j. De esa forma podés tener marcado que salió (es negativo) y también imprimir el valor original, con abs

Esto es genial, ojalá se me hubiera ocurrido jajaja

> La función generateCard está devolviendo un struct que tiene un cartón, lo cual hace que sea lento mover toda esa info, desde la variable card a la zona de la respuesta, y luego al elemento del vector. Se podría hacer que reciba el puntero al cartón y lo complete, o sea invocarla así:
generateCard(cards + i );

Esto tenés razón, pero no se por qué para esa función lo hice así, para todo el resto siempre paso el puntero.

> getBingoBall no es eficiente. A medida que se sacan bolillas, la probabilidad de que salga repetida es muy grande, y se puede poner lento el juego, tendrías tener en cuenta la observación que agregamos en la guía para el juego de mastermind:

Esto la verdad no lo entiendo. Lo que me proponés no es lo mismo que yo hice? Y es lo mismo que apliqué en generateCard.
Igual entiendo que cuantos más números salgan más va a tardar en conseguir uno no repetido, en su momento se me había ocurrido otra forma para getBingoBall que era inicializar el bolillero con números de 1 al 90, y a medida que salía una bolilla eliminarla del vector ese, y después solo pedir un número random entre 0 y remainingBalls.
Pero al final decidí no aplicar eso porque eliminar una bolilla implicaba mover todos los elementos de la bolilla en adelante un lugar a la izquierda, y me pareció eran muchos recorridos innecesarios.
Ahora lo volví a pensar igual y estoy bastante seguro que es mucho mejor eso jajaja. Osea no solo es determinable cuánto va a tardar (como está hecho ahora podría potencialmente quedar en un loop infinito), pero además a medida que van saliendo bolillas menos tarda en removerla del array.

Esta sería la reimplementación:
```C
void initializeBaller(Baller* b) {
  b->remainingBalls = BALL_COUNT;
  for (int i = 0; i < BALL_COUNT; i++) {
    b->baller[i] = i + B_MIN;
  }

int getBingoBall(Baller* b) {
  int ballIndex, ballNumber;
  ballIndex = randInt(0, b->remainingBalls);
  ballNumber = b->baller[ballIndex];

  for (int i = ballIndex; i < b->remainingBalls - 1; i++) {
    b->baller[i] = b->baller[i+1];
  }
  --b->remainingBalls;

  return ballNumber;
}

// Llamado:
int playBingo() {
...
  Baller b;
  initializeBaller(&b);
...
}
int playRound(int numberOfPlayers, Card cards[], Baller* b) {
...
  int ball = getBingoBall(b);
...
}
```

> Usaría un #define o enum en vez de las "magic letters" 'L' y 'B'

Definitivamente, tampoco me gustaba mucho como lo implementé pero ni se me ocurrió usar un enum.

**Comment by marcelogarberoglio** [comment]
Por...
getNumberOfPlayers: deberías usar un "do while" en vez de un while. También podrías usar getint
Esto decís para evitar tener que inicializar las variables?
Respondo: es que si vas a hacer algo al menos una vez es más claro usar do-while, y además te ahorrás el tener que inicializar las variables con un valor especial para forzar a que entre al menos una vez al while.

Por lo de "getBingoBall no es eficiente. A m....."  copié el principio del texto que está escrito en el ejercicio de Mastermind. ( y sí, coincide con lo que vos hiciste). El texto sigue y explica por qué es ineficiente. Hay dos formas de hacerlo eficiente::
1) Generar el bolillero con los números 1 a 90, mezclarlo y luego ir tomando en orden
2) Generar el bolillero con los números 1 a 90. 
    La primera vez generar un aleatorio i entre 0 y 89. Tomar como bolilla bolillero[i], y hacer bolillero[i] = bolillero[89]
    La segunda vez generar un aleatorio i entre 0 y 88. Tomar como bolilla bolillero[i], y hacer bolillero[i] = bolillero[88]
    La tercer vez generar un aleatorio i entre 0 y 87. Tomar como bolilla bolillero[i], y hacer bolillero[i] = bolillero[87]
    etc.
De cualquiera de las dos formas, extraer una bolilla es O(1) sin importar cuántas salieron antes

**Comment by fmorroni** [comment]
Por lo del do while, okay.

Por lo de getBingoBall perdón, lo había buscado en el TP pero justo el texto que vos pusiste en el comentario estaba al final de una página y no me fijé que seguía la explicación en la siguiente página 🤦.
Y okay, sí, esas dos formas son mejores jajaja. La 2 es similar a la versión actualizada que pasé pero mejor xq solo hace un cambio en vez de mover todos los elementos un lugar a la izquierda.
Y la primera no es un poco peor? No en cuanto a sacar las bolillas pero en cuanto a generar el bolillero.
Para mezclar el array lo que se me ocurre sería hacer un loop de i = 0 a 89 y hacer:

swap(bolillero[i], bolillero[randInt(0, 89)]) 

Estaría bien eso o hay mejores formas?
