### ISSUE TITLE
Taller 4 Ejercicio 4 b

### ISSUE THREAD

**Issue by DeZ7ro** [marcelogarberoglio/PI#3]
Consigna:
Escribir un programa que reciba un arreglo de números enteros positivos y mezclesus elementos. La cantidad de elementos del arreglo se pasa mediante unsegundo parámetro entero.
¿Cómo cambiaría el programa si no se pasara el segundo parámetro y se indicarala finalización del arreglo mediante un elemento con el valor -1?
● Ejemplo 1:○ Vector A: 3,5,7,9,15, dim 5○ Vector A(mezclado): 3,7,15,9,5, dim 5
● Ejemplo 2:○ Vector A: 3,5,7,9,15,-1○ Vector A(mezclado): 3,7,15,9,5,-1

Mi solucion:
void mezclarreglov2(int vec[]){  //la diferencia es q aca tengo q cortar con -1
    int aux, i, dim;
    for(dim = 0; vec[dim] != -1; dim++); // como hago?, dim tiene q valer el ultimo o uno menos ya que tengo la marca de final?
    printf("%d\n", dim);
    int choose = randInt(0,dim-1); 
    for(i = 0; vec[i] != -1 ; choose = randInt(0,dim-1), i++){ 
        aux = vec[i];
        vec[i] = vec[choose];
        vec[choose] = aux;
    }

Hola, tenia una duda sobre como manejar vectores los cuales sabemos que tienen marca de final pero no sabemos su dimension. Para poder generar un numero aleatorio uso randint y tengo que dar el rango, pero al no saber el tamaño de mi vector no me queda otra que recorrerlo dos veces, una para saber su tamaño y otra para hacer los cambios en el vector. Esta bien este razonamiento?

**Comment by marcelogarberoglio** [comment]
Si realmente quiero cambiar cada elemento con cualquier otro del mismo (como si mezcláramos un mazo de cartas) entonces la respuesta es sí, hay que hacer dos recorridos: uno para contrar y otro para mezcl;ar.
Lo que sí cambiaría es no repetir código, en la llamada a randInt, o sea lo dejaría así

int choose;
for(i = 0; vec[i] != -1 ;  i++){
     choose = randInt(0,dim-1)
     aux = vec[i];
     vec[i] = vec[choose];
     vec[choose] = aux;
}


La otra opción es no hacer una simulación "real" de intercambiar cada elemento con cualquier otro, sino solamente con los anteriores, y entonces sí se resuelve con un único recorrido, o sea cuando i es 0, no hay intercambio, cuando es 1 puede ser con 0 ó 1, cuando es 2 con 0,1 ó 2, etc.

**Comment by DeZ7ro** [comment]
Perdon que escribo tan tarde pero que tan mal esta hacer esto en un examen, deberia hacerlo como vos decis o aunque mi manera sea mas ineficiente se considera satisfactoria?

**Comment by marcelogarberoglio** [comment]
Si fuera en un examen seguramente el enunciado sería tal que sea más evidente que no se lo debe recorrer dos veces. Por ejemplo en el caso de mezclar un vector no usaríamos una marca de final sino que la función reciba la dimensión,
Como regla general a tener en cuenta, si pedimos una función que reciba un vector con marca de final (por ejemplo un string null terminated) no tendría que ser necesario hacer un primer recorrido para averiguar su longitud y luego otro recorrido para procesarlo.
