### ISSUE TITLE
ej 5 guía 8

### ISSUE THREAD

**Issue by ghost** [marcelogarberoglio/PI#32]
Hola, buenos días. 
Quería consultar si este ejercicio está bien resuelto. Pareciera funcionar, pero dado que es un tema nuevo con mucho a tomar en cuenta quería saber si estoy haciendo algo no recomendable o directamente mal. Gracias por su tiempo.
A continuación pego el código:

```
#include "stdio.h"
#include "stdlib.h"
#include "time.h"
#define RAD_MIN 10
#define RAD_MAX 20
typedef struct{
    int x;
    int y;
} tipoPunto;
typedef struct{
    int rad;
    int tiempo;
    float relacion;
} tipoData;
// devuelve una ficha de datos de la caminata de la particula.
tipoData caminata(int radio){
    int pos[] = {-1,1};
    int t = 0;
tipoData datosCaminata;
tipoPunto particula = {0,0};
    do {
        t++;
        particula.x = (particula.x + pos[rand()%2]);
        particula.y = (particula.y + pos[rand()%2]);;
    }while((particula.x * particula.x) + (particula.y * particula.y) < (radio * radio));
    datosCaminata.rad = radio;
    datosCaminata.tiempo = t;
    datosCaminata.relacion = (float)radio / t;
    return datosCaminata;
}
void imprimirData(tipoData * data){
    printf("%10s | %10s | %10s | %10s", "CAMINATA", "RADIO", "TIEMPO", "RELACION\n");
    int j = 1;
    for (int i = RAD_MIN; i <= RAD_MAX; i++,j++){
        printf("%10d | %10d | %10d | %2f\n", j , data[j-1].rad, data[j-1].tiempo, data[j-1].relacion);
    }
}
int main(void){
    srand(time(NULL));
    tipoData * datos;
    datos = malloc((RAD_MAX - RAD_MIN + 1)*sizeof(tipoData));
    for(int rad = RAD_MIN, i = 0; rad <= RAD_MAX; rad++,i++){
        datos[i] = caminata(rad);
    }
    imprimirData(datos);
    free(datos);
}
```

**Comment by marcelogarberoglio** [comment]
El uso de structs está bien
Hay algunos detalles a corregir:
1) No es necesario almacenar todos los movimientos para después imprimirlos, podrías ir imprimiendo directamente. De hecho no sabés cuántos movimientos serán ya que es al azar (podría dar unas cuantas vueltas antes de salir, o sea

int main(void){
    srand(time(NULL));
    printf("%10s | %10s | %10s | %10s", "CAMINATA", "RADIO", "TIEMPO", "RELACION\n");
    for(int rad = RAD_MIN, i = 0; rad <= RAD_MAX; rad++,i++){
            imprimirData(caminata(rad));  // cambiando la función imprimirData para que sólo imprima una línea
    }

}
2) En cada paso debería poder moverse en cualquiera de las cuatro direcciones (arriba, abajo, derecha, izquierda) y por la forma en que hacés los movimientos siempre se mueve en diagonal, ya que incrementás o decrementás en 1 tanto x como y

**Comment by ghost** [comment]
Gracias Marcelo. 
Con respecto a la corrección 1) me queda la duda, yo estoy guardando una "ficha" (struct tipoData) que contiene el tiempo que tardó, el radio de la caminata y la relación de cada caminata, pero entiendo que no estaría guardando cada movimiento de la partícula. Esa "ficha" que armo la va guardando en un vector de fichas que yo se que va a ser una cantidad fija de fichas pues son la cantidad de radios distintos.

Vuelvo a plantear la parte del imprimirData y lo del movimiento, muchas gracias!

**Comment by marcelogarberoglio** [comment]
Con respecto a la 1, es cierto, no te guardás todos los movimientos sino los resultados, pero igual tampoco es necesario guardarlos todos, al menos en este caso.
