### ISSUE TITLE
Guía 8, Ej 4.a: Juego de naipes

### ISSUE THREAD

**Issue by berni-245** [marcelogarberoglio/PI#33]
Buenas! Estoy teniendo algunos problemas con encontrar la mejor forma de encarar este ejercicio. Adjunto la idea de cómo inicialmente pensé encarar este ejercicio a continuación (Sólo hay una de las funciones escritas en el main programada), junto a algunas preguntas específicas abajo del código.

```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../random.h"

#define CARTAS_MAZO 52
#define CANT_FIGURAS 13
#define CANT_PALOS 4
#define CARTAS_JUGADOR 5
#define LETRAS_PALO 8

//Acá declaré el enum por si le encontraba uso más adelante
typedef enum posNumeros{AZ=1,DOS,TRES,CUATRO,CINCO,SEIS,SIETE,OCHO,NUEVE,DIEZ,J,Q,K} numeros;

typedef struct{
    int numero;
    char palo[LETRAS_PALO+1];  
}carta;

//cartas es un vector de varios struct carta
typedef carta cartas[CARTAS_MAZO];

//Acá utilicé un puntero porque no sé si debería contemplar los casos cuando reparto algo menor a 5 cartas
typedef carta * jugador; 

//genera y mezcla el mazo
void prepararMazo(cartas mazo);

//toma el mazo actual y devuelve un vector de 5 cartas por jugador, y la nueva dimensión del mazo
jugador repartirCartas(cartas mazo, int * dim);

//imprime la mano actual de un jugador
void imprimirMano(jugador jugadorX);

//checkea si la mano actual de un jugador tiene algún PAR/PIERNA/POKER 
void checkearMano(jugador jugadorX);

int
main(){
    cartas mazo;
    jugador jugador1;
    int dim = CARTAS_MAZO;

    randomize();
    prepararMazo(mazo);
    
    do{
        jugador1 = repartirCartas(mazo, &dim);

        imprimirMano(jugador1);
        checkearMano(jugador1);

    }while(dim > 0); //o "dim >= CARTAS_JUGADOR" si sólo quisiera repartir de a 5
    
    printf("FIN.\n");


    return 0;
}

void
prepararMazo(cartas mazo){
    int i, j, aux;
    short index[CARTAS_MAZO];
    char * palos[] = {"corazon","trebol","pica","diamante"};
    numeros numeroActual = AZ-1;

    for(i=0; i<CARTAS_MAZO; i++){
        index[i] = i;   //índices de 0 a 51
    }

    for(i=0; i<CARTAS_MAZO; i++){ //desordeno los índices
        j = randInt(0,CARTAS_MAZO-1);
        aux = index[i];
        index[i] = index[j];
        index[j] = aux;
    }
    
    for(i=0; i<CARTAS_MAZO; i++,j++){
        if(!(i%CANT_PALOS)){
            numeroActual++;
            j=0;
        }
        
        //En lugar de asignarlos en orden ascendente, los asigno en el orden aleatorio de los índices que quedaron antes

        mazo[index[i]].numero = numeroActual; 
        strcpy(mazo[index[i]].palo, palos[j]);
                
    }       
}
```

Dudas:
1) Si bien intenté usar un vector de punteros a char para los palos, esto involucraría probablemente muchos loops para validar luego si dos cartas son del mismo palo. Conviene usar algún número o char de referencia, o igualmente es válido de esta forma?
2) En el código no estaba seguro si el juego debería seguir hasta que queden 0 cartas en el mazo o hasta que no se puedan repartir 5, cuál sería la correcta? (Si bien en el ejercicio 4a no se menciona hacer el programa hasta quedarte sin mazo, quería más o menos encaminarlo para el 4b)
3) Hay alguna forma de realizar el algoritmo de generar cartas y mezclarlas más eficiente?

Muchas gracias!

**Comment by marcelogarberoglio** [comment]
1. Me parece que te complicaste un poco. En vez de un enum podrías tener un string con los "números a imprimir", por ejemplo así
char * valores[] = { "2", "3", "4", ... "J", "Q", "K", "As"}
y entonces la carta 0 será la menor, ya que representa el 2
Y con los palos podrías hacer algo parecido
char * palos[4]  = { "....", 
De esa forma en la estructura carta sólo tenés dos campos int o char: número (entre 0 y 12)  y palo (entre 0 y 3)

2.Deberías seguir hasta que no se pueda completar una mano
3.Para generar el mazo tenés que primero hacer un ciclo para todas y luego mezclar, no hay forma más eficiente. Fijate que siguiendo los consejos del punto 1 es más fácil asignar número y palo.

**Comment by berni-245** [comment]
Ahh, perfecto. Entonces usaría los dos elementos del struct cómo índice para acceder a las posiciones del vector valores y el vector palos que mencionas, ya sea para asignar al mazo o para imprimir, no?
Pregunta de curiosidad, pero ya que estos dos vectores los necesitaré usar varias veces, estaría justificado inicializarlos en el header? Tipo variable global. Ya que de todas formas nunca los cambiaré, sólo los usaré para "interpretar" el nombre y valor de cada elemento.

**Comment by marcelogarberoglio** [comment]
Esos vectores se usarían sólo para imprimir, por lo que podrían ser static en la función que imprime. 
Se justificaría que fueran globales si se usarn en varias funciones, y sólo porque son valores que no van a cambiar. Desde el punto de vista del uso sería equivalente a usar constantes simbólicas. Eso podría pasar en juegos más complejos, pero en este caso no es necesario que sean globales.

**Comment by berni-245** [comment]
Ahh, entiendo. Es bueno saber que podría ser una posibilidad de todas formas.
Muchas gracias por las respuestas Marcelo!
