### ISSUE TITLE
Consulta ejercicio de parcial

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#4]
# Consulta ejercicio de parcial
Buenas, hice el parcial del 13/04/18 y quería pedir la corrección de un ejercicio. Funciona pero quiero saber si está bien el estilo, hay una parte que repite un poco de  código pero no se ocurrió cómo evitarlo. Además tenía una consulta sobre una warning que me tira gcc que no entiendo.

## Enunciado Ej3
Se dice que una matriz de números enteros es "escalable" si para cada fila (excepto la primera) la suma de sus elementos es igual a 1 + la suma de los elementos de la fila anterior, y para cada columna (excepto la primera) se cumple que la suma de sus elementos es igual a la suma de la columna anterior + 1. 
Escribir una función que reciba una matriz de enteros y retorne 1 si es escalable y 0 sino. Agregar los parámetros que sean necesarios.

## My resolución
```c
#include <stdio.h>

int sumRow(unsigned int rows, unsigned int cols, const int m[][cols], unsigned int row);
int sumCol(unsigned int rows, unsigned int cols, const int m[][cols], unsigned int col);
int isScalable(unsigned int rows, unsigned int cols, const int m[][cols]);

int main() {
	int m1[][4] = {{1, 1, 1, 1}, {1, 2, 1, 1}, {1, 1, 2, 2}, {1, 1, 2, 3}};
	int m2[][4] = {{1, 1, 1, -1}, {1, 2, 1, 1}, {1, 1, 2, 2}, {1, 1, 2, 3}};
	int m3[][3] = {{1, 1, 1}, {1, 1, 2}, {1, 2, 2}, {2, 2, 2}};
	int m4[][3] = {{1, 1, 1}, {1, 1, 2}, {1, 2, 2}, {2, 3, 1}};

	printf("m1 is scalable: %s.\n", isScalable(4, 4, m1) ? "Yes" : "No");
	printf("m2 is scalable: %s.\n", isScalable(4, 4, m2) ? "Yes" : "No");
	printf("m3 is scalable: %s.\n", isScalable(4, 3, m3) ? "Yes" : "No");
	printf("m4 is scalable: %s.\n", isScalable(4, 3, m4) ? "Yes" : "No");

	return 0;
}

int isScalable(unsigned int rows, unsigned int cols, const int m[][cols]) {
	int sumPrev = sumRow(rows, cols, m, 0);
	int sumCurrent = sumRow(rows, cols, m, 1);
	int isScalable = (sumCurrent == sumPrev + 1);
	for (int i = 2; i < rows && isScalable; ++i) {
		sumPrev = sumCurrent;
		sumCurrent = sumRow(rows, cols, m, i);
		if (sumCurrent != sumPrev + 1) {
			isScalable = 0;
		}
	}

	if (isScalable) {
		sumPrev = sumCol(rows, cols, m, 0);
		sumCurrent = sumCol(rows, cols, m, 1);
		isScalable = (sumCurrent == sumPrev + 1);
		for (int j = 2; j < cols && isScalable; ++j) {
			sumPrev = sumCurrent;
			sumCurrent = sumCol(rows, cols, m, j);
			if (sumCurrent != sumPrev + 1) {
				isScalable = 0;
			}
		}
	}

	return isScalable;
}

int sumRow(unsigned int rows, unsigned int cols, const int m[][cols], unsigned int row) {
	int sumRow = 0;
	for (int j = 0; j < cols; ++j) {
		sumRow += m[row][j];
	}

	return sumRow;
}

int sumCol(unsigned int rows, unsigned int cols, const int m[][cols], unsigned int col) {
	int sumCol = 0;
	for (int i = 0; i < rows; ++i) {
		sumCol += m[i][col];
	}

	return sumCol;
}
```
Mi duda era más que nada con la función de `isScalable()` donde medio que se repite el código entre el chequeo de las filas y el de las columnas.
## Warning de gcc
Y acá está la warning que me tira, ~pero no tengo idea qué es lo que detecta mal~. Además funciona bien...

![image](https://user-images.githubusercontent.com/88512894/188936511-62952a5a-a215-439a-a452-601992ae1753.png)

Justo se me ocurrió cuál podía ser el problema y lo probé y era eso. El warning viene porque en los parámetros de las funciones digo que la matriz es const. Pero no entiendo por qué eso estaría mal. Lo habíamos usado ya con vectores eso o no? Cuál es la diferencia acá??

**Comment by marcelogarberoglio** [comment]
Por el warning, es un tema de gcc, ya que interpreta el const como parte del tipo de datos del parámetro, gcc entiende que el parámetro m es "un vector de vectores constantes" y en main no está definido como const. Pueden ignorarlo o sacar el const del prototipo cuando usen "matrices". 
Una tercera opción, si realmente querés indicar const y que no tire el warning, es castear las llamadas a la función, como en el siguiente ejemplo, pero no es algo que les vayamos a pedir, de hecho no lo aplicamos nosotros en las soluciones

#define DIM 10

void f(const int matrix[][DIM]) {
   // Nada, solo probando el warning
}

int main(void) {
    int mat[DIM][DIM];

    f((const int (*)[DIM])   mat);   // casteamos para que no tire warning gcc

    return 0;
}



En cuanto a los códigos, están bien, tanto en eficiencia como estilo. Se podría hacer una pequeña mejora para que quede más corto:

        int sumPrev;
        int sumCurrent = sumRow(rows, cols, m, 0);
	int isScalable = 1;
	for (int i = 1; i < rows && isScalable; ++i) {
		sumPrev = sumCurrent;
		sumCurrent = sumRow(rows, cols, m, i);
		if (sumCurrent != sumPrev + 1) {
			isScalable = 0;
		}
	}

y lo mismo para columnas

**Comment by fmorroni** [comment]
Listo genial. No se cómo no se me ocurrió ese cambio que dijiste con sumPrev y sumCurrent...

Y por lo del warning, okay, pero es aún más molesto que con lo de los punteros 🙃
Igual no termino de entender bien qué es lo que decís ahí. Le pedís que castee el `int [][]` a un puntero a `int []` constante??

**Comment by marcelogarberoglio** [comment]
En la próxima clase vamos a ver la equivalencia entre vectores y punteros. Cuando decís que esperás un vector, o sea

func(int v[]);

estás diciendo que v es la dirección de un int, y entonces como tipo de dato el compilador lo ve así

func(int * v);

entonces cuando decís que recibís vector de vectores, como tipo de datos el compilador lo ve así

func(int (*v)[DIM]);

que se lee como "v es la dirección de un vector de DIM enteros"

**Comment by fmorroni** [comment]
Claro genial, gracias!
