### ISSUE TITLE
Guía 10, Ej 4: Función addAll

### ISSUE THREAD

**Issue by berni-245** [marcelogarberoglio/PI#42]
Buenas! Me gustaría saber si la siguiente resolución es correcta. Si bien pasa el testeo, como vi que me quedó un poco distinta a la solución preferiría confirmar si está bien. Adjunto el enunciado y el código.
![E4](https://user-images.githubusercontent.com/90289132/198896842-13781197-43fa-4497-a09e-0328eab66ee7.png)

```C
TList
addAll(TList l1, TList l2){
    if(l2 == NULL)
        return l1;

    if(l1 == NULL || l1->elem > l2->elem){
        TList aux = malloc(sizeof(*aux));
        aux->elem = l2->elem;
        aux->tail = l1;
        aux = addAll(aux, l2->tail);
        return aux;
    }

    if(l1->elem < l2->elem){
        l1->tail = addAll(l1->tail, l2);
    }
    
    if(l1->elem == l2->elem)
        l1 = addAll(l1, l2->tail); //como no hay repetidos en ninguna lista, si lo encontré, ya no volverá a aparecer ese numero

    return l1;
}
```

**Comment by marcelogarberoglio** [comment]
Lo que cambiaría es agregar un else en vez del último if, o sea

if(l1->elem < l2->elem){
        l1->tail = addAll(l1->tail, l2);
    }
else // son iguales
        l1->tail = addAll(l1->tail, l2->tail);

ya que si bien es equivalente, en tu código estás haciendo un if que sí o sí va a ser verdadero. Si hay un if, debería ser  porque existe la posibilidad de que sea verdadero o falso.
Además cambié en la llamada pasándole l1->tail en vez de l1. Si bien en cuanto a resultado es lo mismo, de esta forma se hace una llamada menos.

**Comment by berni-245** [comment]
Claro, es mejor así con el else.
Ahhh, lo del l1->tail es para avanzar en ambas listas. Ya que como son listas ordenadas, entonces el siguiente elemento de la lista 2 va a ser siempre más grande que el actual de la lista 1, está mejor con el l1->tail entonces jaja.

Muchas gracias Marcelo!
