### ISSUE TITLE
Warning al imprimir punteros con %p

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#5]
Y ya que estoy acá dejo lo que mencioné hoy en clase de la warning cuando uso `%p` en el `printf()`.

![image](https://user-images.githubusercontent.com/88512894/188939266-81efb9da-4388-4537-9b42-7272fae25f14.png)

```C
#include <stdio.h>    
 
int
main(void) {
   int a = 0;
   int* p = &a;
   printf("%i\t", *p);
   printf("%p, sizeof(p) = %li\n", p, sizeof(p));

   return 0;
}
```

**Comment by marcelogarberoglio** [comment]
Honestamente, no le encuentro explicación al warning, ya que void * (lo veremos más adelante ) es automáticamente casteable o intercambiable con cualquier tipo de puntero. Pero si querés evitar el warning, también acá se puede usar casteo.
De hecho si declarás void* te deja asignarle otro puntero y no tira warning, así que no entiendo por qué lo tira en el printf. Te copio código de ejemplo sin warnings


#include <stdio.h>

int
main(void) {
   int a = 0;
   int* p = &a;
   void * q = p;    // no tira warning

   printf("%i\t", *p);
   printf("%p  %p, sizeof(p) = %li\n", (void *)p, q, sizeof(p));

   return 0;
}

**Comment by fmorroni** [comment]
Ahh bueno, gracias. Qué molesto jajaja

Y ahí lo busqué también en stackoverflow y dicen que el problema es que por el estándar el compilador no tiene permitido castear automáticamente a void*, y por eso el warning. La solución es castearlo manualmente como dijiste.

**Comment by marcelogarberoglio** [comment]
Si fuera cierto que el compilador no tiene permitido castear automáticamente a void* entonces esta línea también generaría warning o error

void * q = p; // no tira warning

**Comment by fmorroni** [comment]
Huh bueno es verdad, ni idea entonces jajaja.
Lo voy a tomar como otra decisión de diseño rara de C y listo.
