### ISSUE TITLE
2P EJ.2 2022

### ISSUE THREAD

**Issue by ThomasR62875** [marcelogarberoglio/PI#53]
Hola Marcelo, estoy haciendo el parcial del cuatri pasado, y queria ver si este ejercicio estaba bien. 
La consgina era: 

![image](https://user-images.githubusercontent.com/112571497/201201951-e7849270-3231-421c-a2b3-09b585f1aa56.png)

Tlist deleteN(Tlist l, char c, int * n)
{
    if(l==NULL){                //si llegue al final retorno NULL.
        return NULL;
    }

    l = deleteN(l->tail, c, n);

    if(l->c==c && *n>0){               //si encuentro la letra y todavia la quiero borrar lo hago 
        (*n)--;                                    //resto porq la borre una vez
        Tlist liberar = l;
        free(liberar);                        //libero el nodo q borre
        return l->tail;                       //para borrarlo lo salteo, por eso retorno el tail
    }

    return l;
}

**Comment by marcelogarberoglio** [comment]
Está bien.
