### ISSUE TITLE
2p 1c 2022 ej2

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#55]
Buenas tardes, el cuatri pasado me corrigieron lo siguiente en este ejercicio. Cuando lo volvi a intentar lo hice igual sin saberlo, pero no termino de entender la correccion:

![image](https://user-images.githubusercontent.com/113400047/201200258-96a24778-3d65-4c7d-9b96-f1e5d45b2efb.png)
![image](https://user-images.githubusercontent.com/113400047/201200298-f05a249a-43fb-4727-9864-da1b92e0511b.png)
![image](https://user-images.githubusercontent.com/113400047/201200531-536ffbca-53bb-44cd-bdc2-21572b65e628.png)

cuando lo hice de nuevo lo hice casi igual, salvo la recursion de pila

```C

TList deleteN(TList l, char c, int * n){
	if(l==NULL || *n <= 0){
		return l;
	}
	l = deleteN(l->tail, c, n);	
	if(l->c == c){
		TList aux = l;
		l=l->tail;
		free(aux);
		(*n)--;
		return l;	
	}	
	return l;	
}
```

lo que no termino de entender seria porque estaria mal hacer la comparacion al principio?
yo lo veo como que, en caso de que n sea menor desde el principio, ni siquiera entra en la recursion (lo cual seria bueno)
en el caso de que n cumple, entra en la recursion de pila y borra......(creo que mientras escribia esto lo fui entendiendo mejor)

igual quisiera saber cual seria el problema al hacer esto, para entenderlo definitivamente.

**Comment by marcelogarberoglio** [comment]
No sé como explicarlo distinto a lo que ya está comentado. El código tendría que ser así

```C
TList deleteN(TList l, char c, int * n){
	if(l==NULL {
		return l;
	}
	l = deleteN(l->tail, c, n);	
	if(l->c == c && *n > 0)){
		TList aux = l;
		l=l->tail;
		free(aux);
		(*n)--;
		return l;	
	}	
	return l;	
}

La validación que hacés sólo sirve si de entrada te mandan 0

**Comment by marcelogarberoglio** [comment]
Perdón, me concentré en el control de *n que preguntaste, pero en esta nueva versión  hay otro error que es asignar a l el llamado recursivo con l->tail. Aún si no aparece el carácter c, termina retornando NULL.

**Comment by julianBogado1** [comment]
ok, habiendo visto el codigo me cerro mas, graciass
