### ISSUE TITLE
ejercicio 1 segundo parcial (lista)

### ISSUE THREAD

**Issue by ariasnico** [marcelogarberoglio/PI#59]
Hola ! me gustaría saber si esta bien el siguiente código

`typedef struct node{
    int elem;
    struct node * tail;
}TNode;

typedef struct node * TList;

TList eliminaAlReves(TList l){
    //se que no es void la funcion porque el primer nodo puede cambiar
    //mi caso base es retorno l si l es NULL o l->tail es NULL 
    //agrego l->tail==NULL en el if pues el ultimo nodo siempre esta bien puesto
    if(l==NULL || l->tail==NULL){
        return l;
    }

    l->tail = eliminaAlReves(l->tail); //el salto de fe
    //confio ahora que toda la sublista esta ordenada

    //como debe ser ordenado ascendentemente entonces si el nodo en el que estoy es mayor= al siguiente
    //debo eliminar el nodo en el que estoy
    if(l->elem >= l->tail->elem){ 
        TList aux = l->tail;
        free(l);
        return aux;
    }
    
    return l;
}`

**Comment by marcelogarberoglio** [comment]
Sí, está bien.
