### ISSUE TITLE
Ej 18 tp6

### ISSUE THREAD

**Issue by ThomasR62875** [marcelogarberoglio/PI#6]
Hola, el ejercicio pasó el test. Pero mire lo que estaba en las soluciones y es bastante diferente por lo que queria saber si hay algun error en eficiencia o algo por el estilo, que no me haya dado cuenta.

Desde ya muchas gracias, Thomas.  

#define ABZ return 0;
#define COLS 4

int filasAmigas(int f1[], int f2[])
{
    int i, j, esta;

    for(i=0, esta=1; i<COLS&& esta; i++){               
        for(j=0, esta=0; j<COLS && !esta; j++){
            if(f1[i]==f2[j])
                esta=1;
        }
    }
    return esta; //si esta=1 las filas son besties
}

int matrizAmigas(int m1[][COLS], int fils1, int m2[][COLS], int fils2)      
{
    int i, j, esta;

    for(i=0, esta=1; i<fils1 && esta; i++){
        for(j=0, esta=0; j<fils2 && !esta; j++){
            if(filasAmigas(m1[i], m2[j])){
                esta=1;
            }
        }
    }
    return esta;
}

int sonAmigas(int m1[][COLS], int fils1, int m2[][COLS], int fils2)
{
    printf("%d ", matrizAmigas(m1, fils1, m2, fils2));                      //esto era para ver bien q devolvia la función anterior
    printf(" %d\n", matrizAmigas(m2, fils1,m1, fils2));
    if (matrizAmigas(m1, fils1, m2, fils2))
        return 1;
    else if (matrizAmigas(m2, fils2, m1, fils1))
        return 2;
    else
        ABZ
}

**Comment by marcelogarberoglio** [comment]
Está bien. La diferencia está en la modularización, ya que nosotros además usamos una función para saber si un elemento está en un vector o no.
