### ISSUE TITLE
collectionADT segundo parcial

### ISSUE THREAD

**Issue by ariasnico** [marcelogarberoglio/PI#60]
Hola! quería saber si esta bien el siguiente código:

`#include "collectionADT.h"

typedef int (*compare) (elemType,elemType);

typedef struct collectionCDT{
    elemType * collection;
    size_t size;
    compare cmp; //funcion para eliminar
    char * ocupados; //vector que voy a usar con 0 y 1 para ver si una posicion esta ocupada
    size_t enUso; 
}collectionCDT;

collectionADT newCollection(compare cmp){
    collectionADT new = calloc(1,sizeof(collectionCDT));
    new->cmp = cmp;
    return new;
}

/* Retorna cuántos elementos hay insertados */
int elementCount(collectionADT c){
    return c->enUso;
}

/* Almacena un elemento en la posición pos.
** Si había un elemento en esa posición, lo pisa con elem
*/
void putElement(collectionADT c, elemType elem, size_t pos){
    //me fijo si la posicion existe, sino tengo que agrandar el espacio del vector
    if(c->size <= pos){
        c->collection = realloc(c->collection,pos);
        c->ocupados = realloc(c->ocupados,pos);
        //ahora lleno con ceros el ocupados y aumento el size
        for(int i=c->size; i<pos ; i++){
            c->ocupados[i]=0;
        }
        c->size = pos+1;
    }
    //agrego el elemento, aumento el numero de usados
    c->collection[pos] = elem;
    c->ocupados[pos] = 1;
    (c->enUso)++;
}

/* Elimina el elemento en la posición pos.
** Si no hay elementos en pos, no hace nada */
void deleteElement(collectionADT c, size_t pos){
    if(c->size <= pos || c->ocupados[pos]==0){
        return;
    }
    c->ocupados[pos]=0;
    (c->enUso)--;
    return;
}

/* Retorna la posición en el cual está insertado el elemento,
** o -1 si no lo encuentra
*/
int getPosition(collectionADT c, elemType elem){
    for(int i=0; i<c->size; i++){
        if(   (  c->ocupados[i]==1  ) && (  c->cmp(elem,c->collection[i])  ) ){//si esta retorno la posicion
            return i;
        }
    }
    return -1;
}

/* Libera todos los recursos reservados por el TAD */
void freeCollection(collectionADT c){
    free(c->collection);
    free(c->ocupados);
    free(c);
}`

**Comment by marcelogarberoglio** [comment]
Traten de enviar el código indentado, pueden anteponer  ```C para que quede indentado y coloreado

Simpre en putElement hac;és
(c->enUso)++;
Deberías hacerlo sólo cuando la posición estaba libre
EL ejercicio es el mismo que el vectorADT de la guía (en realidad una parte del mismo)

**Comment by ariasnico** [comment]
muchas gracias!
