### ISSUE TITLE
Ejercicio 3 2do Parcial

### ISSUE THREAD

**Issue by romamati** [marcelogarberoglio/PI#62]
Buenas! Intente rehacer el ejercicio 3, me gustaría saber si mi resolución es correcta. Hice varios comentarios que me ayudaban a interpretar lo que estaba haciendo y le modifique los nombres a las estructuras pero mas allá de eso todo el resto estaría igual.
Desde ya, muchas gracias.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ej3ADT.h"
#define BLOQUES 10

typedef struct sinonimos
{
    char * sinonimo;
    // size_t length;//longitud del sinonimo (NO me lo dan)
    struct sinonimos * siguiente_sinonimo;
}Tsinonimo;

typedef struct palabras
{
    char *palabra;
    // size_t length;//longitud de la palabra (NO me lo dan)
    // size_t cant_sin;//Cantidad total de sinonimos de la palabra (NO me lo dan)
    struct palabras *siguiente_palabra;
    struct sinonimos *first_sinonimo;//puntero a la lista de sinonimos de la palabra
}Tpalabras;

typedef struct dicSynCDT
{
    struct palabras * first;
    size_t size;//cantidad de palabras en el diccionario
}dicSynCDT;

/* Retorna un nuevo diccionario de sinónimos. Al inicio está vacío.
** No hay límite de capacidad.*/

dicSynADT newDicSyn()
{
    return calloc(1, sizeof(dicSynCDT));
}

// /* Busca el nodo con la palabra word. Si no estaba lo agrega en forma ascendente** y hace que node apunte al nuevo
//  *nodo.** Si ya estaba entonces node apunta al nodo que contiene word*/
static Tpalabras * addWord( Tpalabras * first, const char * word,Tpalabras ** node, int * flag) 
{}

//Funcion auxiliar que agrega un sinonimo a una palabra
Tsinonimo * addRec(Tsinonimo * sin, const char * synonymous)
{
    int c; 
    if(sin == NULL || (c=strcasecmp(sin->sinonimo, synonymous)) > 0)//En este caso agrego al sinonimo
    {
        Tsinonimo * aux = malloc(sizeof(Tsinonimo)); 
        aux->siguiente_sinonimo = sin;
        // aux->sinonimo = malloc(strlen(synonymous)+1);//OJO! le tengo que dar espacio primero. Al final como en add cuando agrego el sinonimo a la lista de sinonimos de la palabra, como lo hago pasandole node2->palabra, esto no es necesario pero si le pasaba como parametro a synonimous si era necesario
        // strcpy(aux->sinonimo,synonymous);//Analogo a lo que dije en la linea anterior esto ya no es necesario
        aux->sinonimo = synonymous;//Con el truco del node2->palabra en add puedo hacer directamente esto en vez de un strcpy pues aux->sinonimo es un puntero
        return aux;
    }
    else if(c < 0)//avanzo
    {
        sin->siguiente_sinonimo = addRec(sin->siguiente_sinonimo, synonymous);
        return sin;
    }

    //Si llega aca es porque el synonimo ya estaba y por ende no modifico mi lista de sinonimos
    return sin;
}

/* Agrega una relación entre una palabra y su sinónimo** Se asegura que tanto word como synonymous no son NULL ni 
vacíos** Ver ejemplo de uso*/

void add(dicSynADT dict, const char * word, const char * synonymous)
{
    Tpalabras * node;
    int flag = 0;
    dict->first = addWord(dict->first, word, &node, &flag);
    dict->size += flag;

    Tpalabras *node2;
    flag = 0;
    dict->first = addWord(dict->first, synonymous, &node2, &flag);//Agrego al sinonimo a mi lista de palabras
    dict->size += flag;

    node->first_sinonimo = addRec(node->first_sinonimo, node2->palabra);//Agrego el sinonimo a la lista de sinonimos. OJO! Uso node para asignar pues en node esta la direccion de la palabra
//Notemos que al pasarle node2->palabra lo que sucede es que el usuario en el main no puede editar el sinonimo que estoy agregando pues a node2 no lo tiene. En cambio, a *synonimus justamente si lo puede modificar pues en el main tenemos a la variable synonimous y esa la puede modificar a gusto y como  *synonimus justamente es un puntero a esa variable entonces se modificaria 
}

/* Retorna cuántas palabras hay en el diccionario. Se cuentan tanto las palabras** como los sinónimos (los parámetros
word y synonymous de la función anterior)*/

size_t size(const dicSynADT dict)
{
    return dict->size;
}

//Funcion auxiliar que buscar a una palabra en una lista de palabras y retorna su direccion si la encuentra o NULL si no
//Notemos que tengo que crear esta funcion pues si bien en la funcion addWord que me dan se busca a la palabra, en caso de que no se la encuentre no retorna NULL sino que la agrega y esto no me sirve
Tpalabras * BuscaPalabra(Tpalabras * palabras,const char * word )
{
    int c; 
    if(palabras = NULL || (c= strcasecmp(palabras->palabra,word))>0)//En cualquiera de estos casos ya se que no la encuentra
    {
        return NULL;
    }
    else if(c < 0)//avanzo
    {
        return BuscaPalabra(palabras->siguiente_palabra, word);
    }

    //Si llega aca es porque la encontro
    return palabras;
}

//Funcion recursiva que recibe un sinonimo y un vecto y mete al sinonimo en el vector
// void toArraySinonymRec(char ** vector, Tsinonimo * synonimList)
// {
//     if(synonimList == NULL)//si llegue hasta el final de la lista retorno NULL
//     {
//         vector[0] = NULL; //Pues mi vector debe finalizar con NULL
//         return;
//     }

//     vector[0]= malloc(sizeof(char) * (strlen(synonimList->sinonimo)+1));//le doy espacio
//     strcpy(vector[0], synonimList->sinonimo);
//     toArraySinonymRec(vector+1, synonimList->siguiente_sinonimo);

// }
//Ojo! Esta funcion solo me seria util si tuviera la cantidad total de sinonimos en mi struct pero como no la tengo tengo que encontrar otra manera

//Tengo que armarme un for iterativo dentro de mi funcion synonyms

/* Dada una palabra retorna un vector con una copia de todos sus sinónimos** ordenados alfabéticamente, con NULL como
 marca de final*/
char ** synonyms(dicSynADT dict, const char * word)
{
    //Busco a la palabra y la guardo en una variable direccion
    Tpalabras * direccion = BuscaPalabra(dict->first, word);
    //me fijo si direccion es NULL o no 
    if(direccion == NULL)
    {
        return calloc(1, sizeof(char*)); 
    }
    //si direcion no es nula entonces me creo un vector de punteros a char
    char ** vector = NULL;
    Tsinonimo * iter = direccion->first_sinonimo;//creo un iterador para recorrer mi lista de sinonimos
    int i;
    for ( i = 0; iter != NULL; i++, iter=iter->tail)
    {
	    if ( i % BLOQUES == 0) 
        {
	        vector = realloc(vector, sizeof(char*) * (i+BLOQUES)); //doy espacio para mas palabras
	    }
	    //ahora que se que tengo espacio:
	    vector[i] = malloc( strlen(iter->sinonimo)+1); //le doy espacio al elemento para copiarle el sinonimo
	    strcpy(v[i], iter->sinonimo);//Copio al sinonimo
    }
//Le doy el espacio exacto que necesito
vector = realloc(vector, sizeof(char *) * (i+1));

//Finalizo mi vector con NULL
vector[i] = NULL;

return vector;
}

// Funcion recursiva que recibe una palabra y un vector y mete a la palabra en el vector
static void toArrayPalabraRec(char ** vector, Tpalabras * palabraList)
{
    if(palabraList == NULL)//si llegue hasta el final de la lista retorno NULL
    {
        vector[0] = NULL; //Pues mi vector debe finalizar con NULL
        return;
    }

    vector[0]= malloc(strlen(palabraList->palabra)+1);//le doy espacio
    strcpy(vector[0], palabraList->palabra);//Copio la palabra
    toArrayPalabraRec(vector+1, palabraList->siguiente_palabra);//OJO! aca un error comun seria pasarle vector++ pero esto estaria mal pues al pasarle vector++ primero toma la direccion de vector para ejecutar la funcion y recien despues de eso la incrementa 
    return;
}

/* Retorna un vector con las palabras y sinónimos del diccionario (ver ejemplo)** El vector está ordenado en forma 
ascendente y contiene NULL como marca de** final.
** Si no hay palabras, retorna un vector que sólo contiene NULL*/

//Para esta funcion si puedo utilizar una funcion recursiva pues en la estructura que me dan poseo la cantidad total de las palabras
char ** words(const dicSynADT dict)
{
    if(dict->first == NULL)
    {
        return calloc(1,sizeof(char*));
    }
    char ** vector = malloc((dic->size)* sizeof(char*)); //esto se lo paso por parametro a una recursiva junto con la primer palabra de mi lista de palabras
    toArrayPalabraRec(vector, dict->first);
    return vector;
}

**Comment by marcelogarberoglio** [comment]
En addRec esta línea debe ir fuera del if
   return sin;

El resto está bien. Traten para la próxima de mandar los códigos indentados
