### ISSUE TITLE
EJ 3 -Segundo Parcial

### ISSUE THREAD

**Issue by julietaTechenski** [marcelogarberoglio/PI#65]
Hola, buen día. Quería consultar si este ejercicio esta bien resuelto y sino cuales son mis problemas. No estoy segura de haber hecho bien la función de synonyms o words a pesar de que tuve en cuenta lo que se explico en la revisión ¿Está bien  igualar palabra a palabra->tail? Desde ya, mil gracias.

#include "dicSynADT.h"

#include <stdlib.h>

typedef struct node {
    char * synonym;
    struct node * tail;
} node;

typedef struct wordWithSyns {
    char * word;
    node * syns;
    struct wordWithSyns * tail;
} wordWithSyns;

typedef struct dicSynCDT {
    size_t size; // cantidad de palabras
    wordWithSyns * first;
}dicSynCDT;

dicSynADT newDicSyn() {
    return calloc(1, sizeof(dicSynCDT));
}

size_t size(const dicSynADT dict) {
    return dict->size;
}

/*
** Busca el nodo con la palabra word. Si no estaba lo agrega en forma ascendente
** y hace que node apunte al nuevo nodo.
** Si ya estaba entonces node apunta al nodo que contiene word
*/
static wordWithSyns * addWord( wordWithSyns * first, const char * word, wordWithSyns ** node, int * flag );

static node * addSyn(node * first, char * syn){
    if(first == NULL){
        node* aux = malloc(sizeof(node));
        aux->synonym = syn;
        aux->tail = first;
        return first;
    }
    if(strcmp(first->synonym, syn) == 0){
        return first;
    }
    first->tail = addSyn(first->tail, syn);
}

/* Agrega una relación entre una palabra y su sinónimo
** Se asegura que tanto word como synonymous no son NULL ni vacíos
** Ver ejemplo de uso*/
void add(dicSynADT dict, const char * word, const char * synonymous) {
    // Primero veo si hay que agregar word. Me retorna en un parámetro
    // de salida una referencia al nodo, y en un flag retorna 0 si estaba o 1
    // si lo agregó
    wordWithSyns * theWord;  //me permite guardar 
    int flag = 0;
    dict->first = addWord(dict->first, word, &theWord, &flag);
    dict->size += flag;
    // En theWord tenemos el puntero al nodo con la palabra word
    // Completar el resto de la función
    //ya tengo el nodo en donde se encuentra la palabra theWord
    node * theSynonym;
    wordWithSyns *theSyn;
    flag = 0;
    dict->first = addWord(dict->first, synonymous, &theSyn, &flag); // lo agrega en la lista principal de palabras y tmb en la lista the wword
    dict->size +=flag;

    theWord->syns = addSyn(theWord->syns, synonymous);
    return;

}

char ** synonyms(dicSynADT dict, const char * word) {
    char *rta[dict->size];
    // creo un char * rta q es lo que devuelvo y despues hago strcpy por cada uno de los sinonimos de la palabra
    node* sinon = dict->first->syns;
    for(int i = 0; sinon != NULL; i++){
        strcpy(rta[i], sinon->synonym);
        sinon = sinon->tail;
    }
    return rta;
}

char ** words(const dicSynADT dict) {
    char *rta[dict->size];
    wordWithSyns * palabra = dict->first;
    for(int i= 0; palabra != NULL; i++){
        strcpy(rta[i], palabra->word);
        palabra = palabra->tail;
    }
}

void freeDict(dicSynADT dict) {
// NO completar
}

**Comment by marcelogarberoglio** [comment]
addSyn no está bien, deberías insertar en orden, porque cuando te piden el vector con los sinónimos te lo piden ordenado. Deberías usar strcasecmp que ignorar minúsculas y mayúsculas

Hay varios errores conceptuales con punteros, por ejemplo

for(int i = 0; sinon != NULL; i++){ 
              // Antes del stcrpy hay que crear en espacio donde copiar
     rta[i] = malloc(strlen(.....
strcpy(rta[i], sinon->synonym);

char ** words(const dicSynADT dict) {
char *rta[dict->size];           // estás creando un vector en el stack, no en el heap

No hay ningún problema en modificar la variable palabra, es una variable auxiliar propia de la función, el problema sería que hagan algo así para recorrer

for(int i= 0; palabra != NULL; i++){
     // antes el malloc
        strcpy(rta[i], dict->first->word);
  dict->first = dict->first->tail;
}


En ambos vectores falta colocar el NULL al final

synonyms primero debe ubicar la palabra, y si se encuentra entonces sí copiar sus sinónimos

Mi recomendación es que hagas (o rehagas) los TADs de la guía, usando los programas de testeo. 
Siempre usando el flag de sanitizer.
Y luego sí rehacer el parcial.

**Comment by julietaTechenski** [comment]
Genial gracias, entonces me voy a sentar a revisar los ejercicios de la guía por las dudas. Ahí creo que pude corregir un par de los errores. 

/*
** Busca el nodo con la palabra word. Si no estaba lo agrega en forma ascendente
** y hace que node apunte al nuevo nodo.
** Si ya estaba entonces node apunta al nodo que contiene word
*/
static wordWithSyns * addWord( wordWithSyns * first, const char * word, wordWithSyns ** node, int * flag );

static node * addSyn(node * first, char * syn){
    if(first == NULL){
        node* aux = malloc(sizeof(node));
        aux->synonym = syn;
        aux->tail = first;
        return aux;
    }
    if(strcasecmp(first->synonym, syn) == 0){
        return first;
    }

    if(strcasecmp(first->synonym, syn) < 0){
        first->tail = addSyn(first->tail, syn);
    }

    if(strcasecmp(first->synonym, syn) > 0){
        node* aux = malloc(sizeof(node));
        aux->synonym = syn;
        aux->tail = first;
        return aux;
    }
    //no hay mas casos
}


/* Agrega una relación entre una palabra y su sinónimo
** Se asegura que tanto word como synonymous no son NULL ni vacíos
** Ver ejemplo de uso*/
void add(dicSynADT dict, const char * word, const char * synonymous) {
    // Primero veo si hay que agregar word. Me retorna en un parámetro
    // de salida una referencia al nodo, y en un flag retorna 0 si estaba o 1
    // si lo agregó
    wordWithSyns * theWord;  //me permite guardar 
    int flag = 0;
    dict->first = addWord(dict->first, word, &theWord, &flag);
    dict->size += flag;
    // En theWord tenemos el puntero al nodo con la palabra word
    // Completar el resto de la función
    //ya tengo el nodo en donde se encuentra la palabra theWord
    node * theSynonym;
    wordWithSyns *theSyn;
    flag = 0;
    dict->first = addWord(dict->first, synonymous, &theSyn, &flag); // lo agrega en la lista principal de palabras y tmb en la lista the wword
    dict->size +=flag;

    theWord->syns = addSyn(theWord->syns, synonymous);
    return;

}

static void find( wordWithSyns * first, char *palabra, wordWithSyns ** theWord){
    int c;
    if(first == NULL || (c = strcasecmp(first->word, palabra)) < 0){  
        return;   // no existe la palabra
    }
    if((c = strcasecmp(first->word, palabra)) > 0){
        find(first->tail, palabra, theWord);
    }
    // si no se cumple que c es menor o mayor es que son iguales y modifico la direccion a la que apunta theWord para que apunte a la palabra
    (*theWord) = first;
}

char ** synonyms(dicSynADT dict, const char * word) {
    wordWithSyns *theWord = NULL;
    find(dict->first, word, &theWord);

    if(theWord != NULL){
        char **rta = malloc(sizeof(char*)*dict->size);
        // creo un char * rta q es lo que devuelvo y despues hago strcpy por cada uno de los sinonimos de la palabra
        node * sinon = (*theWord).syns;
        for(int i = 0; i < dict->size; i++){
            strcpy(rta[i], sinon->synonym);
            sinon = sinon->tail;
        }
        return rta;
    }
    return NULL;
}


char ** words(const dicSynADT dict) {
    char **rta = malloc(sizeof(char*)*dict->size);
    rta = NULL;
    wordWithSyns * palabra = dict->first;
    for(int i= 0; i < dict->size; i++){
        strcpy(rta[i], palabra->word);
        palabra = palabra->tail;
    }
    return rta;
}

void freeDict(dicSynADT dict) {
// NO completar
}

**Comment by marcelogarberoglio** [comment]
Sigue habiendo errores.
addSyn recibe elstring que le pasaron, debería guardar una copia, no el puntero que recibe
   Repite código.
   llama varias veces a strcasecmp, debería guardar el valor de la comparación. Son cosas que hicimos en todas las funciones que agregan en una lista ordenada

Ver estas dos líneas

char *rta = malloc(sizeof(char)*dict->size);
rta = NULL;

Siguen errores que mencioné antes, por ejemplo
strcpy(rta[i], palabra->word);   // antes hay que hacer rat[i] = malloc(....

find no la haría void,sino que retorne el puntero al nodo o NULL

**Comment by julietaTechenski** [comment]
** Busca el nodo con la palabra word. Si no estaba lo agrega en forma ascendente
** y hace que node apunte al nuevo nodo.
** Si ya estaba entonces node apunta al nodo que contiene word
*/
static wordWithSyns * addWord( wordWithSyns * first, const char * word, wordWithSyns ** node, int * flag );

static node * addSyn(node * first, char * syn){
    if(first == NULL){
        node* aux = malloc(sizeof(node));
        strcpy(aux->synonym, syn);
        aux->tail = first;
        return aux;
    }
    int c;
    if((c = strcasecmp(first->synonym, syn)) == 0){
        return first;
    }

    if(c < 0){
        first->tail = addSyn(first->tail, syn);
    }

    if(c > 0){
        node* aux = malloc(sizeof(node));
        aux->synonym = syn;
        aux->tail = first;
        return aux;
    }
    //no hay mas casos
}


/* Agrega una relación entre una palabra y su sinónimo
** Se asegura que tanto word como synonymous no son NULL ni vacíos
** Ver ejemplo de uso*/
void add(dicSynADT dict, const char * word, const char * synonymous) {
    // Primero veo si hay que agregar word. Me retorna en un parámetro
    // de salida una referencia al nodo, y en un flag retorna 0 si estaba o 1
    // si lo agregó
    wordWithSyns * theWord;  //me permite guardar 
    int flag = 0;
    dict->first = addWord(dict->first, word, &theWord, &flag);
    dict->size += flag;
    // En theWord tenemos el puntero al nodo con la palabra word
    // Completar el resto de la función
    //ya tengo el nodo en donde se encuentra la palabra theWord
    node * theSynonym;
    wordWithSyns *theSyn;
    flag = 0;
    dict->first = addWord(dict->first, synonymous, &theSyn, &flag); // lo agrega en la lista principal de palabras y tmb en la lista the wword
    dict->size +=flag;

    theWord->syns = addSyn(theWord->syns, synonymous);
    return;

}

static wordWithSyns **find( wordWithSyns * first, char *palabra){
    int c;
    if((c = strcasecmp(first->word, palabra) < 0 || first == NULL)){  
        return NULL;   // no existe la palabra
    }
    if(c > 0){
        first->tail = find(first->tail, palabra);
    }
    // si no se cumple que c es menor o mayor es que son iguales y modifico la direccion a la que apunta theWord para que apunte a la palabra
    return first;
}

char ** synonyms(dicSynADT dict, const char * word) {
    wordWithSyns *theWord = find(dict->first, word);

    if(theWord != NULL){
        char **rta = malloc(sizeof(char*)*dict->size);
        // creo un char * rta q es lo que devuelvo y despues hago strcpy por cada uno de los sinonimos de la palabra
        node * sinon = (*theWord).syns;
        for(int i = 0; i < dict->size; i++){
            rta[i] = malloc(strlen(sinon->synonym));
            strcpy(rta[i], sinon->synonym);
            sinon = sinon->tail;
        }
        return rta;
    }
    return NULL;
}


char ** words(const dicSynADT dict) {
    char **rta = malloc(sizeof(char*)*dict->size);
    rta = NULL;
    wordWithSyns * palabra = dict->first;
    for(int i= 0; i < dict->size; i++){
        strcpy(rta[i], palabra->word);
        palabra = palabra->tail;
    }
    return rta;
}

void freeDict(dicSynADT dict) {
// NO completar
}

**Comment by julietaTechenski** [comment]
Ahí lo volví a revisar. Me quedaron un par de dudas sobre porque se debería reservar espacio en esta parte:

char **rta = malloc(sizeof(char*)*dict->size);
   ....
for(int i= 0; i < dict->size; i++){
        rta[i] = malloc(strlen(palabra->word));   // aca
        strcpy(rta[i], palabra->word);

        ...
    }

En la primera linea (si esta bien) reservo el lugar para el vector con los sinónimos, pero me cuesta ver porque se reserva el lugar cuando se hace el strlen.  

/** Busca el nodo con la palabra word. Si no estaba lo agrega en forma ascendente
** y hace que node apunte al nuevo nodo.
** Si ya estaba entonces node apunta al nodo que contiene word
*/
static wordWithSyns * addWord( wordWithSyns * first, const char * word, wordWithSyns ** node, int * flag );

static node * addSyn(node * first, char * syn){
    if(first == NULL){
        node* aux = malloc(sizeof(node));
        strcpy(aux->synonym, syn);
        aux->tail = first;
        return aux;
    }
    int c;
    if((c = strcasecmp(first->synonym, syn)) == 0){
        return first;
    }

    if(c < 0){
        first->tail = addSyn(first->tail, syn);
    }

    if(c > 0){
        node* aux = malloc(sizeof(node));
        aux->synonym = syn;
        aux->tail = first;
        return aux;
    }
    //no hay mas casos
}


/* Agrega una relación entre una palabra y su sinónimo
** Se asegura que tanto word como synonymous no son NULL ni vacíos
** Ver ejemplo de uso*/
void add(dicSynADT dict, const char * word, const char * synonymous) {
    // Primero veo si hay que agregar word. Me retorna en un parámetro
    // de salida una referencia al nodo, y en un flag retorna 0 si estaba o 1
    // si lo agregó
    wordWithSyns * theWord;  //me permite guardar 
    int flag = 0;
    dict->first = addWord(dict->first, word, &theWord, &flag);
    dict->size += flag;
    // En theWord tenemos el puntero al nodo con la palabra word
    // Completar el resto de la función
    //ya tengo el nodo en donde se encuentra la palabra theWord
    node * theSynonym;
    wordWithSyns *theSyn;
    flag = 0;
    dict->first = addWord(dict->first, synonymous, &theSyn, &flag); // lo agrega en la lista principal de palabras y tmb en la lista the wword
    dict->size +=flag;

    theWord->syns = addSyn(theWord->syns, synonymous);
    return;

}

static wordWithSyns **find( wordWithSyns * first, char *palabra){
    int c;
    if((c = strcasecmp(first->word, palabra) < 0 || first == NULL)){  
        return NULL;   // no existe la palabra
    }
    if(c > 0){
        first->tail = find(first->tail, palabra);
    }
    // si no se cumple que c es menor o mayor es que son iguales y modifico la direccion a la que apunta theWord para que apunte a la palabra
    return first;
}

char ** synonyms(dicSynADT dict, const char * word) {
    wordWithSyns *theWord = find(dict->first, word);

    if(theWord != NULL){
        char **rta = malloc(sizeof(char*)*dict->size);
        // creo un char * rta q es lo que devuelvo y despues hago strcpy por cada uno de los sinonimos de la palabra
        node * sinon = (*theWord).syns;
        for(int i = 0; i < dict->size; i++){
            rta[i] = malloc(strlen(sinon->synonym));
            strcpy(rta[i], sinon->synonym);
            sinon = sinon->tail;
        }
        return rta;
    }
    return NULL;
}




char ** words(const dicSynADT dict) {
    char **rta = malloc(sizeof(char*)*dict->size);
    wordWithSyns * palabra = dict->first;
    for(int i= 0; i < dict->size; i++){
        rta[i] = malloc(strlen(palabra->word));
        strcpy(rta[i], palabra->word);
        palabra = palabra->tail;
    }
    return rta;
}

**Comment by marcelogarberoglio** [comment]
char *rta = malloc(sizeof(char)*dict->size);        Debería ser    char **rta = malloc(sizeof(char * )*dict->size);  
                                                                          Lo que estás haciendo es crear el vector para los punteros a char
....
for(int i= 0; i < dict->size; i++){
rta[i] = malloc(strlen(palabra->word)+1);             Acá se crea espacio para cada uno de los string
strcpy(rta[i], palabra->word);

Al ser un vector de strings, primero creás espacio para todos los punteros a char. Luego creás espacio para la copia de cada string. Fijate en el main de prueba cuando libera la rta, que primero libera cada string y luego libera el vector. No es algo nuevo, así hay hechos varios ejercicios en la guía, por ejemplo el socialADT y otros que retornan vectores de strings


También sigue con errores find, hay errores de tipo y otros

static wordWithSyns *find( wordWithSyns * first, char *palabra){
int c;
if(   first == NULL ||   (c = strcasecmp(first->word, palabra)) < 0  ){
return NULL; // no existe la palabra
}
if(c > 0){
//                          NO: first->tail = find(first->tail, palabra);   estás buscando, no cambiando la lista, 
                       // da la sensación de que se están haciendo las cosas medio de memoria, sin tener muy claro cómo
                   // manipular una lista.

   return find(first->tail, palabra);
}

return first;
}

No seguiría insistiendo con este ejercicio, seguiría con los de la guía que tienen su testeo. Tener que buscar los errores de por qué no funciona un test te obliga a reveer el código que estás haciendo, encontrar los errores y aprender a no volver a hacerlos. 
Luego entonces sí fijate de volver a hacer desde un principio este ejercicio.
