### ISSUE TITLE
EJ 1 - Segundo Parcial

### ISSUE THREAD

**Issue by julietaTechenski** [marcelogarberoglio/PI#66]
Hola, buen día. Mando una resolución del primer ejercicio que lo había pensado mal en parcial. Desde ya, mil gracias.

typedef struct node * TList;
 
typedef struct node{
  int elem; 
  struct node * tail; 
} TNode;
 
TList sortedList(TList list);
 
TList sortedList(TList list){
	if(list->tail == NULL)
		return list;

	
	list->tail = sortedList(list->tail);
	
	if(list->elem > list->tail->elem){
		TList aux;
		aux = list;
		list = list->tail;
		free(aux);
		return list;
	}
	
}

**Comment by marcelogarberoglio** [comment]
Está bien pensado pero hay dos errores

Debe ser 
if(list->elem >= list->tail->elem){

¿y qué devuelve si este if es falso? Si la función no es void siempre debe retornar algo o termina retornando basura
