### ISSUE TITLE
EJ 5 - Segundo Parcial

### ISSUE THREAD

**Issue by julietaTechenski** [marcelogarberoglio/PI#68]
Hola, buenas tardes. Paso mi resolución del ejercicio 5. Desde ya, mil gracias.

#define LIBROS 76
#define BLOCK 5

typedef struct verse{
	char *frases;  // vector con frases
	size_t dim;		
}verse;

typedef struct verse* TVerse;

typedef struct bibleCDT{
	TVerse biblia[LIBROS];
}bibleCDT;

bibleADT newBible(){
	return calloc(1, sizeof(bibleCDT));
}

/*
** Agrega un versículo a la Biblia. Si ya estaba ese número de versículo en ese
** número de libro, no lo agrega ni modifica y retorna 0. Si lo agregó retorna 1
** bookNbr: número de libro
** verseNbr: número de versículo
*/
int addVerse(bibleADT bible, size_t bookNbr, size_t verseNbr, const char * verse){
	// si todavia no se habia definiod el vector con los versos del libro pedido o el nro de verso es mas grande que la dimension del vector frases
    if(bible->biblia[bookNbr-1] == NULL || verseNbr > bible->biblia[bookNbr-1]->dim){
        if(bible->biblia[bookNbr-1] == NULL){  // si entro xq no estaba definido el vector necesito definir el veector frases de ese libro
            bible->biblia[bookNbr-1] = malloc(sizeof(TVerse)*BLOCK);
            bible->biblia[bookNbr-1]->dim = BLOCK;
            for(int k = 0; k<BLOCK; k++){
                bible->biblia[bookNbr-1]->frases[k] = NULL;
            }

        }
        int i;
        for(i = (bible->biblia[bookNbr-1]->dim-1); i < verseNbr; i+=BLOCK){  // mientras que la dimension del vector no alcance para guardar el nro de verso aumento de a bloques
            bible->biblia[bookNbr-1] = realloc(bible->biblia[bookNbr-1],sizeof(TVerse)*BLOCK);    
            bible->biblia[bookNbr-1]->dim = 0;
            for(int j = i; i%BLOCK != 0; j++){
                bible->biblia[bookNbr-1]->frases[j-1] = NULL;
            }
            bible->biblia[bookNbr-1]->dim = i-BLOCK;
        }
        bible->biblia[bookNbr-1]->frases[verseNbr-1] = verse;
        return 1;
    }
    else{   // si ya se habia definido un vector
        if(bible->biblia[bookNbr-1]->frases[verseNbr-1] == NULL){  // la posicion estaba definida pero no ocupada
            bible->biblia[bookNbr-1]->frases[verseNbr-1] = verse;
            return 1;
        }
        // si la posicion estaba ocupada 
        return 0;
    }
}

/*
** Retorna una copia de un versículo o NULL si no existe.
** bookNbr: número de libro
** verseNbr: número de versículo
*/
char * getVerse(bibleADT bible, size_t bookNbr, size_t verseNbr){
	char * versiculo;
	if( LIBROS < bookNbr || bible->biblia[bookNbr-1]->frases[verseNbr] == NULL || bible->biblia[bookNbr-1]->dim < verseNbr){
		return NULL;
	}
	strcpy(versiculo, bible->biblia[bookNbr-1]->frases[verseNbr]);
	return versiculo;
}

/* Libera todos los recursos reservados por el TAD */
void freeBible(bibleADT bible){
	for(int i = 0; i < LIBROS; i++){
		for(int j = 0; j< bible->biblia[i]->dim; j++){
			free(bible->biblia[i]->frases[j]);
		}
		free(bible->biblia[i]);
	}
	free(bible);
}

**Comment by marcelogarberoglio** [comment]
Hay muchos errores de tipos y de lógica. Si no pueden copiar el código desde el enunciado, dejo acá una copia, para que lo puedan probar. Insisito en mi sugerencia de hacer o rehacer los TADs de la guía, porque veo muchos errores importantes en esta solución planteada

int 
main(void) {
    bibleADT b = newBible(); 
    assert(getVerse(b, 1, 1)==NULL);

    char aux[2000];
    strcpy(aux, "En el principio creo Dios los cielos y la tierra.");
    assert(addVerse(b, 1, 1, aux)==1);

    strcpy(aux, "Y atardecio y amanecio: dia tercero.");
    assert(addVerse(b, 1, 13, aux)==1);

    assert(addVerse(b, 1, 13, "Amaos los unos a los otros")==0); // Ya estaba
  
    strcpy(aux, "los contados de la tribu de Dan fueron sesenta y dos mil setecientos.");
    assert(addVerse(b, 4, 39, aux)==1);

    assert(addVerse(b, 4, 46,
      "fueron todos los contados seiscientos tres mil quinientos cincuenta.")==1);

    char * v = getVerse(b, 4, 45);
    assert(v==NULL);

    v = getVerse(b, 4, 39);
    assert(strncmp(v, "los con", 7)==0);
    free(v);
    
    freeBible(b);

    puts("Aleluya !");
    return 0;
}
