### ISSUE TITLE
EJ1 - P(2C2018)

### ISSUE THREAD

**Issue by urielsv** [marcelogarberoglio/PI#8]
### EJERCICIO 1 - PARCIAL 2018 2C 
Hola! Recien es mi primer parcial y lo termine resolviendo de dos formas, uno con mayor modularizacion (pero hace loops de mas que no se me ocurrieron como solucionar) y otro con menos modularizacion pero mas eficiente. Cual estaria bien? (En caso de alguno estarlo).

_Dejo links para poder verlos desde la web._

**Version "no modular":** https://raw.githubusercontent.com/urielsv/PI/main/PARC/P1/2C2018/ej1a.c
**Version "modular"**: https://raw.githubusercontent.com/urielsv/PI/main/PARC/P1/2C2018/ej1b.c

Saludos y disculpas por las molestias! 😄

**Comment by marcelogarberoglio** [comment]
La versión ej1a no está bien primero y principal porque no respeta el enunciado, ya que se pide una función que reciba la matriz, y estás agregando un vector. Suponiendo que se cambia para que el vector sea interno, tampoco está bien porque no es necesario crear un vector para almacenar todos los posibles valores (la matriz podría tener cientos de filas), sino sólo guardarse el mayor.

Lo mismo cabe para la opción b.

Y tampoco es necesario ir calculando pot, podrías simplemente multiplicar por 10 el resultado parcial y sumarle el nuevo dígito.

Y por las dudas una aclaración: no es necesario en este caso crear una condición especial de eficiencia de forma tal que prediga si una fila, tan solo viendo el primer dígito, no superará el máximo. Por ejemplo: si tuviera 8 columnas y el máximo por ahora es 80000000, se puede descartar cualquier fila que empiece con 7 o menos. Pero repito: no es necesario contemplar esto para cortar antes.

Saludos y no se disculpen, no es molestia, para esto se armó este repositorio.

**Comment by urielsv** [comment]
Entendido, muchas gracias.
