### ISSUE TITLE
Consulta struct

### ISSUE THREAD

**Issue by julietaTechenski** [marcelogarberoglio/PI#82]
Hola, buenos dias. Quería saber si están bien planteadas las estructuras del ej 2 de este parcial. Desde ya, muchas gracias.

typedef elemento{
	elemTypeKey key;
	elemTypeValue value;
	size_t estado;
}elemento;

typedef struct dictCDT{
	elemento *diccionario;
	int (*cmpKey);
	size_t dim; // espacio ocupado
	size_t size;  //espacio reservado
}dictCDT;

[Segundo Parcial - 2017 - 24 de junio.pdf](https://github.com/marcelogarberoglio/PI/files/10123592/Segundo.Parcial.-.2017.-.24.de.junio.pdf)

**Comment by marcelogarberoglio** [comment]
La idea está bien, ya que al no pedir ordenado puede ser vector o lista, pero hay algunas cosas a corregir
1) El campo estado no tiene sentido. El elemento está o no está, eso lo manejás con dim. No debería haber "huecos" en el vector
2) Está mal definido cmpKey, debería ser
    int (*cmpKey)(elemTypeKey, elemTypeKey);

Esto asumiendo que estado es para saber si está libre u ocupado, y que cmpKey es una función para comparar dos claves, para saber si una clave ya está o no.
Y si elegiste vector me imagino que no vas a insertar ordenado por clave.

**Comment by julietaTechenski** [comment]
Ahhh ok genial, gracias.

**Comment by julietaTechenski** [comment]
Buenas, hice otro struct del parcial del cuatri pasado . No me convence la manera en la que definí lastRemoved, lo podria definir como elemType y despues simplemente usar add(collection, collection->lastRemoved) cuando lo invoco desde la funcion?

typedef struct node{
	elemType elem;
	struct node *tail;
}node;

typedef struct collectionCDT{
	node * c;
	node * lastRemoved;
	size_t size;
	int (*cmp) (elemType e1, elemType e2);
}collectionCDT;

![888982c4-a38c-47fd-8603-56e9119e7109](https://user-images.githubusercontent.com/119064935/204829797-2ce748a3-802c-4bf7-8126-d4569e319a41.jpg)

**Comment by julietaTechenski** [comment]
Mando también uno del mismo parcial pero ejercicio 4.  Una consulta, cuando la consigna me dice hacer la funcion putElement lo mas eficiente posible, significa que debería crear un vector y se lo pase a la funcion put o simplemente asigno el elemento en la posicion?

typedef struct node{
	elemType elem;
	size_t estado;
}node;

typedef struct vectorCDT{
	node *vec;
	size_t dim; // espacio reservado
	size_t size; // elementos ocupados
	int (*cmp) (elemType e1, elemType e2)
}vectorCDT;

![f70dce78-a8a4-40cb-b1b2-3e93be8d2eb9](https://user-images.githubusercontent.com/119064935/204855525-6059b0ea-2644-401d-b89c-6eb5f4c6d332.jpg)

**Comment by marcelogarberoglio** [comment]
Al ser dos ejercicios distintos sería mejor crear una nueva issue para c/u, para que sea más práctico poder ir respondiendo.

En cuanto a lastRemoved no puede ser un puntero a elemType, fijate en los ejemplos que no se aplica sólo a uno. Podés ir deshaciendo las 2, 3, etc últimas borradas, por lo que tené que ir apilando los que se van borrando


En el otro caso (putElement), te dice que tendrá pocas posiciones libres, y que esa función debe ser eficiente, entonces sí, tenés que usar un vector, sabiendo de alguna forma qué posición está ocupada y cuál libre.

**Comment by julietaTechenski** [comment]
Genial, gracias.
