### ISSUE TITLE
Consulta struct ej 5 - 2022 1C 

### ISSUE THREAD

**Issue by julietaTechenski** [marcelogarberoglio/PI#86]
Buenas, mando la estructura del ejercicio 5 del parcial del cuatri pasado. Desde ya, muchas gracias.

typdef struct pagina{
	char **pagina;  // vector de char *
	size_t dim; //
	size_t size;  // cantidad de parrafos almacenados en la pagina
}pagina;

typedef struct phrasesCDT{
	pagina *libro;
	size_t dim; 
	size_t cantParrafos; // cantidad de parrafos en todo el texto
}phrasesCDT;

![292d3643-b946-4d6a-beeb-99efea2927f0](https://user-images.githubusercontent.com/119064935/204907016-a71115a8-2e04-401e-84ba-362ffbdd1180.jpg)
![b54d4834-6002-4f1e-aa9b-2704e0051156](https://user-images.githubusercontent.com/119064935/204907073-74b49662-d424-4d04-9f9e-1e49f34b6c78.jpg)

**Comment by marcelogarberoglio** [comment]
Me parece que habría que guardar la longitud de cada frase, para facilitar las funciones get y phrases.

**Comment by julietaTechenski** [comment]
Ahh genial, con razón luché tanto, gracias.
