### ISSUE TITLE
Ejercicio de la prueba de respondus

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#9]
Buenas, el viernes pasado traté de hacer el ejercicio de la prueba de respondus pero estaba apurado y no logré que me salga así que lo dejé para después. Hoy lo volví a intentar, costó un poco pero creo que salió. Lo paso por acá así me decís si está bien. Gracias!

```C
// Crear una función que reciba dos vectores y sus dimensiones y remueva del primer vector todos los
// elementos que también están en el segundo. La función debe retornar la nueva dimensión del primer vector.
// Los vectores se pasan en orden ascendente.

#include <stdio.h>

void printArray(int v[], int dim);
int removeV2FromV1(int v1[], int dim1, int v2[], int dim2);

int main() {
	int dim1 = 12;
	int v1[] = {1, 1, 3, 3, 4, 5, 6, 7, 7, 7, 8, 9};
	int dim2 = 5;
	int v2[] = {1, 2, 5, 7, 9};
	int newDim1 = removeV2FromV1(v1, dim1, v2, dim2);
	printArray(v1, newDim1);

	return 0;
}

int removeV2FromV1(int v1[], int dim1, int v2[], int dim2) {
	// isInV2 == -1 --> No se si está o no.
	// isInV2 ==  0 --> Se que no está.
	// isInV2 ==  1 --> Se que está.
	int length = 0, isInV2 = -1;
	for (int i = 0, j = 0; i < dim1; ++i, isInV2 = -1) {
		while (j < dim2 && isInV2 == -1) {
			if (v1[i] < v2[j]) {
				isInV2 = 0;
			} else if (v1[i] == v2[j]) {
				isInV2 = 1;
			} else {
				++j;
			}
		}
		// Técnicamente no es necesario el "|| j == dim2" porque si se queda sin elementos v2
		// entonces va a salir del while con isInV2 en -1, y !(-1) es true. Pero lo dejo por claridad.
		if (!isInV2 || j == dim2) {
			v1[length++] = v1[i];
		}
	}
	
	return length;
}

void printArray(int v[], int dim) {
	printf("[ ");
	for (int i = 0; i < dim; ++i) {
		printf("%i%s", v[i], (i == dim - 1) ? " ]" : ", ");
	}
}
```

**Comment by fmorroni** [comment]
Desestimar el comentario del "|| j == dim2". Sí es necesario. No se por qué puse que !(-1) era true jajaja

**Comment by marcelogarberoglio** [comment]
Está bien. La pregunta es si te salió bien de primer intento o tuviste que correrlo en la computadora para comprobar que funcionaba, viste que no y tuviste que corregirlo. Menciono esto porque la forma en que manejas los posibles valores de isInV2 es un tanto confusa. Hubiese quedado más simple si el while interno lo hacés en una función auxiliar, que reciba el vector y desde dónde buscar, y retorne 1 si lo encontró y 0 sinó. Obviamente manteniendo la misma eficiencia que en tu solución.

**Comment by fmorroni** [comment]
La que puse acá es la primer versión que compilé y corrí. Pero sí estuve un rato analizándolo a mano/mentalmente y cambiando cosas que no funcionaban o eran feas. Y si eso te parece confuso ni te cuento cómo era al principio jajaja

Lo de hacer la búsqueda por separado ni lo consideré la verdad, parecía una función simple y tenía más o menos una idea de lo quería hacer entonces lo encaré de una. Aunque al final no fue tan simple como esperaba. 
Mañana veo como sería hacer esa función de búsqueda por separado.

Gracias!
