### ISSUE TITLE
Duda TPE

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#90]
Buenas, una duda respecto a los mensajes de error. El enunciado dice:

`El programa no debe abortar por ningún motivo y ante cualquier error se debe mostrar un mensaje adecuado. En todo caso será el front-end (nunca el back-end) el que -ante un error- podrá decidir que no tiene sentido seguir ejecutando la aplicación.`

Esos mensajes los imprimimos desde el back no? Por ejemplo  usando perror() o fprintf(stderr, ...) directo desde el punto de falla.
O tenemos que dejar que el front se encargue de eso leyendo errno por ejemplo?

**Comment by marcelogarberoglio** [comment]
Como se explicó en clase, el usuario del backend son funciones (de front u otro backend), y el usuario del front es una persona. Por lo tanto, si el mensaje de error es para que lo vea una persona, el que se lo tiene que comunicar es el front. Incluso, uno podría tener versiones de un mismo programa en español, inglés, etc.; en este caso el backend tendría que ser exactamente el mismo, sin saber en qué idioma lo usará una persona.

**Comment by fmorroni** [comment]
Hmm okay, pero eso limita bastante los mensajes de error que podés dar. Si mi función tiene que devolver un puntero puedo devolver NULL en caso de error, pero si tengo varios tipos de error no se cuál es. Y puedo setear errno pero los mensajes de errno son limitados.
Podría hacer una especie de custom errno también pero no creo que valga la pena.

En cualquier caso gracias.
