### ISSUE TITLE
Duda sobre datasets TPE

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#91]
Buenas, en cuanto a los datasets que recibimos, podemos asumir que cada línea no va a superar una cierta longitud (255 caracteres por ejemplo)? O tenemos que hacerlo para largo de línea genérico?

**Comment by marcelogarberoglio** [comment]
Se asegura que los datos son correctos y el formato también, por lo tanto pueden asumir un tamaño máximo.

**Comment by fmorroni** [comment]
Claro pero pregunto más que nada por los nombres de los sensores o las Hourly_Counts que técnicamente pueden ser tan largos como quieras.

**Comment by marcelogarberoglio** [comment]
>  pueden asumir un tamaño máximo.

**Comment by fmorroni** [comment]
ok gracias
