### ISSUE TITLE
consulta git

### ISSUE THREAD

**Issue by julianBogado1** [marcelogarberoglio/PI#92]
Buenas tardes, estuve intentando crear un repositorio en github pero cuando trato de hacer un push o un clone me sale el error:

![image](https://user-images.githubusercontent.com/113400047/205512948-b08e8d8f-eb64-4061-89d3-d63794a01085.png)

y cuando trato de pushear un repositorio local:

![image](https://user-images.githubusercontent.com/113400047/205512982-f2f456b2-325d-46b0-8228-b290f7ab765c.png)

ya probe ejecutado los comandos sugeridos apenas se crea un repositorio en github, y tambien los que vimos en la clase de git, que son los siguientes:

![image](https://user-images.githubusercontent.com/113400047/205513030-c105c271-d32b-4158-9066-7e6c934acf33.png)

![image](https://user-images.githubusercontent.com/113400047/205513057-517c825d-ded3-4da6-b189-b39b5d4b1e4f.png)

creo que debe ser algun error de autentificacion pero no estoy seguro

**Comment by marcelogarberoglio** [comment]
¿Viste el tutorial para crear la "SSH key"?

**Comment by fmeola** [comment]
@julianBogado1 Hola Julián. Parece ser un error de configuración del SSH. 
Probá clonar el repositorio usando HTTPS y no SSH (en la captura que adjuntás se ven los dos botones para elegir). Con eso ya debería funcionarte.
Para poder trabajar con un repositorio por SSH tenés que primero configurar una clave SSH en tu computadora y cargarla en GitHub. En la captura de la diapositiva que mandás está el link al tutorial para hacerlo. Y [acá](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey) te dejo otro link con los errores más comunes.

**Comment by julianBogado1** [comment]
la opcion de https tambien la habia probado, pero cuando corro los comandos no me sale ningun mensaje de verificiacion o de confirmacion.
Voy a revisar el link con errores comunes y cualquier cosa consulto de nuevo.

Otra duda, quizas media obvia, se puede manipular un repositorio remoto desde pampero? supongo que no, pero cuando lo probe no sabia si el error era mio o de pampero (igual estoy usando wsl por las dudas)

**Comment by fmeola** [comment]
@julianBogado1 Ok. Respecto a Pampero, sí. Podés clonar tu repositorio en tu home de Pampero y hacer pull y push desde esa terminal.
