### ISSUE TITLE
Duda TPE separación back-end front-end

### ISSUE THREAD

**Issue by fmorroni** [marcelogarberoglio/PI#93]
Del enunciado:

`Se debe realizar un diseño donde se separe claramente la lectura y preparación de datos (front-end) del almacenamiento y procesamiento de los datos (back-end). `

No entiendo cuál sería "preparación de datos" que le corresponde al front-end. Por ejemplo, yo para parsear los datos del archivo de sensores.csv tengo una función `int parseSensors(SensorList sl, FILE* sensors_csv)` de back-end donde `SensorList` es un adt con un array de estructuras `Sensor`.
Y esta función recibe un puntero al archivo, valida los datos de cada sensor y los guarda en el array. Estaría bien eso?
O qué tengo que pasarle al back en vez del puntero al archivo?

**Comment by marcelogarberoglio** [comment]
El enunciado es claro:
-lectura: leer los datos (del archivo, seguramente de a líneas)
-preparación: obtener los datos correspondientes de la línea.

También el enunciado dice : "recordar que el back-end no debe saber cuál es origen o el destino de los datos"
y "El back-end debería servir también para otros front-ends. ..  o que la información sea leída por teclado o desde una base de datos."
