### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by Diego-Rabinovich** [marcelogarberoglio/PI#96]
Hola, como están? 
Tenemos una duda con respecto a la parte del enunciado (en la sección 8). Donde dice  que se tomará en cuenta "el correcto diseño de el/los TAD, que debería poder ser **_fácilmente adaptable para otras codificaciones, nombres o formatos de archivos_** " ¿a qué hace referencia "otras codificaciones, nombres o formatos de archivos"?

Nosotros estamos interpretando que tiene que ver con el formato en que se recibe la información (por ejemplo en vez de venir separada por ; puede venir separada por alguna otra marca) o bien que se cambie el nombre de algún archivo, queríamos saber si se refiere a esto o alguna otra cosa. 

Desde ya, muchas gracias

**Comment by marcelogarberoglio** [comment]
Si bien no es la misma pregunta, sobre la relación entre el backend y los archivos se contestó en https://github.com/marcelogarberoglio/PI/issues/93
Está claro que el TAD está (o debería estar) en el back-end
