### ISSUE TITLE
Consulta enunciado

### ISSUE THREAD

**Issue by Diego-badin** [marcelogarberoglio/PI#97]
Buenas tardes Marcelo, tengo un duda respecto al diseño de nuestro TAD. Debemos plantear un TAD dedicado a las tres primeras queries o uno que pueda contemplar las otras dos?
Muchas gracias

**Comment by marcelogarberoglio** [comment]
Si tienen que hacer las primeras tres, concéntrense en esas tres.

**Comment by Diego-badin** [comment]
Muchas gracias.
