### ISSUE TITLE
Consulta TPE - cantidad de días del año

### ISSUE THREAD

**Issue by julietaTechenski** [marcelogarberoglio/PI#98]
Hola, buenos días, vimos que ya había respondido una pregunta al respecto pero no terminamos de entender completamente. Queríamos realizar una consulta con respecto a la cantidad de días por los que necesitamos dividir para realizar el promedio. Cuando miramos los datos nos encontramos con que en 2022 solo se registran datos hasta Mayo ¿Nos basamos en los días que se realizo un registro de los datos o de los días totales de 2022? Desde ya, mil gracias.

**Comment by marcelogarberoglio** [comment]
Está muy bien la pregunta.
Lo correcto sería tomar únicamente la cantidad de días en los que hubo muestra y no la cantidad total de días del año. En tu ejemplo serían los días que pasaron entre 1/1 y el 31/5. Pero a efectos de lo que buscamos evaluar en este TPE no es necesario que hagan la cuenta exacta, pueden dividir siempre por la cantidad total de días del año (365 ó 366)
