### ISSUE TITLE
Consulta TPE

### ISSUE THREAD

**Issue by AgusAlonso1** [marcelogarberoglio/PI#99]
Buenas
Tenia una consulta respecto a la generalidad del TP. Con mi grupo estamos discutiendo acerca de como "guardar" la información de los archivos csv. Por ejemplo, para el q1 que debemos contar el total de las iteraciones de los sensores, nos resulta mas eficiente guardar únicamente el total de iteraciones por año, que por hora.  A su vez, si en el futuro se desea implementar una query que analice el promedio de iteraciones por hora, en este caso deberíamos "guardar" los datos por hora lo cual requiere de mas memoria.

La pregunta es si únicamente trabajamos en función de las querys que debemos llevar a cabo o pensando mas en la generalización.
Desde ya muchas gracias.

**Comment by marcelogarberoglio** [comment]
Deben desarrollarlo para que sea eficiente para las queries pedidas. Cuando decimos que debe ser "fácilmente adaptable" no estamos pidiendo que ya dé soporte a posibles extensiones sino que esté escrito en forma clara, modularizada, códigos no acoplados, etc. de forma tal que resulte fácil de entender y de modificar.
